### ISSUE TITLE
[Translatable] Example how print translatable values in twig (knp translatable behaviour)

### ISSUE THREAD

**Issue by kvaje** [KnpLabs/DoctrineBehaviors#100]
Hi,

Is any example available how print translatable field values in twig?

**Comment by grekpg** [comment]
i think about this way

`/**
     * @return string
     */
    public function getContent()
    {
        if($this->translate()->getLocale()!=AppBundle::DEFAULT_LOCALE)
            return $this->translate()->getContent();

        return $this->content;
    }
`

in this way default locale i store in original entity and user next db query only for translations. 

but for simple 

{{category.getName}}

its enough in main entity

  `
public function getContent(){
return $this->translate()->getContent();
}
`

and we have current lang version and ide helper for getContent method

**Comment by patie** [comment]
any news on this?

**Comment by jkhamler** [comment]
I'm struggling with this myself - using Symfony 4 and an absolute vanilla use case. Product and ProductTranslation. Adding the following to my Product class avoids a fatal error but it's returning blank strings.

``` 
public function __call($method, $arguments)
    {
        return $this->proxyCurrentLocaleTranslation($method, $arguments);
    }
```

**Comment by TomasVotruba** [comment]
Resolved as answered

**Comment by bor-yo** [comment]
This is how I solved it, hope it helps to someone

`class Category implements TranslatableInterface
{
    use TranslatableTrait;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName()
    {
        if(!$this->translations[$this->getCurrentLocale()]) {
            return null;
        }
        return $this->translations[$this->getCurrentLocale()]->getName();
    }
}`

**Comment by bor-yo** [comment]
This is how I solved it
`class Category implements TranslatableInterface
{
    use TranslatableTrait;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    
    private $name;

    
    public function getName()
    {
        if(!$this->translations[$this->getCurrentLocale()]) {
            return;
        }
        $this->name = $this->translations[$this->getCurrentLocale()]->getName();
        return $this->name;
    }
}`
