### ISSUE TITLE
[Loggable] Problem in Loggable with master version of Doctrine

### ISSUE THREAD

**Issue by raziel057** [KnpLabs/DoctrineBehaviors#101]
Hello,

I notice there is a problem from the following commit in Doctrine:

https://github.com/doctrine/doctrine2/commit/53a5a48aed7d87aa1533c0bcbd72e41b686527d8

If an entity is `loggable` and contains OneToMany or ManytoMany relations, there is an exception when modifying the entity.

**Comment by Einenlum** [comment]
Seems it was merged. Closing the issue.
