### ISSUE TITLE
[Translatable] Accessing translatable in Doctrine query builder

### ISSUE THREAD

**Issue by a1ku** [KnpLabs/DoctrineBehaviors#108]
Hello,

I have Category and CategoryTranslation entities. Both are connected with Translatable.
I need to join CategoryTranslation back into the Category in Doctrine query builder.

`$qb->join('ct.translatable', 'c');` 
(translatable comes from `Knp\DoctrineBehaviors\Model\Translatable\Translation` trait that is used by CategoryTranslation entity)

yells 

> "The parent object of entity result with alias 'c' was not found".`

Is it even possible? How to do that?

**Comment by glennthehuman** [comment]
How was this resolved?
