### ISSUE TITLE
[Sortable] The documentation for Sortable misses

### ISSUE THREAD

**Issue by greg0ire** [KnpLabs/DoctrineBehaviors#117]
There even is a Feature Request for it (see #59 )

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
