### ISSUE TITLE
Create multiple translations at once

### ISSUE THREAD

**Issue by feedmeastraycat** [KnpLabs/DoctrineBehaviors#121]
Not sure if this is an issue, or if I just misunderstand the documentation or if I have some other issue in my implementation. But Im using this lib in a Silex project and trying to do a Category entity with translation. It works some... But when I try to do like the following example from the readme.md file:

```
$category = new Category;
$category->translate('fr')->setName('Chaussures');
$category->translate('en')->setName('Shoes');
$em->persist($category);

// In order to persist new translations, call mergeNewTranslations method, before flush
$category->mergeNewTranslations();

$category->translate('en')->getName();
```

Only the last one is created, in this case "en". If I do $category->translate('fr'), then "en", then "sv" only "sv" is created.

Do you have to persist, merge and flush in between each call to $category->translate('x')? Or do I have some error in my implementation?

**Comment by brunoew** [comment]
> Sorry about this. It seems it was my implementation. :)
> 
> After your reply I did some remaking. Im implementing this in a Silex project and was using simple annotation mode in Doctrine to start with. I've changed that. Unfortunately I've changed some more things so Im not sure exactly what was the cause.
> 
> But we can close this now knowing it isn't you. :)

How you did the integration with Silex?  
Thanks!
