### ISSUE TITLE
Validate translation field

### ISSUE THREAD

**Issue by h3llr4iser** [KnpLabs/DoctrineBehaviors#124]
How Can i validate a translation field?

```
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Em\Bundle\CmsBundle\Entity\Metatag;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="zona_translation")
 */
class ZonaTranslation
{
    use ORMBehaviors\Translatable\Translation ;

    /**
     * @ORM\Column(type="string", nullable=true)
     * @Assert\NotBlank()
     */
    private $title;
```

**Comment by charlieWasp** [comment]
I would like to reopen this issue, because now I run into same question. How translatable entities is supposed to be validated? How I should declare FormType for translatable entity?

**Comment by docteurklein** [comment]
ha, an idea comes to my mind: you need to add a `@Assert\Valid` on the translatable field, in order to let the validator walker walk through the children.

Otherwise, it's a typical form.

**Comment by Mondane** [comment]
Adding a validation.yml to the bundels config appears to work:

```yaml
Class\Of\Translatable\Entity:
    properties:
        translations:
            - Valid: ~
```

Taken from https://github.com/a2lix/TranslationFormBundle/issues/104#issuecomment-62743276

**Comment by evgeni4** [comment]
not work
