### ISSUE TITLE
[Tree] Trait type hinting

### ISSUE THREAD

**Issue by sagikazarmark** [KnpLabs/DoctrineBehaviors#128]
I have a problem with the usage of interfaces and type hinting: for example `Node` functions has hinting for `NodeInterface`. It means, that any entities using `Node` (and implementing `NodeInterface`) can be used with each other (which is wrong). Eg. a Category node should not be able to added to any other entity which is not category.

Possible fix: use the `self` keyword for type hinting in traits, and remove all type hinted functions from the interface. This way the type hint will always point to the current class, not the interface which in turn means that only the same entity can be added to the tree.

**Comment by digitalkaoz** [comment]
learn something new everyday :)

**Comment by TomasVotruba** [comment]
Closing as very old issue. Feel free to send PR with such a feature though
