### ISSUE TITLE
[Translatable] After Bundle Upgrade: ReflectionException Property Namespace\MyBundle\Entity\CategoryTranslation::$id does not exist

### ISSUE THREAD

**Issue by giovkanata** [KnpLabs/DoctrineBehaviors#154]
All worked as expected but after the upgrade:
- Removing knplabs/doctrine-behaviors (dev-master b7083e9)
- Installing knplabs/doctrine-behaviors (dev-master 2ff5031)

I get the error in the title.

What do I need to write in composer.json to do the downgrade?

PS: I use Standard Symfony 2.5.5 with upgraded components. What do I need to show to get you able to reproduce that error?

Thanks!

**Comment by webspin** [comment]
issue still present in dev-master...

**Comment by Einenlum** [comment]
Do you still experience this issue in the last versions, or was it fixed by #158 ?

**Comment by giovkanata** [comment]
Sorry @Einenlum for the late reply but I was away for some time. The project from which I started this issue is finished long time ago (and now it's followed by others), but soon I should start another one using Symfony4.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
