### ISSUE TITLE
[Translatable/Timestampable] Error when using Translatable and Timestampable behaviors

### ISSUE THREAD

**Issue by drkdev** [KnpLabs/DoctrineBehaviors#163]
I get an error when attempt to persist an Entity using both Translatable and Timestampable:

Catchable Fatal Error: Argument 1 passed to MyBundle\Entity\CategoryTranslation::setCreatedAt() must be an instance of DateTime, null given, called in myproject/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 438 and defined in myproject /vendor/knplabs/doctrine-behaviors/src/Model/Timestampable/TimestampableMethods.php line 45"

It seems the error occurs when it attempts to save the xxxTranslation entity

**Comment by netandreus** [comment]
Just start using Timestampable for TranslatableEntity and it doesn't track changes in translations fields.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
