### ISSUE TITLE
hash/checksum behavior

### ISSUE THREAD

**Issue by cordoval** [KnpLabs/DoctrineBehaviors#164]
I was wondering if a hash/checksum behavior is possible and if there is such a thing somewhere or anyone has done it already. Thanks.

**Comment by Einenlum** [comment]
@cordoval  Can you explain in a more detailed way what feature you are talking about?

**Comment by cordoval** [comment]
I don't use this anymore sorry about my issue.

**Comment by Einenlum** [comment]
@cordoval Thanks for you answer :).
