### ISSUE TITLE
comparison to gedmo behaviors

### ISSUE THREAD

**Issue by cordoval** [KnpLabs/DoctrineBehaviors#165]
how does these behaviors compare to gedmo behaviors?

**Comment by MAXakaWIZARD** [comment]
@cordoval Translatable is far better here, for example

**Comment by docteurklein** [comment]
It also tries to be more near from the language itself, by using traits f.e

**Comment by cordoval** [comment]
I see, thanks guyz. :older_man: just hope people will see this when they compare. :+1:
