### ISSUE TITLE
Make a slug with nestedTranslation entity

### ISSUE THREAD

**Issue by khyor** [KnpLabs/DoctrineBehaviors#171]
Hello,
I have two entities "Page" and "PageCategory"  using Sluggable and translatable.

example category name : Product (EN) and Produits (FR)
example page title : My little page (EN) and Ma petite page (FR)
I want to use the PageCategory slug to generate the slug page like :
- product/my-little-page 
- produit/ma-petite-page

i don't get anywhere with the function getSluggableFields() In PageCategoryTranslation to retrieve the name in the bound entity.

can you help me ?

**Comment by docteurklein** [comment]
hello! You just need to override the `generateSlug` method, and populate the `$this->slug` property the way you like.

**Comment by khyor** [comment]
i try but i can't get the good translate slug of my PageCategory.
I want to use each translate version of my slug category to populate each slug page but i get only one  version.

* product/my-little-page
* product/ma-petite-page (i want produit/ma-petite-page)

I try to use locale of my PageTranslation to get the good slug, but doesn't work !

    <?php 
    class PageTranslation
    {
        use ORMBehaviors\Translatable\Translation;
        use ORMBehaviors\Sluggable\Sluggable;

       public function generateSlug() {
       
           $localTranslation = $this->getLocale();
           $categorySlug = $this->getTranslatable()->getCategory()->translate($localTranslation)->getSlug();

           /*............*/

           $this->slug = $categorySlug.'/'.$urlized;
       }

    }
    ?>

Any idea ?
