### ISSUE TITLE
[Translatable] Feature: ability to choose the class translation name

### ISSUE THREAD

**Issue by asprega** [KnpLabs/DoctrineBehaviors#172]
What about adding a custom annotation (or even a dead simple static method) to translatable classes to override the default `<classname>Translation` class used to establish the mapping?

How it is now:
Acme\Model\Category <=> Acme\Model\CategoryTranslation

How it could be with the proposed feature:
Acme\Model\Category <=> Acme\Model\Translation\CategoryTranslation

The reason why I'm proposing this is that I find very useful to separate entities and translations in different namespaces: this allows for less pollution and better organization when you have many translatable entities.

If you guys think this may be a nice addition, I can provide a pull request.

**Comment by docteurklein** [comment]
I thought it was configurable through a static method, but it appears it isn't https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php#L206.

Feel free to PR something.

I'm not sure i'm willing to introduce annotations (even tho it would be a great way to configure it :) )
It's just that until now, we didn't need annotations.

Anyway, let's try something.

**Comment by asprega** [comment]
I agree with you, an annotation would seem overkill... But you already require doctrine/common which in turns requires doctrine/annotations, so no additional dependencies would be (practically) needed. There may be other use cases for custom annotations in other behaviors (just guessing, didn't look at them yet).

Alternatively, would you prefer using an interface to dictate which static method should be implemented? Or just duck typing?

**Comment by docteurklein** [comment]
a trait method might be enough.

**Comment by nick4fake** [comment]
https://github.com/KnpLabs/DoctrineBehaviors/pull/166

**Comment by asprega** [comment]
The trait actually already has a method to return the translation class (https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Model/Translatable/TranslatableMethods.php#L152). There are 2 problems:
1. It isn't currently used by the listener which establishes the mapping (only by the trait itself)
2. AFAIK it is not possible to override trait methods without triggering an E_NOTICE which, depending on your error reporting settings, might cause fatals (in my case, it does with production settings).

Alternatives would seem to be:
- using an annotation
- implementing an additional interface (only specific for overriding the translation name)
- quick and dirty duck typing without overriding the trait method.

Please let me know if I'm missing something.

**Comment by docteurklein** [comment]
@asprega woah! thanks for such a detailled answer!

I forgot about this method. I guess we should use it in the listener then.
We could maybe make it static to simplify its invokation ?

Anyway, concerning the override of a trait method, you **can** do it. Only property overrides are forbidden: http://3v4l.org/buImF

I guess it might be an option, even tho #166 already implemented the annotation way.

**Comment by asprega** [comment]
Turns out I *was* missing something then! Good to know, I'll prepare a PR shortly.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
