### ISSUE TITLE
Sluggable and accents

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#173]
Hello,

sluggable is not handling accents. Is that normal or did I miss something in the settings ?

**Comment by CharlyPoppins** [comment]
There is a problem with iconv.
$sluggableText = "Châteauneuf du Pape";
$usableValues = iconv('UTF-8', 'ASCII//TRANSLIT', $sluggableText);
echo $usableValues; // Ch?teauneuf du Pape

**Comment by CharlyPoppins** [comment]
> Please note that iconv('UTF-8', 'ASCII//TRANSLIT', ...) doesn't work properly when locale category LC_CTYPE is set to C or POSIX. You must choose another locale otherwise all non-ASCII characters will be replaced with question marks. This is at least true with glibc 2.5.

> Example:
> <?php
> setlocale(LC_CTYPE, 'POSIX');
> echo iconv('UTF-8', 'ASCII//TRANSLIT', "Žluťoučký kůň\n");
> // ?lu?ou?k? k??
> 
> setlocale(LC_CTYPE, 'cs_CZ');
> echo iconv('UTF-8', 'ASCII//TRANSLIT', "Žluťoučký kůň\n");
> // Zlutoucky kun
> ?>

**Comment by docteurklein** [comment]
Unfortunatly, I never had to run into those problems, and I have no idea how transliteration works :)

**Comment by markitosgv** [comment]
accents like áéóèàñß not been converted i think is possible to modify generateSlug function with this

```php
public function generateSlug()
{
    if ( $this->getRegenerateSlugOnUpdate() || empty( $this->slug ) ) {
        $fields = $this->getSluggableFields();
        $usableValues = [];

        foreach ($fields as $field) {
            // Too bad empty is a language construct...otherwise we could use the return value in a write context :)
            $val = $this->{$field};
            if ( !empty( $val ) ) {
                $usableValues[] = $val;
            }
        }

        if ( count($usableValues) < 1 ) {
            throw new \UnexpectedValueException('Sluggable expects to have at least one usable (non-empty) field from the following: [ ' . implode($fields, ',') .' ]');
        }

        // generate the slug itself
        $sluggableText = implode($usableValues, ' ');
        $sluggableText = strtr(utf8_decode($sluggableText), utf8_decode('ŠŒŽšœžŸ¥µÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýÿ'),
            'SOZsozYYuAAAAAAACEEEEIIIIDNOOOOOOUUUUYsaaaaaaaceeeeiiiionoooooouuuuyy');
        $urlized = strtolower( trim( preg_replace("/[^a-zA-Z0-9\/_|+ -]/", '', iconv('UTF-8', 'ASCII//TRANSLIT', $sluggableText) ), $this->getSlugDelimiter() ) );
        $urlized = preg_replace("/[\/_|+ -]+/", $this->getSlugDelimiter(), $urlized);

        $this->slug = $urlized;
    }
}
```

What do you think about insert this conversion?

```php
$sluggableText = strtr(utf8_decode($sluggableText), utf8_decode('ŠŒŽšœžŸ¥µÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýÿ'),
            'SOZsozYYuAAAAAAACEEEEIIIIDNOOOOOOUUUUYsaaaaaaaceeeeiiiionoooooouuuuyy');
```

Words like 'Café', 'Niño', 'ße' become 'cafe', 'nino', 'be'

**Comment by kuczek** [comment]
@markitosgv It not supports polish characters ążśźęćńół ĄŻŚŹĘĆŃÓŁ

**Comment by kuczek** [comment]
And look at #162 it solve that problem.

**Comment by MAXakaWIZARD** [comment]
@CharlyPoppins I've added your examples as test cases in #162

**Comment by CharlyPoppins** [comment]
Thanks, not used to git yet. So that means I need to wait an "admin" to merge your pull request #162 and then I can do a *composer update* of that git : "knplabs/doctrine-behaviors": "dev-master".
Am I right ?

**Comment by MAXakaWIZARD** [comment]
@charlypoppins exactly

**Comment by CharlyPoppins** [comment]
Ok perfect :) Thanks again
