### ISSUE TITLE
Softdeletable: Auto filter out results?

### ISSUE THREAD

**Issue by lopsided** [KnpLabs/DoctrineBehaviors#175]
Hi,

I have used the Stof/Gedmo doctrine behaviours in the past but thought I would use this bundle for my next project. However I noticed that there is no filtering of select query results when using the softdeletable behaviour like there is here: https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/Filter/SoftDeleteableFilter.php

Are there any plans to implement this behaviour in this bundle or is it considered outside of the scope?

Thanks

**Comment by docteurklein** [comment]
hello! I guess it could be doable by providing a specific repository method (trait?)  that adds a filter automatically. But it's not out of scope, we just didn't implement it. If Gedmo does it already, it might be possbile to reue it ?

**Comment by lopsided** [comment]
Thanks, yes that's what I did in the end, I just copied the Gedmo filter into our project with a few slight tweaks. I've put it in a gist in case it helps anyone else: https://gist.github.com/lopsided/b32c819d7bf4edeea00a
