### ISSUE TITLE
[Translatable] Identifier name is too long

### ISSUE THREAD

**Issue by NV-iloweb** [KnpLabs/DoctrineBehaviors#178]
Hello,

I encountered a problem with the method used for the Translatable behavior.
`SQLSTATE[42000]: Syntax error or access violation: 1059 Identifier name 'iloweb_page_block_content_disclaimer_translation_unique_translation' is too long`

The method used in the TranslatableSubscriber is a concatenation of the table name and '_unique_translation' which can leads to this kind of problem.
Wouldn't it be better to use a hash like that `uniq_cbfaabb32c2ac5d34180c698` ?

**Comment by docteurklein** [comment]
We need reproducibility of the name, that's the only constraint I guess.

I'm not sure yet how to solve it, but if you find one, don't hesitate to PR.

**Comment by NV-iloweb** [comment]
Why not using the same method as Doctrine ?
I overrided the whole TranslatableSubscriber (since everything is in private, I don't understand why..) and used the same methods as Doctrine
```
protected function generateIdentifierName($columnNames, $prefix = '', $maxSize = 30)
    {
        $hash = implode(
            "",
            array_map(
                function ($column) {
                    return dechex(crc32($column));
                },
                $columnNames
            )
        );

        return substr(strtoupper($prefix . "_" . $hash), 0, $maxSize);
    }
```
It works like a charm.
I can't do any PR because I don't write tests and I copy / pasted the method Doctrine uses since I couldn't find a way to get access to the Table object from the TranslatableListener.

**Comment by docteurklein** [comment]
It should indeed be possible to override this behavior without having to copy paste the whole class.
But instead of using protected methods, we should favor composition, if possible.

Concerning the way doctrine names them, i always find them criptic and non-semantic. If possible, it would be awesome to avoid it, and use hashes only when needed (>20 chars for ex).

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
