### ISSUE TITLE
Release new stable

### ISSUE THREAD

**Issue by Rvanlaak** [KnpLabs/DoctrineBehaviors#180]
The Translatable behaviour really acts weird when I'm iterating over a Translatable based on the locales as I describe [in a topic on the TranslatableFormBundle](https://github.com/a2lix/TranslationFormBundle/issues/78#issuecomment-73280553).

This is already fixed in [this commit](https://github.com/KnpLabs/DoctrineBehaviors/commit/8077613800c87e0119fe6734f463c245e4dd5f97) but it isn't released in a stable tag yet.

Please release `v1.1`

**Comment by pilot** [comment]
https://github.com/KnpLabs/DoctrineBehaviors/releases/tag/v1.0.3

**Comment by Rvanlaak** [comment]
> pilot released this 7 hours ago

:+1:  Was I really too impatient? ;)

> Rvanlaak commented 2 hours ago

**Comment by pilot** [comment]
:D time collapse
