### ISSUE TITLE
Blameable fields broken on 1.0.3

### ISSUE THREAD

**Issue by sgilberg** [KnpLabs/DoctrineBehaviors#181]
I just updated from 1.0.2 to 1.0.3 and I'm getting errors like the one below for every query on my site:
"Column not found: 1054 Unknown column 'm0_.createdBy' in 'field list'"
I can't tell from the latest changes what would cause this. Do I need to update something in my configuration? Any help is appreciated.

**Comment by sgilberg** [comment]
I figured it out - I had overwritten the "knp.doctrine_behaviors.blameable_listener.user_entity" parameter in my config, and I see now that you have renamed "listener" to "subscriber". Subtle.

**Comment by docteurklein** [comment]
oh yes. that was indeed a big BC break we didn't handle correctly. Sorry for that.
