### ISSUE TITLE
Hardcoded defaultLocale() in TranslatableMethods trait

### ISSUE THREAD

**Issue by markitosgv** [KnpLabs/DoctrineBehaviors#183]
Why is hard-coded return defaultLocale()

```php
    public function getDefaultLocale()
    {
        return 'en';
    }
```

When a translations is not found i need to set defaultLocale to another locale

**Comment by kuczek** [comment]
Same as #182.

**Comment by markitosgv** [comment]
sorry i close and comment in #182
