### ISSUE TITLE
Trouble with magic proxy

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#188]
Hi, I've got a problem with the magic proxy, it works fine in my app, and it works fine after an update.
But the first time I create the entity the magic does not work.
ps: I'm using a2lix/TranslationFormBundle
```
$categorie->translate('fr')->setLibelle("toto");
$em->persist($categorie);
$em->flush();

$categorie->translate('fr')->getLibelle(); // return "toto"
$categorie->getLibelle(); // return ""
```

**Comment by kuczek** [comment]
@CharlyPoppins You should use $categorie->setCurrentLocale('fr') and then it will work.

**Comment by CharlyPoppins** [comment]
It works perfectly :) Thanks
