### ISSUE TITLE
Sluggable+Translatable - slug not updated when updating translation

### ISSUE THREAD

**Issue by MAXakaWIZARD** [KnpLabs/DoctrineBehaviors#194]
I'm using both `Sluggable` and `Translatable` (`Article` and `ArticleTranslation`). `Sluggable` is configured like that:
```php
public function getSluggableFields()
{
    return ['title'];
}

public function getTitle()
{
    return $this->translate()->getTitle();
}
```
So there is an issue: when we update translations, slug is not updated since no changes have been made to `Article` entity (`Sluggable` only listens to `preUpdate` and `prePersit` callbacks on itself).

Similar edge case occurs when using `id` field as part of slug (`id` is not avaliable in `prePersist` callback):
```php
public function getSluggableFields()
{
    return ['id', 'title'];
}
```
So we don't get correct slug on entity creation.

**Comment by MAXakaWIZARD** [comment]
I see only one solution - use doctrine event listeners to manually call `generateSlug` and update sluggable entity.

**Comment by docteurklein** [comment]
I guess it's more a doctrine problem that could be resolved with doctrine patterns. (see hotify change stategies and co).
concerning id in slug, i guess there is no other solution than postPersist event.

**Comment by MAXakaWIZARD** [comment]
I solved those problems with such lifecycle event callback:
```php
/**
     * @ORM\PostUpdate
     * @ORM\PostPersist
     */
    public function updateSlug(LifecycleEventArgs $eventArgs)
    {
        $translatable = $this->getTranslatable();
        $oldSlug = $translatable->getSlug();
        $translatable->generateSlug();

        if ($oldSlug !== $translatable->getSlug()) {
            $repo = $eventArgs->getEntityManager()->getRepository(get_class($translatable));
            $repo->updateSlug($translatable);
        }
    }
```
