### ISSUE TITLE
No @ORM\Column annotations anymore?

### ISSUE THREAD

**Issue by lukasneubauer** [KnpLabs/DoctrineBehaviors#195]
Why there are missing `@ORM\Column` docblock annotations in every property trait (ver 1.0.3) e.g. Knp\DoctrineBehaviors\Model\Translatable\TranslationProperties? Have they been removed for a purpose? How should these traits be used now when these annotations are missing? I´ts like a car without wheels now.

**Comment by docteurklein** [comment]
hey there :)
We decided to normalize the way to define mappings: now they (fields and assocs) all are mapped by the listeners during the `loadMetadata` event.

**Comment by bocharsky-bw** [comment]
So how I should to use Timestampable fields now? I should to add `ORM\Column` annotation manually now?

**Comment by akovalyov** [comment]
@bocharsky-bw https://github.com/KnpLabs/DoctrineBehaviors/issues/218#issuecomment-108129057

**Comment by bocharsky-bw** [comment]
@akovalyov May bad! I forgot to import `orm-services.yml`. Thanks!
