### ISSUE TITLE
Loggable and objects

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#197]
Hi,

method **getUpdateLogMessage** crash with objects that don't have the magic **__toString**.

''in .../vendor/knplabs/doctrine-behaviors/src/Model/Loggable/Loggable.php at line 42''

**Comment by kuczek** [comment]
@CharlyPoppins Add __toString to this object.

@docteurklein Maybe if there is not __toString we should put ther var_export($var, true)? Or print that object cannot be mapped to string. (then i will also try if there is method getId and it yes, i'll put it there)

**Comment by CharlyPoppins** [comment]
Yes, I've done it,
just want to inform about it.
