### ISSUE TITLE
[Tree] and orderBy

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#200]
Hi, i'm using **Tree** on my class **Category**.

Currently I'm ordering my categories by the field **Order**.
Then I'm trying to order by hierarchy and also by order.

Do you have an idea of how I can do this ?

**Comment by docteurklein** [comment]
you can try to modify the query by overriding `moifyFlatTreeQB` or something, and add some `addOrderBy`.

**Comment by CharlyPoppins** [comment]
Yes, the problem is I didn't manage to "imagine" the query.
Do you have an idea ?
2nd option, I can have a recursive method that parse the tree, and add the "display order".

**Comment by docteurklein** [comment]
I imagine something like:

``` php
function buildFlatTreeQb(QueryBuilder $qb)
{
    $qb->addOrderBy($qb->getRootAlias().'.order', 'ASC');
}
```

**Comment by CharlyPoppins** [comment]
Then I'm having a recordset ordered by **order** only et not by hierarchy.
Considering in this example that the last digit is also the order (in a same branch), I need to have a list ordered like this :
´´´
P1
    P1.1
        P1.1.1
        P1.1.2
    P1.2
    P1.3
P2
    P2.1
    P2.2
        P2.2.1
        P2.2.2
P3
    P3.1
        P3.1.1
    P3.2
´´´

**Comment by docteurklein** [comment]
If I remember correctly, the base query already includes a ORDER BY ASC on the materialized path, which means the order should be correct.

**Comment by CharlyPoppins** [comment]
Yes, ordering by **materializedPath** works fine, then I didn't manage to add an order in each branch (in each level. Considering the order is between brackets.
```
Men (1)
    Jacket (1)
        Black (1)
        White (2)
    Pants (2)
    Shoes (3)
Women (2)
    Shoes (1)
    Jacket (2)
        White (1)
        Black (2)

**Comment by CharlyPoppins** [comment]
I'm not sure it can be possible with a SQL query, so I used a recursive function (base on an @moafred sample code).
Using **usort** function on each leaf/branch in the same branch and same level.
```
usort($temp, array("\Charly\My\Entity\Categorie", "triOrdre"));
...
public static function triOrdre($a, $b)
{
   return ($a->getOrdre() < $b->getOrdre()) ? -1 : 1;
}
```
