### ISSUE TITLE
Soft-deletable and remove from database

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#201]
Hi,
using Soft-Deletable, how can I remove entities from the database ?

**Comment by docteurklein** [comment]
using Doctrine?  you could use a  bulk operation for example.

**Comment by CharlyPoppins** [comment]
Ok, (yes using with doctrine).
I have to use a **DQL query**, so it won't trigger the soft-deletable subscriber, is that right ?
```
$em->createQuery('delete from categories c where c.deletedAt > ???);
```

**Comment by docteurklein** [comment]
exactly!

**Comment by docteurklein** [comment]
see http://doctrine-orm.readthedocs.org/en/latest/reference/batch-processing.html#bulk-deletes
