### ISSUE TITLE
Loggable and Translation

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#202]
Hi,
working on a **Category** and **CategoryTranslation**.

**getUpdateLogMessage()** is not triggered if I modify only **translations** of **Category**. 

Do I have to use **ORMBehaviors\Loggable\Loggable** on each **Category** and **CategoryTranslation** ? or is there another way ?

**Comment by docteurklein** [comment]
unfortunately, doctrine does not trigger events on an entity if only its associations change. You'll have to workaround a second listener of yours maybe.

**Comment by CharlyPoppins** [comment]
Ok thanks.
