### ISSUE TITLE
Soft-deletable remove my translations

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#203]
Hi,

I've got a class
```
class BlogCategorie
{
    use ORMBehaviors\SoftDeletable\SoftDeletable;
    use ORMBehaviors\Translatable\Translatable;
}
```
when i do **$em->remove($myCategorie)** it remove my corresponding **BlogCategorieTranslation** from the DB (the **BlogCategorie** is still existing with deletedAt set with current datetime).

What am I missing ?

**Comment by kuczek** [comment]
@CharlyPoppins Do you have SoftDeletable in BlogCategorieTranslation?

**Comment by docteurklein** [comment]
yep, you should try what @kuczek propoosed. 
I guess doctrine cascaded delete yur translation, and our listener doesn't handle relations.

**Comment by CharlyPoppins** [comment]
Thanks it works.
(It's strange because it was working on a test translatable entity, then not with my BlogCategorie.
I probably remove Translatable without paying attention(.
