### ISSUE TITLE
[Softdeleteable] Proposal: Document working SoftDeletable and unique constraint handling

### ISSUE THREAD

**Issue by spackmat** [KnpLabs/DoctrineBehaviors#204]
Hi, this bundle handles unique constraints and SoftDeletable well. I just tried it and it simply works. This is nice!

Proposal: The documentation could mention this pleasant fact, since the Doctrine Extension don't handle this well, see this workaround: http://intelligentbee.com/blog/2015/01/09/symfony2-gedmo-softdeletable-doctrine-entities-with-unique-index-columns/

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.

**Comment by spackmat** [comment]
@TomasVotruba this issue wasn't about a bug, but nevermind, you can keep it closed. :)
