### ISSUE TITLE
[Translatable] How to sort translatable entities taking the current locale into account?

### ISSUE THREAD

**Issue by Mondane** [KnpLabs/DoctrineBehaviors#205]
Let's say I have 4 records where field 'name' is in the translatable table for Dutch and English. 

| Id | Code | Name (English) | Name (Dutch) |
| --- | --- | --- | --- |
| 1 | komk | Cucumber | Komkommer |
| 2 | toma | Tomato | Tomaat |
| 3 | pine | Pineapple | Ananas |

To get the results, I join the translations with the main table. That can give me these results:

``` sql
SELECT * FROM item JOIN translations;
```

| Id | Code | Name | Locale |
| --- | --- | --- | --- |
| 1 | cucu | Cucumber | en |
| 1 | cucu | Komkommer | nl |
| 2 | toma | Tomato | en |
| 2 | toma | Tomaat | nl |
| 3 | pine | Pineapple | en |
| 3 | pine | Ananas | nl |

Now, I want to order the results by name, this would be the result:

``` sql
SELECT * FROM item JOIN translations ORDER BY name;
```

| Id | Code | Name | Locale |
| --- | --- | --- | --- |
| 3 | pine | Ananas | nl |
| 1 | cucu | Cucumber | en |
| 1 | cucu | Komkommer | nl |
| 3 | pine | Pineapple | en |
| 2 | toma | Tomaat | nl |
| 2 | toma | Tomato | en |

From the SQL point-of-view, this is correct. The sorting is applied on the name column as asked. From a users perspective, it's not really as expected and one would have to add the locale:

``` sql
SELECT * FROM item JOIN translations ORDER BY locale, name;
```

| Id | Code | Name | Locale |
| --- | --- | --- | --- |
| 1 | cucu | Cucumber | en |
| 3 | pine | Pineapple | en |
| 2 | toma | Tomato | en |
| 3 | pine | Ananas | nl |
| 1 | cucu | Komkommer | nl |
| 2 | toma | Tomaat | nl |

This, is also correct.

But, I have this interface as webpage, default 'nl' translations are shown, but the other 'en' can be shown when clicking on the 'en' link in the first column:

| Translations | ID | Code | Name |
| --- | --- | --- | --- |
| en nl | 1 | cucu | Komkommer |
| en nl | 2 | toma | Tomaat |
| en nl | 3 | pine | Ananas |

Clicking on ID, Code or Name, will order that column. For the columns ID and Code, it's working as expected (those columns arent translated). When clicking on the Name column, I expect the sorting the take the current locale into account. So, when the overall locale for the website is 'English / en', the sorting must be done first on English. If the overall locale is set to 'Dutch / nl', then the shown order must apply to the 'nl' locale:

Eg. Sorted on Name ascending when Dutch is shown:

| Translations | ID | Code | Name |
| --- | --- | --- | --- |
| en nl | 3 | pine | Ananas |
| en nl | 1 | cucu | Komkommer |
| en nl | 2 | toma | Tomaat |

Sorted on Name ascending when English is shown:

| Translations | ID | Code | Name |
| --- | --- | --- | --- |
| en nl | 1 | cucu | Cucumber |
| en nl | 3 | pine | Pineappel |
| en nl | 2 | toma | Tomato |

How could I achieve this with a QueryBuilder? 

NB I'm using the https://github.com/KnpLabs/KnpPaginatorBundle to sort.

**Comment by fkrauthan** [comment]
I was wondering if you guys have a suggestion for that too. Or do I need to manual read the current locale and fallback locale and create a join with the condition? Or is there a easier way?

**Comment by Mondane** [comment]
While re-reading my post a possible solution came to me.  A realtime determined column could be added to the querybuilder like:

```
IF(locale = currently displayed locale; 1; 0) AS 'currentdisplaylocale' 
```

Then, the ordering could be like:

```
ORDER BY currentdisplaylocale DESC,  name
```

Is this something that could be added?

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
