### ISSUE TITLE
[Tree] Use text for paths rather than ID

### ISSUE THREAD

**Issue by aranw** [KnpLabs/DoctrineBehaviors#209]
Is it at all possible to use name for the paths rather than the ID column? 

I still need UUID's along with my paths but currently the way the Tree trait seems to work it forces you to use ID field. 

This looks horrible when dealing with UUID's are nested tree structures.

```
/bfd6663b-cb7a-47f0-1aa2-87cda7299f97/1ad6663b-cb7a-47f0-1aa2-87cda7299f97/
```

**Comment by docteurklein** [comment]
you can modify this behavior by overriding the getNodeId method.

**Comment by aranw** [comment]
@docteurklein I ended up figuring this out but as I mention in #210 I found that the composer version is different to the version on GitHub.

**Comment by aranw** [comment]
@docteurklein thanks for pushing v1.1.0 thats now working perfectly.
