### ISSUE TITLE
setCreatedBy(fixture reference) does not work ?

### ISSUE THREAD

**Issue by sebastienvermeille** [KnpLabs/DoctrineBehaviors#213]
Hello guys,
first of all great job with this bundle I use it in all my projects.

I have a small problem with my doctrine:fixture.

I try to create some fake entities (for testing purpose). This works but when I try to assign a user as the creator it just save a string with the username of the user.

Here is how I did :

$myObject = new Object(); // Entity that use Blamable
$myObject->setCreatedBy($this->getReference('admin-user'));

but when it is persisted -> in created_at column in phpmyadmin I can see : "admin" that is the admin-user username. It should be the id... is there a way to solve it ?

Thank you in advance

**Comment by docteurklein** [comment]
hey :)
Did you configure it like described here: https://github.com/KnpLabs/DoctrineBehaviors#blameable ?

You need to explicitly define the relation by adding:
```
parameters:
    knp.doctrine_behaviors.blameable_subscriber.user_entity: AppBundle\Entity\User
    
```
in your config.

**Comment by sebastienvermeille** [comment]
@docteurklein you saved my day ! with the parameter it works perfectly

Thank you very much !

**Comment by docteurklein** [comment]
my pleasure :)
