### ISSUE TITLE
No more ORM mapping annotations since 

### ISSUE THREAD

**Issue by ypereirareis** [KnpLabs/DoctrineBehaviors#218]
Hi !

In tag v1.0.2, ORM mapping annotations are defined in `traits` like `TimestampableProperties.php` : 

```php
trait TimestampableProperties
{
    /**
     * @var \DateTime $createdAt
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $createdAt;
    /**
     * @var \DateTime $updatedAt
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $updatedAt;
}
```

But no more annotations in tag v1.0.3 : 
```php
trait TimestampableProperties
{
    protected $createdAt;
    protected $updatedAt;
}
```

Don't you think that's kind of a BC break ?

**Comment by akovalyov** [comment]
@ypereirareis it is loaded in the subscriber metadata, example - https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Timestampable/TimestampableSubscriber.php#L38-L62

**Comment by akovalyov** [comment]
Same as https://github.com/KnpLabs/DoctrineBehaviors/issues/195

**Comment by bocharsky-bw** [comment]
@akovalyov May bad! I forgot to import `orm-services.yml`. Thanks!
