### ISSUE TITLE
[Sortable] Sortable functionnality is not in the doc main page

### ISSUE THREAD

**Issue by sebastienvermeille** [KnpLabs/DoctrineBehaviors#222]
Hello ! Again thank's for this awesome bundle ! It saved my days in a huge amount of projects.

I just discovered the "sortable" functionnality (and of course... I developped mine because didn't saw).

I think it could be a good thing if you add it on the doc page too.

**Comment by docteurklein** [comment]
we removed it from the docs because we didn't really liked the implementation, but we could add it back indeed.

**Comment by ebuildy** [comment]
Yes please!

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
