### ISSUE TITLE
Translatable __call and segmentation fault

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#227]
Hi,
I'm using Translatable and a custom __call method :
```
public function __call($method, $arguments)
{
	try {
		return $this->proxyCurrentLocaleTranslation($method, $arguments);
	} catch (\Symfony\Component\Debug\Exception\ContextErrorException $e) {
		return $this->proxyCurrentLocaleTranslation('get' . ucfirst($method), $arguments);
	}
}
```

when in twig i call an inexistante method, it triggered a segmentation fault (11) in apache error.log

```
{{ product.getzzPhotos() }}
# display a blank page, and add a segmentation fault (11) in apache error.log
```

any idea to solve that ?

**Comment by docteurklein** [comment]
segfault are probably due to php iself. Try with a different version of php.

**Comment by akovalyov** [comment]
@CharlyPoppins probably https://bugs.php.net/bug.php?id=69427 could help. 
Do you have any news about this issue?

**Comment by CharlyPoppins** [comment]
Hi, no I just waiting apt-get update / upgrade to upgrade my version of php...
I'll probably have to find how to do it manually, the bug in your link has been fixed, but I don't know how to get this revision.

**Comment by akovalyov** [comment]
@CharlyPoppins you can try to use ```phpenv``` or ```docker``` to reproduce the bug with latest versions of php.

**Comment by akovalyov** [comment]
@CharlyPoppins do you have any news about it?

**Comment by CharlyPoppins** [comment]
Hi, sry for late response.
I'm not confortable with server administration...
Someone is going to help me on the server, and I'll come back

**Comment by CharlyPoppins** [comment]
Hi, I still have the problem, working on it.
Now my version is PHP 5.6.13-1~dotdeb+7.1 (cli) (built: Sep  4 2015 17:30:11).
And find in log : 
```
> Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal 11, Segmentation fault.
#0  zend_resolve_non_class_name (element_name=0x30, check_namespace=0x7ffd87128050 "\001", case_sensitive=0 '\000', 
    current_import_sub=<optimized out>) at /usr/src/builddir/Zend/zend_compile.c:2165
2165 /usr/src/builddir/Zend/zend_compile.c: Aucun fichier ou dossier de ce type.
```

**Comment by CharlyPoppins** [comment]
Didn't manage to solve this issue but I found a way to bypass it :
´´´
public function __call($method, $arguments)
	{
		try {
			
			if (method_exists(self::getTranslationEntityClass(), $method)) {
	            return $this->proxyCurrentLocaleTranslation($method, $arguments);
	        }
	        
	        $getMethod = 'get'. ucfirst($method);
	        if (method_exists(self::getTranslationEntityClass(), $getMethod)) {
	            return $this->proxyCurrentLocaleTranslation($getMethod, $arguments);
	        }
	        
	        return "*** DOES NOT EXIST : " . $method . " / " . $getMethod . " ***";
		} catch (\Symfony\Component\Debug\Exception\ContextErrorException $e) {
			return "null";
		} catch (\Exception $e) {
			return "null";
		}	
	}
´´´
