### ISSUE TITLE
ClassNotFoundException : DoctrineBehaviorsBundle() 

### ISSUE THREAD

**Issue by sebastienvermeille** [KnpLabs/DoctrineBehaviors#230]
Hello guys,
I just installed this great bundle on symfony 2.7 and It seems there is something wrong in the documentation : https://github.com/KnpLabs/DoctrineBehaviors#subscribers

When I add this line : new Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle() in AppKernel it does not work :

ClassNotFoundException in AppKernel.php line 22:
Attempted to load class "DoctrineBehaviorsBundle" from namespace "Knp\DoctrineBehaviors".
Did you forget a "use" statement for another namespace?

Do you have a fix for that ? Should I use the deprecated way -> import an .yml ?

Thank you in advance for your answer.

**Comment by docteurklein** [comment]
Mmmh I'm not sure of the reason. It might be an autoload problem. (we maybe made a typo in the compser.json config).

Can you verify your autolad generated files?

**Comment by docteurklein** [comment]
OH, from your message, I can see a possible problem:

you try to load `Knp\DoctrineBehaviors\DoctrineBehaviorsBundle` when it should be:
`Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle`.

**Comment by JulienItard** [comment]
I have the same problem with new Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle()

**Comment by akovalyov** [comment]
@docteurklein I have a feeling that @JulienItard and @sebastienvermeille are trying to follow the README and they are doing everything correctly, but we do not have the release for the version with bundle support.

**Comment by akovalyov** [comment]
@docteurklein I have just retested with ```dev-master``` version, indeed we have screwed up.

**Comment by akovalyov** [comment]
https://github.com/KnpLabs/DoctrineBehaviors/issues/229 has the same root.

**Comment by docteurklein** [comment]
ok so the reason is simple: you follow the docs for version dev-master, but you installed latest stable (which has no bundle yet). Closing.
