### ISSUE TITLE
[Sluggable] How could I generate unique slug with sluggable Trait?

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/DoctrineBehaviors#234]
I try to use Symfony Validator Callbacks to check whether slug is unique manually and add violation if not, but this unsuccessful finished because validators triggered before slug was generated. Any suggestions?

**Comment by akovalyov** [comment]
@bocharsky-bw could you provide a little bit more info(code I mean) about what are you trying to achieve?

**Comment by bocharsky-bw** [comment]
@akovalyov Thank you for your response! In [docs](https://github.com/KnpLabs/DoctrineBehaviors#sluggable) I see **uniqueness is not guaranteed** and it's true. So let me simplify my question a bit:
How could I generate an unique slug with sluggable Trait?

**Comment by akovalyov** [comment]
what about something ike
```php
    public function getSluggableFields()
    {
        return ['id',  'name' ];
    }
```
in your entity?

**Comment by bocharsky-bw** [comment]
@akovalyov Yeah, it's a nice idea, in some projects it will be work, but what if I need slug without id in it. Could I get some behavior like:

```
some-entity-slug
some-entity-slug-1
some-entity-slug-2
// ... etc.
```

I need to add a counter at the end of the slug if such slug already used. How can I do it?

**Comment by akovalyov** [comment]
@bocharsky-bw I am not sure if you can do it with Sluggable and I am not sure that you *should* do it with Sluggable. You will need to interact with your DB and it should not be done on the Model level. 
I have another question. Why do you need a unique slug? You already have an id, which is unique.

**Comment by bocharsky-bw** [comment]
Well, in a business world we get some tasks that we must do as the customer wants. Also I think you know that many sites has an unique slug without ID in it )

I agree with you to do it with Sluggable is wrong idea. But maybe we should to create an event listener for it where we could interact with DB?

Anyway, a tool which will be solved such business task seems to be an useful, in my opinion.

**Comment by akovalyov** [comment]
Wait. If we are talking about business world and business tasks - I have never heard about the business task to be able to generate unique slug in DB. 
 If we are talking about business task for human-friendly URLs - that is not the task of Sluggable, because we do not care about the strategy for unique URLs. We only generate slugs.

**Comment by bocharsky-bw** [comment]
OK, what about business task for human-friendly URLs... OK, that is not the task of Sluggable directly. But we could add a tool to this repository which will solve this tasks (care about the strategy of unique URLs)! Why not? :)

**Comment by bocharsky-bw** [comment]
P.S. I don't see the big difference between your first and second sentences. Or maybe I don't understand you )

**Comment by docteurklein** [comment]
@bocharsky-bw that's a good question. maybe you should do it at form submission, and hope the current slug listener doesn't override this value.

**Comment by bocharsky-bw** [comment]
@docteurklein Thank you! I think I could use `priority` to prevent overriding

**Comment by DarekTw** [comment]
@akovalyov 
> return ['id', 'name'];

The problem is that it only works when editing, rather than adding content.
Whent content is new, id is empty :(

**Comment by danabrey** [comment]
@DarekTw This is what UUIDs are for. Generate a UUID for each entity on construct.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
