### ISSUE TITLE
Add new tag in order to use AppKernel config way

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/DoctrineBehaviors#235]
The latest stable tag `v1.1.0` not work with recommended configuration way via `AppKernel`, described in [Subscribers](https://github.com/KnpLabs/DoctrineBehaviors#subscribers) section.

Could we tagged this bundle with new `v1.1.1` to make it work?

**Comment by docteurklein** [comment]
yes, it's in the pipe, just didn't have time to do it.
