### ISSUE TITLE
Use interfaces instead of traits

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/DoctrineBehaviors#241]
With interfaces implementation code looks more clearer, readable and correct than with current trait implementation. Developers could easily override properties and methods with their customs. Also we get auto-completion by IDEs in code. More discusion was in PR https://github.com/KnpLabs/DoctrineBehaviors/pull/237 .

There are a list of traits that should be refactored with interfaces:
- [x] - tree (in https://github.com/KnpLabs/DoctrineBehaviors/pull/246)
- [x] - translatable (in #322)
- [x] - timestampable (in https://github.com/KnpLabs/DoctrineBehaviors/pull/242)
- [x] - softDeletable (in https://github.com/KnpLabs/DoctrineBehaviors/pull/248)
- [x] - blameable (in #323)
- [x] - loggable (in #324)
- [x] - geocodable (in #325)
- [x] - filterable
- [x] - sluggable (in https://github.com/KnpLabs/DoctrineBehaviors/pull/237)
- [x] - sortable (in https://github.com/KnpLabs/DoctrineBehaviors/pull/249)

**Comment by migmolrod** [comment]
Hum. Maybe (very probably) I'm missing something, but with that approach users would have to implement the very same methods over and over in each entity using the behavior, right?

The good thing about 'traits' is they are so 'DRY'... (Don't Repeat Yourself). Wouldn't we be losing that with interfaces?

I can't see anything obscure or incorrect about traits, at all. They are just tools and I think they fit very well in this case.
About the auto-completion, I think there are ways to help with that, using ```@property``` PHPDoc tag (never used it myself yet, but I've read about it somewhere I don't remember now)

**Comment by bocharsky-bw** [comment]
@migmolrod Well, look closely to this PRs and changes that I made in them. I don't propose to remove traits that are awesome for DRY. I only suggest to add interfaces to this behaviors and do some refactor for using them.

So we keep all traits and provide a much clearer arvhitecture with interfaces as I explain in https://github.com/KnpLabs/DoctrineBehaviors/pull/237#issuecomment-122708798 .

**Comment by migmolrod** [comment]
Ahhh. Sorry for the misconception then.

**Comment by bocharsky-bw** [comment]
@migmolrod no problem. Seems these PRs maintainers review a bit hang up.

**Comment by ruscon** [comment]
+1

**Comment by NiR-** [comment]
Also using interfaces rather than reflection on properties will prevent any conflict. :+1:

**Comment by akovalyov** [comment]
4 PR's are red except https://github.com/KnpLabs/DoctrineBehaviors/pull/249. 
@NiR- @docteurklein should we merge every pr once it is done or beta release per PR, feedback from community and then final release with all of those?

**Comment by lemoinem** [comment]
@NiR- @docteurklein, @bocharsky-bw, Hi there, It's been a while since anything happen on this PR or any related to it.

I happen have some free time on my hands and would be happy to see this going through. Could one of you work me through the current status and what should be the next steps? I'm looking forward looking on this!

**Comment by bocharsky-bw** [comment]
Hey @lemoinem , thanks for reminding me about it!

There're still some missing behaviors like translatable, loggable, etc. which should be refactored according to the interfaces. I think you could pick one of them for implementing. Just let us know on what behavior you're working.

I'll take a look on my hung PRs soon when I have a time.

**Comment by lemoinem** [comment]
@bocharsky-bw Translatable #322 ;)

**Comment by lemoinem** [comment]
@bocharsky-bw
Blameable: #323 
Loggable: #324 
;)

**Comment by bocharsky-bw** [comment]
@lemoinem Wow, great! The only 2 left... or have I missed some behaviors in my TODO list?

**Comment by lemoinem** [comment]
@bocharsky-bw I don't think you missed anything. But I was thinking of going over everything just to be sure once I'm done.

I think we will also need to have a final PR to globally update the documentation with the basic principle.

**Comment by lemoinem** [comment]
@bocharsky-bw #325 for Geocodable.

As far as I can see, there will be no need to rewrite Filterable since it providing a single trait for the Repository. It looks like an Interface would be superfluous in that case.

**Comment by lemoinem** [comment]
@bocharsky-bw Ok, I think the PRs are done. I went through the other PRs, to make sure we don't hit #317 later on. I appreciate greatly the fact that the code base is becoming more consistent (Interface is much better for type-hinting and such, split traits all the time, easier to separate and improve)... I really like this!

**Comment by W0rma** [comment]
Any chance to get this PRs merged?

**Comment by ibasaw** [comment]
news ?

**Comment by TomasVotruba** [comment]
This look like something to be implemented :)

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/KnpLabs/DoctrineBehaviors/pull/442
