### ISSUE TITLE
[Translatable] Document required %locale% parameter (and maybe change its name to something more specific?)

### ISSUE THREAD

**Issue by asprega** [KnpLabs/DoctrineBehaviors#245]
In orm-services.yml, line 59, there's a reference to a %locale% parameter that is not documented anywhere. That seems to have been introduced in this commit: https://github.com/KnpLabs/DoctrineBehaviors/commit/c4fe668be50c5fe5e64ca888004bec5bc34bbde6

This forces any application which uses your bundle to declare that parameter. That is not documented anywhere though, and in my opinion it should have a more specific name, maybe namespaced like service names, to indicate that it's needed by the Knp Doctrine behaviors bundle.

Question for the maintainers: do you agree with this change? If so, I can prepare a pull request.

Are you following semver? If so, you should be more careful as this kind of issues should not happen when going from 1.0.\* to 1.1.\* (backward compatibility should be guaranteed).

**Comment by Einenlum** [comment]
Sorry for the very late answer @asprega. If you still want to do a PR about it, it would be welcome.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
