### ISSUE TITLE
Rename release tag 1.1.1 with "v" prefix

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/DoctrineBehaviors#247]
Could we rename release tag `1.1.1` to `v1.1.1` to be consistent with other tags?
I think we could remove `1.1.1` and add `v1.1.1` instead without BC break, doesn't it?

**Comment by docteurklein** [comment]
I think we should keep with just numbers and remove the v.
i know it's uncool to break consistency, but as of now, I think we'll stick with numbers only
