### ISSUE TITLE
[Translatable] Calling method mergeNewTranslations on inserting new translations

### ISSUE THREAD

**Issue by TomasPilar** [KnpLabs/DoctrineBehaviors#255]
Hi,

when i need update my entity translations calling method mergeNewTranslations is not required and everything is stored in database. I must call method mergeNewTranslations when i need insert new translations into database. I think that calling this method should ensure a subscriber.

Is this standard behaviour or bug? 

Thanks

**Comment by shieldo** [comment]
It is the documented behaviour.  I don't know whether making a call like this explicitly could be avoided easily using behaviour in a subscriber that detects new translations.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
