### ISSUE TITLE
[Loggable] Logging many-to-many relation changes

### ISSUE THREAD

**Issue by daniel-adlantic** [KnpLabs/DoctrineBehaviors#258]
Hi,

I've been trying the `Loggable` functionality, so far it seem to be working except that many to many changes are not reflected correctly.

When removing a relation, `getUpdateLogMessage(array $changeSets = [])` is not triggered. When adding a relation  `getUpdateLogMessage(array $changeSets = [])` is triggered with an empty array in `$changeSets`.

I am very new to this project so I might have missed something.

**Comment by docteurklein** [comment]
I think associations are not handled, only scalar properties.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
