### ISSUE TITLE
[Translatable] Error during flush - Warning: spl_object_hash() expects parameter 1 to be object, null given

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#259]
Hi,
I'm trying to remove a translation when some fields are null, then I have this error : "Warning:  spl_object_hash() expects parameter 1 to be object, null given".
Am I doing it the right way ? 

```
/**
 * @ORM\PreUpdate()
 * @ORM\PrePersist()
 */
public function checkAlt()
{
    if( $this->getAlt() == null && $this->getLabel() == null ) {
        $this->getTranslatable()->removeTranslation($this);
    }
}
```

edit: maybe there a probleme with a required locale ? I'm using a2lix translation bundle too.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
