### ISSUE TITLE
[Translatable] I can not get all translations of an entity, why?

### ISSUE THREAD

**Issue by davidvalero** [KnpLabs/DoctrineBehaviors#260]
Hi, I have multiple entities using Translatable behaviour, but in some cases, I can not get all translations.
For example:

``` php
if($category->getId() == 61) {
    echo "ES => ".$category->translate('es')->getName()."<br>"; //ES => PROMOCIONALES<br>
    echo "EN => ".$category->translate('en')->getName()."<br>"; //EN => <br>
    echo "FR => ".$category->translate('fr')->getName()."<br>"; //FR => <br>
}
```

But the category with id 61, has the next entries on the translations table:
![Image of test](http://i.stack.imgur.com/7ELec.jpg)

Any idea? Thank you in advance!

**Comment by xmon** [comment]
The same here

**Comment by docteurklein** [comment]
that definitley looks like a bug. Could you dump the sql query responsible for that?

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
