### ISSUE TITLE
[Blameable/Timestampable/Translatable] Only works when creating new objects

### ISSUE THREAD

**Issue by Mondane** [KnpLabs/DoctrineBehaviors#263]
I have an entity with the blameable, timestampable and the translatable behaviors. When I create a new object, in the database, the fields 'created_by', 'updated_by', 'created_at' and 'updated_at' are set properly. But when I change the translated fields, the 'updated_by' and 'updated_at' aren't changed.

How can I make sure this works?

**Comment by calumbrodie** [comment]
/src/ORM/Timestampable/TimestampableSubscriber.php

This is the class which executes whenever your entity is loaded (loadClassMetadata), and carries out the timestampable behaviour. Have you enabled the subscribers?

https://github.com/KnpLabs/DoctrineBehaviors#subscribers

**Comment by Mondane** [comment]
As it turned out, I didn't have the subscribers enabled. But I must say, after enabling them (and clearing the cache), the problem stays the same. the updated_by and updated_at fields in the main entity are not adjusted when editing translatable properties. 

This is in my entity:

```
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * NourishmentType
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Vaarties\DwehBundle\Entity\TranslatableRepository")
 */
class NourishmentType
{
    use ORMBehaviors\Blameable\Blameable;
    use ORMBehaviors\Timestampable\Timestampable;
    use ORMBehaviors\Translatable\Translatable;
```

What's the easiest way to check if I've forgotten something else?

**Comment by Mondane** [comment]
I've now tested it with a proper configuration using the new method for registering the services. This made no change in the behavior.

**Comment by TomasVotruba** [comment]
Any idea how to fix this? Adding an event?

**Comment by TomasVotruba** [comment]
Missing test case is needed.
