### ISSUE TITLE
[Translatable] DBAL error with PostgreSQL schemas and translations: Invalid index-name

### ISSUE THREAD

**Issue by migmolrod** [KnpLabs/DoctrineBehaviors#264]
Steps to reproduce it:
- Use pdo_pgsql database driver.
- Create a new translatable entity with table name = schema1.table1
- Create a new translation entity with table name = schema1.table1_translation
- Try `php app/console doctrine:schema:update --dump-sql` (or any command that check Doctrine mapping)

You get an error like:

```
[Doctrine\DBAL\Schema\SchemaException]                                                     
  Invalid index-name schema1.table1_translation_unique_translation given,
  has to be [a-zA-Z0-9_]
```

A possible fix: make the method (that generates the '_translation_unique_translation' key name) to strip dots, convert them to underscores or something similar.
From a quick look, I'd say it has something to do with https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php

Just for those that don't know, in PostgreSQL schemas are like 'folders' to separate your tables into categories, sort of. The notation to create a table inside a given schema is to use "schema_name.table_name" as table name.

**Comment by docteurklein** [comment]
ha, so it seems we don't strip the schema name from the index key. if you could provide a fix for that, it would be awesome!

thanks for pointing this out.

**Comment by migmolrod** [comment]
Yeah. I think in Doctrine 2.5 we will be able to use ```@Table(name="table1", schema="schema1")```.

Now, about the fix I was thinking about it. Do I hardcode a string replace (dots for underscores) in TranslatableSubscriber? Or there is some method in Doctrine to generate index names that we could use to not reinvent the wheel? Something about the naming strategy or... I don't know.

I took a deeper look at TranslatableSubscriber and I think that there could be an issue with id sequence names as well, not sure.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
