### ISSUE TITLE
Commit a52a92a disables all subscribers

### ISSUE THREAD

**Issue by tamcy** [KnpLabs/DoctrineBehaviors#267]
According to the updated documentation, commit a52a92a intended to make all configurations enabled by default when the root node `knp_doctrine_behaviors` is empty. However, when tested on Symfony 2.7.6, the actual behavior is that all behaviors are disabled by default. Looks like the `treatNullLike([... => true ])` in `Configuration` class has no effect. Can anyone verify this behavior? Thanks.

**Comment by docteurklein** [comment]
ping @NiR-

**Comment by Mondane** [comment]
Mm, this might actually be true as I've just tried to convert the deprecated method to the new one in my project. After the conversion, nothing worked anymore. See #263 and #272 .

**Comment by NiR-** [comment]
Thanks @Mondane & @tamcy for the report. I've pushed a fix for this BC break. It will be merged soon.
