### ISSUE TITLE
Translatable with JMS serializer

### ISSUE THREAD

**Issue by btribouillet** [KnpLabs/DoctrineBehaviors#268]
Hi, 

I'm not sure if it is an issue or a misconfiguration of JMS serializer, i'd like to know if anyone knows if it ever worked with JMS Serializer, otherwise the issue is described below.

I'm building a restful api with fos rest bundle and JMS serializer.
I want to be able to only return fields of a specific group.

**For the example here, the field classIcon is not returned** 

Service Controller :

     /**
       * Get the services
       *
       * @Get("/services")
       *
       * @ApiDoc(
       *   resource = true,
       *   description = "Get the services",
       *   output = "SE\ApiBundle\Entity\Service",
       *   statusCodes = {
       *     200 = "Returned when successful",
       *   }
       * )
       *
       * @Annotations\View(
       *      serializerGroups={"service"},
       *      serializerEnableMaxDepthChecks=true
       *  )
       *
       * @return array
       *
       * @throws AccessDeniedHttpException when user is not logged in
       */
       public function getServicesAction(Request $request)
       {

           $service  = $this->container->get('doctrine')
                ->getManager('default')
                ->getRepository('ApiBundle:Service');

           return $service->findAll();

      }

Service Entity :

    /**
     * @ORM\Entity
     * @ORM\Table(name="service")
     */
    class Service
    {

        use ORMBehaviors\Translatable\Translatable;

        /**
         * @ORM\Id
         * @ORM\Column(type="integer")
         * @ORM\GeneratedValue(strategy="AUTO")
         * @JMSSerializer\Groups({"service"})
         */
        private $id;

        /**
         * @ORM\Column(type="string", length=32)
         * @JMSSerializer\Groups({"service"})
         */
        private $slug;

        /**
         * @ORM\Column(type="string", length=64, name="class_icon")
         */
         private $classIcon;

    }

ServiceTranslation Entity :

    /**
     * @ORM\Entity
     * @ORM\Table(name="service_translations")
     */
    class ServiceTranslation
    {

        use ORMBehaviors\Translatable\Translation;

        /**
         * @ORM\Column(type="string", length=32)
         * @JMSSerializer\Groups({"service"})
         */
         protected $name;

    }

Would i be able to do that, otherwise what would be the solution? 

For your information i need to return only the required language (and of course if not exists the default one). FindByLocale doesn't seem to do the job i was looking for, so i did some DQL. I have the **same issue if i return the full entity (SELECT s instead of s.name, s.slug etc.)** .

This is the way i've done it for now, but it would be great if it could work with JMSSerializer.

    // Get language (default : en)
    $lg = $request->query->get('lg', 'en');

    return $this->container->get('doctrine')->getManager('default')
        ->createQuery(
                "SELECT s.id as id, s.slug as slug, t.name as name, s.classIcon as class_icon
                FROM ApiBundle:Service s
                INNER JOIN ApiBundle:ServiceTranslation t
                WITH s.id = t.translatable 
                WHERE 
                ( 
                    CASE
                        WHEN
                            (
                               SELECT count(t2)
                               FROM ApiBundle:ServiceTranslation t2
                               WHERE s.id = t2.translatable AND t2.locale = :lg
                            ) > 0
                        THEN :lg
                        ELSE 'en'
                    END
                ) = t.locale
                "
            )
        ->setParameter('lg', $lg)
        ->getResult();

It will return correctly :

    [
       {
        "id": 1,
        "slug": "service-one",
        "name": "Service one",
        "class_icon": "icon-eye"
      },
      {
        "id": 2,
        "slug": "service-two",
        "name": "Service  deux (fr)",
        "class_icon": "icon-camera"
      }
    ]

**Comment by lumilo8** [comment]
I have the same problem, Did you solve this issue with JMSSerializer @btribouillet ? Thanks!

**Comment by btribouillet** [comment]
@lumilo8 I didn't solve it by only using JMSSerializer. The only way i found is with 2 type of queries. The first one is used if more than one field is translated.

The first one is similar to group by. You can maybe manage to do it fully in SQL but with doctrine query language this si the way i found. If you have any better solution, please let me know.

        // Get language (default : en)
        $lg = $request->query->get('lg', 'en');

        $bundles_tmp = $this->container->get('doctrine')->getManager('default')
            ->createQuery(
                    "SELECT b.id, b.price, t.name, t.description
                    FROM ApiBundle:Bundle b
                    INNER JOIN ApiBundle:BundleTranslation t
                    WITH b.id = t.translatable AND (t.locale = :lg OR t.locale = 'en')
                    WHERE b.user = :user
                    ORDER BY t.id"
                )
            ->setParameter('lg', $lg)
            ->setParameter('user', $user[0])
            ->getResult();

        // Mix required translations with default language (when null)

        $bundles = array();

        foreach($bundles_tmp as $bundle){

            if(!isset($bundle['id'])){
                $bundle['id'] = array();
            }

            $bundles['data'][$bundle['id']]['price'] = $bundle['price'];

            if(!is_null($bundle['name'])){
                $bundles['data'][$bundle['id']]['name'] = $bundle['name'];
            }

            if(!is_null($bundle['description'])){
                $bundles['data'][$bundle['id']]['description'] = $bundle['description'];
            }

        }

Second one (if only one translated field) :

    // Get language (default : en)
    $lg = $request->query->get('lg', 'en');

    return $this->container->get('doctrine')->getManager('default')
    ->createQuery(
            "SELECT s.id as id, s.slug as slug, t.name as name, s.classIcon as class_icon
            FROM ApiBundle:Service s
            INNER JOIN ApiBundle:ServiceTranslation t
            WITH s.id = t.translatable 
            WHERE 
            ( 
                CASE
                    WHEN
                        (
                           SELECT count(t2)
                           FROM ApiBundle:ServiceTranslation t2
                           WHERE s.id = t2.translatable AND t2.locale = :lg
                        ) > 0
                    THEN :lg
                    ELSE 'en'
                END
            ) = t.locale
            "
        )
    ->setParameter('lg', $lg)
    ->getResult();

**Comment by docteurklein** [comment]
It seems to me that you are querying partial results ?
Wouldn't doctrine return an array for:

    SELECT s.id as id, s.slug as slug, t.name as name, s.classIcon as class_icon
    FROM ApiBundle:Service s

Shouldn't you simply use:

    Select s FROM ApiBundle:Service s

?

**Comment by btribouillet** [comment]
The problem by doing this is that it will return all the languages and not only the required language. If you don't mind about doing this logic on the client side.
 
    Select s FROM ApiBundle:Service s

would do it.

**Comment by docteurklein** [comment]
you will need to join the translations and filter them based on the current locale indeed.

But using partial resultset is not a choice if you want to use jms serializer IMHO.

**Comment by btribouillet** [comment]
Yes you are right, indeed JMSSerializer is not used with that solution.

I guess this is not an issue anymore.

**Comment by yegorLitvinov** [comment]
You can use JMS VirtualProperty annotation:

    /**
     * @JMS\VirtualProperty
     */
    public function getTitleOffer()
    {
        return $this->translate()->getTitleOffer();
    }
