### ISSUE TITLE
How to use Translatable with a pre-existing entity

### ISSUE THREAD

**Issue by picks44** [KnpLabs/DoctrineBehaviors#269]
Hi,

I'm trying to use the bundle for its Translatable function. I had a Catagory entity with id/name/slug that I managed to transform following the bundle doc.
I've updated the database.
But now, when i'm trying to crete or list the Category records, I get some erros messages like 
```
Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "My\AppBundle\Entity\ArticleCategory".
```
And the doc doesn't explain at all how to deal with forms, etc...

Can someone tell me a bit more on how this bundle works ?

**Comment by docteurklein** [comment]
It seems that's a form specific problem.

Entities using behavior traits are handled the exact same way than a normal entity.
You need to follow http://symfony.com/doc/current/book/forms.html#building-the-form
