### ISSUE TITLE
Error: ...no extension able to load the configuration for "knp_doctrine_behaviors"

### ISSUE THREAD

**Issue by rrakibul** [KnpLabs/DoctrineBehaviors#270]
Following error occurs when use "knp_doctrine_behaviors" in config.yml file. 

...no extension able to load the configuration for "knp_doctrine_behaviors" ...

error resolves with "doctrine_behaviors".

**Comment by krombox** [comment]
the same. Symfony 2.6.3. strange earlier work well

**Comment by docteurklein** [comment]
did you register the bundle accordingly?

**Comment by krombox** [comment]
Now all is ok. I have updated doctrine/orm
