### ISSUE TITLE
[Timestampable] makeTimestampable work with FPN\TagBundle

### ISSUE THREAD

**Issue by Hanmac** [KnpLabs/DoctrineBehaviors#271]
if i try to use both i got the following message:

```
Runtime Notice: DoctrineExtensions\Taggable\Entity\Tag and Knp\DoctrineBehaviors\Model\Timestampable\Timestampable define the same property ($createdAt) 
```

i get it work with only using TimestampableMethods, and not the Timestampable trait, but i don't think it would still have using the callbacks for setting the properties.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
