### ISSUE TITLE
Deprecated way: Importing a service definition file (not deprecated anymore?)

### ISSUE THREAD

**Issue by michaeldk** [KnpLabs/DoctrineBehaviors#272]
Hello :)

I've been using DoctrineBehaviors for almost a year now without much problems.
But last night I encountered a new error (new to me ofc) and couldn't find anything online about it.

When I try to update my database schema with doctrine's `doctrine:schema:update -f` I get the following error:

    [Doctrine\ORM\Mapping\MappingException]                                                                                                     
    No identifier/primary key specified for Entity "AppBundle\Entity\AppVersionTranslation". Every Entity must have an identifier/primary key.

This project is in its 3rd iteration and had over 60k uses on both previous iterations without any issues.
I've verified my code to make sure I didn't add anything to my entities and I'm 100% sure it's not coming from there.

If I add an id to my *Translation entity it fails telling me both my entity and the Translation Trait use the same attribute `id`. I tried removing the id attribute from the Translation Trait and it works that way too (well, at least doctrine:schema:update doesn't fail that way).

I updated my project to SF 2.7.7 (even though I have no clue if this is linked) and FOSUserBundle (hence the database schema update needed). 
When I add the deprecated `orm-services.yml` import it works:

    # app/config/config.yml
    imports:
        - { resource: ../../vendor/knplabs/doctrine-behaviors/config/orm-services.yml }

Can you guys tell me where I should look to see what could cause the sudden need for the import to be used ?

Thanks!

**Comment by docteurklein** [comment]
hi! sorry for that, I think it is related to a recent commit: https://github.com/KnpLabs/DoctrineBehaviors/commit/3a916a548c19ea6bf29c1d5c86b1dabe7074700e

but it is not yet part of a stable release, only in master.

So if you are using the latest release, then including orm-services.yml is still the official way to do it.

**Comment by Mondane** [comment]
@docteurklein If I'm correct, release 1.3.0 should have the new method in it. If that's correct, do you have any idea why I got this error after changing the deprecated method to the new method:

> request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 84 near 't': Error: Class Vaarties\DwehBundle\Entity\Nourishment has no association named translations" at /var/www/sites/dweh/site/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63 {"exception":"[object] (Doctrine\\ORM\\Query\\QueryException(code: 0): [Semantical Error] line 0, col 84 near 't': Error: Class Vaarties\\DwehBundle\\Entity\\Nourishment has no association named translations at /var/www/sites/dweh/site/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:63, Doctrine\\ORM\\Query\\QueryException(code: 0): SELECT e, t FROM Vaarties\\DwehBundle\\Entity\\Nourishment e INNER JOIN e.translations t at /var/www/sites/dweh/site/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:41)"} []
