### ISSUE TITLE
[Tree] Is there something broken with the tree?

### ISSUE THREAD

**Issue by tknuppe** [KnpLabs/DoctrineBehaviors#273]
Hi

I would like to start using the tree behaviour but I think there is something not right ATM.

In the repository, root entries have an empty materialized path:

<pre><code>
    public function getRootNodesQB($rootAlias = 't')
    {
        return $this->createQueryBuilder($rootAlias)
            ->andWhere($rootAlias.'.materializedPath = :empty')
            ->setParameter('empty', '')
        ;
    }
</code></pre>

In the Node, the root node has the separator:

<pre><code>
    public function isRootNode()
    {
        return self::getMaterializedPathSeparator() === $this->getParentMaterializedPath();
    }
</code></pre>

What is right and how does this all work?

Also, when I fetch a Node and asks it to getParentNode(), it always returns null.

Maybe I got something wrong but at least the first example ( root == '' and root == '/') seems to be completely broken. Can you please look at it?

Greetings
Thomas

**Comment by docteurklein** [comment]
hi!

It's definitely possible something is wrong with path comparison. I have however not planned to look at this problem, until I have the need to.

If you can provide a fix for that, it would be awesome!

Concerning:
> Also, when I fetch a Node and asks it to getParentNode(), it always returns null.

you have to build the tree first. Fetching a node by itself won't populate the parent and children until you pass by the `buildTree` method.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
