### ISSUE TITLE
[Translatable/Slugable] defaultlocale ?

### ISSUE THREAD

**Issue by CharlyPoppins** [KnpLabs/DoctrineBehaviors#277]
Hi,

I'm working on a Command that create entities from a csv,
I've got an exception during the flush.

```
//$annonce->setDefaultLocale('fr'); // I tried with and without
$annonce->translate('fr')->setTitre("blablatitre");
$annonce->translate('fr')->setTexte("blablatexte");
$em->persist($annonce);
$annonce->mergeNewTranslations();
$em->flush();
```

and I've got this exception

```
string(21) "AnnonceTranslation fr"
string(21) "AnnonceTranslation en"
"UnexpectedValueException"
"Sluggable expects to have at least one usable (non-empty) field from the following: [ 0 ]"
```

as you can see I set only **fr** then **en** is still "triggered" in **DoctrineBehaviors/src/Model/Sluggable/SluggableMethods.php generateSlugValue($values)**

```
class AnnonceTranslation
{
    ORMBehaviors\Sluggable\Sluggable,
    ORMBehaviors\SoftDeletable\SoftDeletable,
    ORMBehaviors\Translatable\Translation;

    public function getSluggableFields()
    {
        var_dump("AnnonceTranslation " . $this->getLocale());
        return [ 'titre' ];
    }
}

am I doing something wrong ?
```

**Comment by CharlyPoppins** [comment]
I update my code to prevent the exception, but I haven't found out why this is happening.

```
$annonce->translate('fr')->setTitre("blablatitre");
$annonce->translate('fr')->setTexte("blablatexte");
$em->persist($annonce);
$annonce->mergeNewTranslations();

foreach($annonce->getTranslations() as $t) {
	if($t->getTitre() === null) {
		$annonce->removeTranslation($t);
	}
}

$em->flush();
```

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
