### ISSUE TITLE
[Translatable] Limit the length of locale column?

### ISSUE THREAD

**Issue by tamcy** [KnpLabs/DoctrineBehaviors#280]
Currently, `TranslatableSubscriber` doesn't specify the column length of the `locale` column, and its data type defaults to VARCHAR(255) in MySQL. However, the generated schema file won't work when `utf8mb4` is used as the database charset because 
1. `locale` is used as a key / unique index which is limited to 767 bytes, and 
2. `utf8mb4` charset uses 4 bytes for each character, so `varchar(255)` breaks the 767 bytes key length limit.

The key length limit can be lifted with extra configurations, which includes altering the `innodb_file_format`, `innodb_file_per_table` and finally `innodb_large_prefix` config values, which is not easy especially in a shared environment. And the problem I think is that whether the `locale` column really needs to take up to 255 characters to store the values. So I'd like to propose limiting it to a reasonable length (100? 50?).

**Comment by docteurklein** [comment]
see https://github.com/KnpLabs/DoctrineBehaviors/projects/1#card-310712

**Comment by giovkanata** [comment]
I had the same issue using the `utf8mb4` charset on string columns and to avoid the key lenght limit I temporary resolved mapping the `$locale` on each Translation class like this (I use annotation for mapping entities):
```
    /**
     * @var string
     *
     * @ORM\Column(
     *     type="string",
     *     length=190
     * )
     */
     protected $locale;
```

The max key lenght of an `utf8mb4` string is 190 chars instead of 255 that are automatically assigned by default.

**Comment by patie** [comment]
i also using utf8mb4 on some projects, any news here please?

**Comment by sudosu** [comment]
Same issue here. Any updates?

**Comment by TomasVotruba** [comment]
Replaced by https://github.com/KnpLabs/DoctrineBehaviors/pull/389
