### ISSUE TITLE
[BC Break] Translation stopped working after 1.2.0 -> 1.3.0 update on Doctrine 2.6

### ISSUE THREAD

**Issue by kiler129** [KnpLabs/DoctrineBehaviors#281]
Hi!
I think I maybe found a bug in the newest 1.3.0 release. I'm using `translatable` from `DoctrineBehaviors` along with [a2lix/translation-form-bundle](https://github.com/a2lix/TranslationFormBundle) & [Sonata](https://github.com/sonata-project/SonataAdminBundle).
After upgrade I noticed all translations are missing. To pinpoint that issue I downgraded Doctrine from 2.6.1 to 2.6.0 - result was the same. Next I've tried downgrading `DoctrineBehaviors` to 1.2.0, and bingo - everything started working.
I wrote minimal code to test it:
```php
$pageRepo = $this->getDoctrine()->getRepository('XyzBundle:Page');
$page = $pageRepo->find(1);
var_dump($page);
```
On 1.3.0 it returns nulls where on 1.2.0 proper vales are returned.

Here're my implementation details (simplified to single-field, no setters, no comments to save space):
**Mappings**
```xml
<?xml version="1.0" encoding="utf-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
    <entity name="FooCompany\XyzBundle\Entity\Page" table="pages">
        <id name="id" type="integer" column="id">
            <generator strategy="AUTO"/>
            <options>
                <option name="unsigned">true</option>
            </options>
        </id>
        <field name="userEditable" type="boolean" column="user_editable" nullable="false"/>
    </entity>
</doctrine-mapping>
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
    <entity name="FooCompany\XyzBundle\Entity\PageTranslation" table="page_translations">
        <field name="title" type="string" column="title" length="255" nullable="false"/>
    </entity>
</doctrine-mapping>
```

**Page entity**
```php
<?php

namespace FooCompany\XyzBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

class Page
{
    use ORMBehaviors\Translatable\Translatable;

    private $id;
    private $userEditable = false;

    public function getId()
    {
        return $this->id;
    }

    public function getTitle()
    {
        return $this->translate($this->getCurrentLocale())->getTitle();
    }

    public function getUserEditable()
    {
        return $this->userEditable;
    }

    public function __debugInfo()
    {
       return [
            'id' => $this->id,
            'title' => $this->getTitle(),
            'userEditable' => $this->userEditable
        ];
    }
}
```

**PageTranslation entity**
```php
<?php

namespace FooCompany\XyzBundle\Entity;

use Knp\DoctrineBehaviors\Model as ORMBehaviors;

class PageTranslation
{
    use ORMBehaviors\Translatable\Translation;

    private $title;

    public function getTitle()
    {
        return $this->title;
    }
```

That issue may be related to another problem I noticed after update. If I try to edit translated entity I'm getting `No identifier/primary key specified for Entity "Foo\XyzBundle\Entity\PageTranslation". Every Entity must have an identifier/primary key.`.
Despite my efforts I was unable to replicate that issue with few simple lines of code.

**Comment by docteurklein** [comment]
could you manually define the identifier in the translation class?

**Comment by kiler129** [comment]
Unfortunately it doesn't solve the problem - of course exception on form will disappear, but entity continues to contain only nulls.
I tried two approaches - mapping `id` field from trait and completely different field defined in translation class.

```xml
        <id name="id" type="integer" column="id">
            <generator strategy="AUTO"/>
            <options>
                <option name="unsigned">true</option>
            </options>
        </id>
``` 

```xml
        <id name="trId" type="integer" column="id">
            <generator strategy="AUTO"/>
            <options>
                <option name="unsigned">true</option>
            </options>
        </id>
```

**Comment by docteurklein** [comment]
ok. sorry for the problem. I'm not sure which commit introduced this regression, but if you have time to look at the diff between 1.2 and 1.3, that would be awesome.

**Comment by kiler129** [comment]
Yeah... adding
```yaml
knp_doctrine_behaviors:
  translatable: true
```
solved the problem - it was stupid :)

Don't you think, according to sem-ver, all values should be `true` by default in 1.3? Especially considering default version specification ~1.1 which will break many installations after update.
It's a very good thing to not enable everything in general, but it should be consistent with 1.2.

I propose to switch defaults to true and place a note in readme describing that all unused modules should be disabled and in 2.0 release flip all of them to default false.
What do you think?

**Comment by docteurklein** [comment]
you're totally right! this new configuration brings us a lot of problems, and it definitely breaks existing setups.

I'm not sure how to handle this tho.

**Comment by samjarrett** [comment]
Wanted to add a note that using Timestampable and SoftDeletable also were broken with this change.

**Comment by JulienItard** [comment]
Hello,

when i did doctrine:schema:update --force
i had the errror : 

  No identifier/primary key specified for Entity "AppBundle\Entity\AlertTranslation". Every Entity must have an identifier/primary key.  


Your solution fix it ! Thx
