### ISSUE TITLE
[Translatable] TranslationFormBundle has problems with translation fallback

### ISSUE THREAD

**Issue by Hanmac** [KnpLabs/DoctrineBehaviors#282]
hi i am using [a2lix/TranslationFormBundle](https://github.com/a2lix/TranslationFormBundle),
but it does not support the translation fallback that was added later in this bundle.

might there be a way to make it working?
my first test was a new class that does implements ArrayAccess which does work as a wrapper returned from getTranslations, but it didn't work as i wanted yet.

it might not be fixed in TranslationFormBundle because it does use a PropertyAccess String and my Symfony version doesnt support Callable at that place yet.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
