### ISSUE TITLE
Translation validator

### ISSUE THREAD

**Issue by nicolas-brousse** [KnpLabs/DoctrineBehaviors#283]
For a project I created a custom validator to allow applying constraints in function of locale value.
It's not specific to my project but generic to the translation behavior.

I would like to know if you are interested by a PR to add this into your project.

http://stackoverflow.com/questions/34877703/symfony2-conditionnal-form-validation/34905094#34905094

Cheers

**Comment by docteurklein** [comment]
sorry for such a long delay. We'd like to limit as much as possible the scope of this package, which is already hard to maintain. A separate package would be perfect for your contrib.
thanks :)

**Comment by nicolas-brousse** [comment]
@docteurklein no worries :)
thanks
