### ISSUE TITLE
[Translatable] translatable_fetch_method: 'EAGER' still doesn't work

### ISSUE THREAD

**Issue by Hanmac** [KnpLabs/DoctrineBehaviors#285]
I have a Vehicle class which does have a ManyToOne connection (lazy) to FuelType.
FuelType is a Translatable which is connected to FuelTypeTranslation (per translatable_fetch_method its 'EAGER')

but when i go to the side and wanted to output a Vehicle with its translated FuelType,
it still does do 2 queries for FuelType and one for FuelTypeTranslation.

Even if i do change the connection from Vehicle to FuelType into 'EAGER' too it still does make this two extra queries (even if it should has already the FuelType from the Vehicle Query), but it seems it doesn't work.

how can I do it that it does look for FuelType and its Translation in one Query? or is that a Doctrine bug?

**Comment by waitxd** [comment]
#261

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.

**Comment by MichaelBrauner** [comment]
First - Thank you for your efforts and this/these great bundle(s)! I completly love it. 

But I have  the same a problem like the opener of this issue ... 

I translated some `Entity\Page` - everything works just fine. 
BUT when I query the pages the eager loading do not work at all. 

I have in my `services.yaml`:

```yaml
parameters:
  app_locales: de|en
  locale: en
  doctrine_behaviors_translatable_fetch_mode: "EAGER"
  doctrine_behaviors_translation_fetch_mode: "EAGER"
```

But it makes absolute no difference in my queries. 

```sql
SELECT
  t0.id AS id_1,
  t0.title AS title_2,
  t0.locale AS locale_3,
  t0.translatable_id AS translatable_id_4
FROM
  page_translation t0
WHERE
  t0.translatable_id = ?
```

This query is a distinct query every time no matter what.

**Comment by TomasVotruba** [comment]
Thank you for appreciation :+1: 

I do not use this bundle much, so I don't have a clue. But I can make failing test pass :) could you share your use case in test case?

**Comment by MichaelBrauner** [comment]
Yes. I can try that. Give me some days.

**Comment by MichaelBrauner** [comment]
Ok. After digging - I see. 

In https://github.com/KnpLabs/DoctrineBehaviors/blob/c7c2831ae4e6b846fbdcffad1c2489652b3b4a0e/src/EventSubscriber/TranslatableEventSubscriber.php#L106 the fetch mode will be set. 

It uses the default or the given parameter by the current system. 

It's NOT something like an automatic join with a select to avoid additional queries. 

So I completely misunderstood that. 
It will just change IF the extra query should be done every time (EAGER), only if needed (LAZY), or only if a data query is triggered (EXTRA_LAZY). 

Then we can forget that ;).

**Comment by TomasVotruba** [comment]
I see. Thanks for exploring. Do you think we should update the docs to make that more clear to others?

**Comment by MichaelBrauner** [comment]
Yes. I can do that if you want.

**Comment by MichaelBrauner** [comment]
@TomasVotruba - You mentioned earlier that you don't use this bundle much. May I ask what you use for translations instead?

**Comment by TomasVotruba** [comment]
@MichaelBrauner I used this package in prevous project and it worked well. Just last 5 years I don't deal with translations at all. So I'd use this one, as the other had huge performnace issues.

**Comment by MichaelBrauner** [comment]
> @MichaelBrauner I used this package in prevous project and it worked well. Just last 5 years I don't deal with translations at all. So I'd use this one, as the other had huge performnace issues.

Yes, I read your blog post about it. That's what convinced me not to use StofDoctrineExtensions. thank you for that
