### ISSUE TITLE
Integrating into Zend Framework 2

### ISSUE THREAD

**Issue by danbroooks** [KnpLabs/DoctrineBehaviors#287]
Is there an easy way to integrate these behaviors into a ZF2 project? I'm currently going down the path of creating services/factories manually but this is soon going to become quite unwieldy.

Considering writing something that takes the settings in `config/orm-services.yml` and translates them into a configuration for Zend, would that be possible? Am I barking up the wrong tree?

**Comment by TomasVotruba** [comment]
The best way is to take service and intergrate them in framework's DI
