### ISSUE TITLE
[Translatable] add a `getCurrentTranslation` method (that aliases `translate`)

### ISSUE THREAD

**Issue by docteurklein** [KnpLabs/DoctrineBehaviors#29]
This way, we can use it directly in forms.

**Comment by Einenlum** [comment]
@docteurklein Not sure I get it. Why it would be useful to have it apart from `->translate()`, and how would it help about forms?

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
