### ISSUE TITLE
Some "bugs" in the readme.md

### ISSUE THREAD

**Issue by rthreis** [KnpLabs/DoctrineBehaviors#293]
Hello folks,
First of all, thank you for your work.
I got a tiny question about the readme.md file.  Is it possible an error slipped in ?
I thing I followed the instructions to use the Translatable extension, but something strange happened.
When trying to update my schema using the doctrine command line instructions, I get a message telling me No Identifier/primary key specified for the <entityName>Translation.  According to the readme.md file, no primary key is needed.  So, I thing to myself, perhaps an error in the readme.md file.
So, I add the id field in my <entityName>Translation entity, but then, an other error occurs.
Here's the message I get :

> [Symfony\Component\Debug\Exception\ContextErrorException]                                        
  Runtime Notice: Mdy\XlagendaBundle\Entity\EventTranslation and Knp\DoctrineBehaviors\Model\Tran  
  slatable\Translation define the same property ($id) in the composition of Mdy\XlagendaBundle\En  
  tity\EventTranslation. This might be incompatible, to improve maintainability consider using ac  
  cessor methods in traits instead. Class was composed 

And this is the message I get when I remove the id reference in the <entityName>Translation entity 

> [Doctrine\ORM\Mapping\MappingException]                                                          
  No identifier/primary key specified for Entity "Mdy\XlagendaBundle\Entity\EventTranslation". Ev  
  ery Entity must have an identifier/primary key.

Can anyone explain me what I should do ? I'm completely lost down here.
Thank you for any return and help you can provide me with ?

**Comment by docteurklein** [comment]
do you still have an error ? try to upgrade to the latest version, it might be a problem we fixed since then. Closing for now. Reopen if you think it worths it.
