### ISSUE TITLE
[Translatable] How to return an empty array if no translations

### ISSUE THREAD

**Issue by gthomasAdfab** [KnpLabs/DoctrineBehaviors#295]
Hello,
I want to know if is possible to get a json empty when entity has not translation.

Actually I get :

> ```
> {
>   "id": 17,
>   "code": "F02",
>   "image": "",
>   "translations": {
>     "en_US": {
>       "name": "",
>       "description": "",
>       "id": 87,
>       "locale": "en_US"
>     },
>     "fr_BE": {
>       "name": "Halal",
>       "description": "",
>       "id": 88,
>       "locale": "fr_BE"
>     },
>     "fr_FR": {
>       "name": "Halal",
>       "description": "",
>       "id": 86,
>       "locale": "fr_FR"
>     },
>     "fr_LU": {
>       "name": "Halal",
>       "description": "",
>       "id": 90,
>       "locale": "fr_LU"
>     },
>     "nl_BE": {
>       "name": "Halal",
>       "description": "",
>       "id": 89,
>       "locale": "nl_BE"
>     }
>   },
>   "current_locale": "en",
>   "default_locale": "en",
>   "created_at": "2015-05-04T15:16:27+0200",
>   "updated_at": "2015-05-11T10:38:29+0200"
> },
> {
>   "id": 35,
>   "code": "E999",
>   "translations": [],
>   "current_locale": "en",
>   "default_locale": "en",
>   "created_at": "2016-02-29T18:25:11+0100",
>   "updated_at": "2016-02-29T18:25:11+0100"
> }
> ```

Thx for your help

**Comment by TomasVotruba** [comment]
Closing as there is no-one to answer this question now.
