### ISSUE TITLE
[Translatable] Paginating translatables and translations

### ISSUE THREAD

**Issue by aderuwe** [KnpLabs/DoctrineBehaviors#296]
Hi,

We're left-joining the translations to our translatables, and trying to paginate that using the knp paginator.
One of the translation columns is the one we sort on (title). The below problem only occurs when we sort (i.e. title is in the ORDER BY).

Because of https://github.com/doctrine/doctrine2/issues/2630 and https://github.com/doctrine/doctrine2/issues/5622 that means that the title field will be SELECT'ed as well.

This returns duplicate id's to the limit subquery that gets the id's, breaking the pagination ever worse the more languages we translate in.

How should we go about avoiding it? We were trying to remove the title field from the SELECT, but given the above links, that's not a good idea.

Thanks for any hints!

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
