### ISSUE TITLE
Translation stopped working in Symfony 3.0.3 project with Doctrine behaviors 1.3

### ISSUE THREAD

**Issue by yvesblancquaert** [KnpLabs/DoctrineBehaviors#297]
Hi,

I've successfully used translatable in previous projects based on Symfony 2.8 and Doctrine Behaviors 1.2. In my current Symfony 3.0.3 project where I use Doctrine Behaviors 1.3 I keep getting the following error message: 
[Doctrine\ORM\Mapping\MappingException] No identifier/primary key specified for Entity "AppBundle\Entity\CanvasAclTranslation". Every Entity must have an identifier/primary key.

I've added the bundle to the AppKernel and only activated translatable via the config.yml file.
I've attached an overview of current installed packages and the entity classes.

Regards
Yves

[CanvasAcl.txt](https://github.com/KnpLabs/DoctrineBehaviors/files/164796/CanvasAcl.txt)
[CanvasAclTranslation.txt](https://github.com/KnpLabs/DoctrineBehaviors/files/164797/CanvasAclTranslation.txt)
[InstalledPackages.txt](https://github.com/KnpLabs/DoctrineBehaviors/files/164798/InstalledPackages.txt)

**Comment by NiR-** [comment]
Hey @yvesblancquaert, I looked at your CanvasAclTranslation and it appears that you are using the `Translatable` trait in the translation. You should try to fix that, and I think all your problems will disappear :)

**Comment by yvesblancquaert** [comment]
Hey @NiR- Ouch, that hurts :-) Thank you very much for looking at it. Copy-paste of class code was not that smart. All my problems have disappeared.

**Comment by NiR-** [comment]
Good news :)
