### ISSUE TITLE
How to use the translatable and doctrine second cache level ?

### ISSUE THREAD

**Issue by mpoiriert** [KnpLabs/DoctrineBehaviors#301]
I would like to use the second cache level on the translations of a translatable entity. Is there a know way to do that ?

**Comment by docteurklein** [comment]
i never tried. if it implies defining new metadata on some entities, you can try to listen at the loadclassmetadata even.

**Comment by mpoiriert** [comment]
I have edit your subcriber as a test and had the cache information. I would
need to had a listener after that one so the Metadata exist prior to me
setting it. does it make sens ?

**Comment by docteurklein** [comment]
yep, you can add your own listener, and modify the metadata on the fly for a specific entity.

http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/events.html#load-classmetadata-event

**Comment by kunicmarko20** [comment]
I stumbled upon the same problem, adding manually translations field with metadata fixed problem for me:
 
    //... AppBundle\Entity\Post  
    /**
     * @ORM\OneToMany(
     *     targetEntity="AppBundle\Entity\PostTranslation",
     *     orphanRemoval=true,
     *     mappedBy="translatable",
     *     indexBy="locale",
     *     cascade={"persist", "merge", "remove"}
     *)
     * @ORM\Cache(usage="NONSTRICT_READ_WRITE")
    */
    protected $translations;

**Comment by Einenlum** [comment]
Seems an answer was given that solves the problem. I close the issue for now.
