### ISSUE TITLE
[Loggable] Is it possible to version entity properties with Loggable?

### ISSUE THREAD

**Issue by anacicconi** [KnpLabs/DoctrineBehaviors#308]
Sorry, this is not an issue but a question. I just installed loggable for the first time and I thought I could use it to keep a versioning system in my database. I mean a table with the last version of my objects in order to check what the values of the properties were, for instance.

I don't know if I didn't understand something or if this is not the goal of the behavior but I was only able to keep track of bigger changes in the entity as a whole: the creation, if it was removed, deleted... Could somebody tell me if it's possible to use loggable to do what I'm searching for and how to do it?

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
