### ISSUE TITLE
Query entities that have a translation in the current locale?

### ISSUE THREAD

**Issue by Mondane** [KnpLabs/DoctrineBehaviors#309]
I have this querybuilder:

```
$queryBuilder = $this->createQueryBuilder('e')
                ->select('e, t')
                ->join('e.translations', 't')
                ->Where('t.locale = :locale')
                ->setParameter('locale', 'en');
```

This will return only those items that have a translation for the 'en' locale. But my problem is, how can I automatically get the current locale and, if that locale also holds a locations, get the correct translations?

Ie, when I have 'en_GB', I think I have to search entities that have one of these translations:
- en_GB
- en

Does the translatable behaviour provide this? Maybe something like https://blog.liplex.de/get-translatable-entity-from-repository-with-specific-locale/ ?

**Comment by docteurklein** [comment]
that is something we don't really support ATM. We only handle simple locales like 'en' or 'de', but we're not parsing 'en_US' for example, to detect that ti's 'en' **and** US.

**Comment by Mondane** [comment]
Is this something you could implement or give pointers how to add this support?

**Comment by docteurklein** [comment]
first of all, the query itself is independant from the rest. You can do the parsing alongside the query builder, and use `where t.locale IN (:locales)`, where `:locales` is an array constructed by you, like `['en_US', 'en']` if your received `en_US`.

Now you just have to override the `translate` (or `doTranslate`), or `findTranslationByLocale` method in your translatable entities. (see https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Model/Translatable/TranslatableMethods.php#L101)
