### ISSUE TITLE
[Softdeleteable] isDeleted() does not work with deleted related entities

### ISSUE THREAD

**Issue by spackmat** [KnpLabs/DoctrineBehaviors#311]
Hi,

I'm working with the SoftDeletable Trait and have a problem with soft-deleted records: If it is related and doctrine tries to access its properties via its relation, I get an Exception that an Entity with ID n is not found. This is correct, since it is marked as deleted and Doctrine won't fetch it. But now, I try to distinguish, if a related Entity is deleted before I access its properties. But calling isDeleted() also tries to fetch it, fails and throws the Exception.

Any suggestions on that? How can I prevent Doctrine from fetching related and soft-deleted Entities and failing? Shouldn't the isDeleted() method detect, if an Entity is soft-deleted? Is this a bug or a feature?

A bad workaround is to catch that Exception and return null instead of the related Entity in the getter for that relation, but this is stupid and should not be the solution:

```php
public function getRelatedEntity()
    try {
        $this->relatedEntity->isDeleted(); // or try to access any other property (but the id)
        return $this->relatedEntity; // not deleted, everything OK
    }
    catch (\Doctrine\ORM\EntityNotFoundException $e) {
        return null; // Doctrine could not fetch the soft-deleted related Entity and threw an Exception
    }
}
```

A little context: I have an activity stream with Activity-Entities having relations to their activity-objects. When a watched Entity is deleted, all old Activities referencing it must be preserved (since it is a log). This is cool, with soft-delete the references are still valid from the database perspective. But not from Doctrine's perspective, which is a problem here. When I fetch a deleted Entity directly and call isDeleted() on it, I get the correct behaviour, but not when I fetch it via a relation.

**Comment by spackmat** [comment]
I saw, that the documentation is wrong (or there is a bug) and isDeleted() doesn't work at all, if one doesn't disable the filter at all. So this code from the documentation leads to a not found exception (or whatever not found behavior):

    // hey, I'm still here:
    $category = $em->getRepository('Category')->findOneById($id);

    // but I'm "deleted"
    $category->isDeleted(); // === true

Instead anything similar to this should be in the documentation:

    // disable the softdeletable filter for a moment to fetch the deleted entity, even if it is soft-deleted
    $em->getFilters()->disable('softdeleteable');
    
    // hey, I'm still here:
    $category = $em->getRepository('Category')->findOneById($id);

    // but I'm "deleted"
    $category->isDeleted(); // === true

    // OK, we have our soft-deleted entity, so re-enable the softdeletable filter
    $em->getFilters()->enable('softdeleteable');

The problem mentioned in the first post can also be solved with this change:

1. Set the fetch mode of the relations to `eager`, so that the related entities are not lazy-loaded.
2. Disable the softdeletable-filter before the containing entities are fetched and re-enable it afterwards.

This only works, if the containing entities cannot be soft-deleted themselves. Is this the case, you can implement something like this (or just filter them with isDeleted() after the database call, if suitable):

1. Load the containing entities normally.
2. Accessing properties of their soft-deleted related entities leads to database errors as described above. So before accessing their properties, disable the softdeletable-filter, load the related entities (e.g. in the controller with findById()) and re-enable the filter afterwards.

Better would be, if the isDeleted()-method tried to load the soft-deleted entities without the filter, if they could not be loaded with the filter enabled. This would also match the documented behavior. So you could check, if an entity is soft-deleted.

**Comment by spackmat** [comment]
My workaround from the first post doesn't work anymore (the new ProxyGenerator with the generateMethods-method was introduces with Doctrine 2.4). Since then Every call of an entity-method (but the getter of the ID property) will provoke the Proxy to be initialized, which will result in an EntityNorFoundException. Before, only accessing a not-yet-loaded property provoked a Proxy-initialization.

A workaround to fix this workaround is to use something like this:

````
    /**
     * checks, if the object can be loaded from the database (i.e. is not soft deleted)
     * this implementation must be declared final to prevent the proxy class to be initialized on call
     *
     * @return bool  true or false, if the object is not loadable (i.e. is soft deleted)
     */
    public final function isObjectLoadable(): bool
    {
        try {
            // try to access a getter (not the ID, since it is always accessible, even before the object was fetched from the database)
            $this->getAnyPropertyButTheId();
        } catch (Doctrine\ORM\EntityNotFoundException $e) {
            return false;
        }
        return true;
    }
````

With such a method you can test, if a related entity is loadable.

In future project, I won't use the soft-deletable pattern anymore, since it is a constant source of problems. Maybe the archiveable-pattern could be a better solution for that.

**Comment by ViniH** [comment]
Hello there, I have a similar issue however my problem is compounded by the fact that this is happened in onFlush listeners, and the soft-deletable trait is only disabled for the listener.

Let's say you have an entity, let's call it Route, this entity has a property Page, which is Many-to-One relation and the Page entity itself is soft-deletable.

In PageRouteListener, the soft-deletable filter is disabled while the listener checks the route for the page, one of the tasks it does is to remove the route if the page is no longer 'found' (e.g. soft-deleted). The problem comes when the entity manager tries to remove the now defunct route - because the non-existent page cannot be loaded the ProxyFactory throws an EntityNotFoundException.

If the whole process was wrapped in disabled soft-deletable filter, it would likely work, but the filter is only applied in the listener, so all of the other onFlush listeners, including DoctrineProxySubscriber, have the filter enabled, and putting the filter disable around the actual flush would like raise other issues.

I am only able to modify our own codebase, so trying to come up with a workaround for this is proving tricky.

I am fairly sure this issue is closely related to the problem described in this page, hence my post.

Does anyone have any ideas?

**Comment by PowerKiKi** [comment]
This is closely related to an older issue reported in doctrine2: https://github.com/doctrine/doctrine2/issues/4543

**Comment by docteurklein** [comment]
Thanks @PowerKiKi to point this out. It seems related to how sql filters work within doctrine. A potential solution would be to disable the soft-deletable sql filter and adding the correct WHERE statements manually in all your queries.

**Comment by PowerKiKi** [comment]
According to linked issue, filters should never be used, or at the maximum a "always off, very rarely temporarily enabled" kind of usage. But really it ruins the concept of filters.

I really wonder why they were implemented in the first place. I cannot see a use case where they would be both more convenient than manually injecting DQL/SQL, and not wrecking havock in relations managed by doctrine.

**Comment by PowerKiKi** [comment]
@docteurklein I think this issue should be closed as wontfix, because it is unlikely to be fixable by non-Doctrine code and Doctrine itself is very unlikely to fix it on their side.
