### ISSUE TITLE
[Translatable] Can't query the non-current locale

### ISSUE THREAD

**Issue by NoelProg** [KnpLabs/DoctrineBehaviors#313]
I need to translate dynamic url data for a lang switcher. I have to query an entity and get the slug for the "other locale" but it always only gives me back the current locale data. What I do is that I query once the translated object and then use the id to query the other locale like so :

`
 $qb
                ->select('e, et')
                ->join('e.translations', 'et', 'WITH', 'et.locale = :locale')->setParameter('locale', $locale)
                ->where('e.id = :tid')->setParameter('tid', $identifier->getId())
                ;
`
However it only return the current locale data. Even if I try to do $entity->translate($locale) on my entity, it still only give me the translation for the locale that I don't want.

Is there any way to achieve what I want?
Thanks

**Comment by kryzalidhub** [comment]
The only way I found to workaround is a native SQL query using doctrie's prepared statement (of course you should use parameters and not variable directly inside a query) :

`$query = 'SELECT * FROM '.$tableName.' WHERE translatable_id = '.$entity->getId().' AND locale = "'.$locale.'" LIMIT 1';
                $stmt = $this->em->getConnection()->prepare($query);
                $stmt->execute();
                $results = $stmt->fetchAll();
`

But it kind of looks unclean so I'm not completely satisfied but at least it's some work around.

**Comment by NoelProg** [comment]
The only way I found to workaround is a native SQL query using doctrie's prepared statement (of course you should use parameters and not variable directly inside a query) :
`$query = 'SELECT * FROM '.$tableName.' WHERE translatable_id = '.$entity->getId().' AND locale = "'.$locale.'" LIMIT 1'; $stmt = $this->em->getConnection()->prepare($query); $stmt->execute(); $results = $stmt->fetchAll();`

But it kind of looks unclean so I'm not completely satisfied but at least it's some work around.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
