### ISSUE TITLE
Set fallback language for translator

### ISSUE THREAD

**Issue by vikey89** [KnpLabs/DoctrineBehaviors#319]
Hello guys,
I'm using [translatable component](https://github.com/KnpLabs/DoctrineBehaviors#translatable).

How can I set the fallback language?

My config.yml is:
```
framework:
    translator:      { fallbacks: [it] }
```

but this doesn't work.

**Comment by docteurklein** [comment]
the default locale for translatable entities is the DIC parameter named `"%locale%"`

**Comment by docteurklein** [comment]
maybe a note in the README would help. closing for now.
