### ISSUE TITLE
Tag new stable release

### ISSUE THREAD

**Issue by jankramer** [KnpLabs/DoctrineBehaviors#327]
The current stable version (1.3.2) is getting quite old, and does not include some important fixes: e.g. #316

**Comment by docteurklein** [comment]
#317 scares me a bit. I wouldn't want to tag something which hasn't been tested by  a lot of setups, but hey, let's try 1.4.0 and see

**Comment by docteurklein** [comment]
done

**Comment by jankramer** [comment]
Thanks!
