### ISSUE TITLE
[Translatable] translation.translatable_id shouldn't be nullable

### ISSUE THREAD

**Issue by EVDW** [KnpLabs/DoctrineBehaviors#330]

**Comment by homersimpsons** [comment]
Any consideration about this thread?

**Comment by Einenlum** [comment]
I don't think it's nullable right now. Is it?

https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php#L218-L229

**Comment by homersimpsons** [comment]
Just generate the schema and check in PHPMyAdmin or so and it's writed that `translatable_id`can be null...

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
