### ISSUE TITLE
[QUESTION] This Library support ODM?

### ISSUE THREAD

**Issue by ad3n** [KnpLabs/DoctrineBehaviors#333]
I see the folder structure and nothing found about ODM, is library support for ODM?

**Comment by docteurklein** [comment]
there is no support for ODM. I started [a PR](#15) a while ago, but nothing landed.

**Comment by ad3n** [comment]
@docteurklein : hhhmmm why you reject your PR? and never merge into master? That's we need because in my case, i use ODM to store masters and also use ORM to store transactions data.

I hope you will reopen that PR :-)
