### ISSUE TITLE
[Translatable] Get translatable field by locale

### ISSUE THREAD

**Issue by xmon** [KnpLabs/DoctrineBehaviors#337]
Hi, I need to get a list of a translatable field (slug), for all locales in controller. To build hreflang tags

I'm trying: 
```php
$news->translate('es')->getSlug();
$news->translate('en')->getSlug();
```

but allways return the values of current locale.

any idea?

**Comment by skytorner** [comment]
give translate methods its 2nd parameter to prevent fallback to default local
 
`$news->translate('en',  FALSE)->getSlug();`

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
