### ISSUE TITLE
[Timestampable] TimestampableMethods with DateTime

### ISSUE THREAD

**Issue by gsdevme** [KnpLabs/DoctrineBehaviors#339]
Hi,

I've noticed some odd things relating to DateTime & Doctrine but I also find this page on Doctrines docs
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html

Should the methods not be something similar to this? Given they are evaluated by reference we only want to change that reference if the Date & Time are different? 

Also would seem to make sense to clone the DateTime on the `gettter` also 

```
    /**
     * Returns createdAt value.
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return clone $this->createdAt;
    }

    /**
     * Returns updatedAt value.
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return clone $this->updatedAt;
    }

    /**
     * @param \DateTime $createdAt
     * @return $this
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        if ($this->getCreatedAt()->diff($createdAt, true)) {
            $this->createdAt = $createdAt;
        }

        return $this;
    }

    /**
     * @param \DateTime $updatedAt
     * @return $this
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        if ($this->getUpdatedAt()->diff($updatedAt, true)) {
            $this->updatedAt = $updatedAt;
        }

        return $this;
    }
```

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
