### ISSUE TITLE
Id field error with doctrine:schema:update --force command

### ISSUE THREAD

**Issue by kibizu** [KnpLabs/DoctrineBehaviors#340]
Hi,

I have theese class:

`<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
/**
 * FaqCategory
 *
 * @ORM\Table(name="faqcategory")
 * @ORM\Entity(repositoryClass="AppBundle\Entity\FaqCategoryRepository")
 */
class FaqCategory 
{
    
    use ORMBehaviors\Translatable\Translatable;    
    
    
    /**
     * @var integer
     *
     * @ORM\Column(name="categoryid", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $categoryid;

    /**
     * @var integer
     *
     * @ORM\Column(name="admin_id", type="integer", nullable=true)
     */
    private $adminId;    
  
    
    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="data_ins", type="datetime", nullable=false)
     */
    private $dataIns;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="change", field={"description","adminId"})
     * @ORM\Column(name="data_mod", type="datetime", nullable=true)
     */
    private $dataMod;`

and

`<?php

namespace AppBundle\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;

/**
 * @ORM\Entity
 */
class FaqCategoryTranslation {
    
    use ORMBehaviors\Translatable\Translation;
    
    /**
     * @var string
     *
     * @ORM\Column(name="description", type="string", length=255, nullable=true)
     */
    private $description;
}`

when i run the schema:update --force i get this error:

[Doctrine\ORM\ORMException]                                                  
  Column name `id` referenced for relation from AppBundle\Entity\FaqCategoryT  
  ranslation towards AppBundle\Entity\FaqCategory does not exist.

Why??

Thank you

**Comment by kibizu** [comment]
I solved it,

the column name that identifies the id must necessarily be "id".

**Comment by docteurklein** [comment]
yeah, it's still not configurable. thanks for te feedback!

**Comment by asgardia7** [comment]
All the primary key for the entity must be named  id????

**Comment by asgardia7** [comment]
**Solution 1 :**
You can map your own `translatable` association in your translatable entity. You could get inspiration from this default association in the `TranslatableSubscriber` class of knplabs.

`$classMetadata->mapManyToOne([
                'fieldName'    => 'translatable',
                'inversedBy'   => 'translations',
                'cascade'      => ['persist', 'merge'],
                'fetch'        => $this->translationFetchMode,
                'joinColumns'  => [[
                    'name'                 => 'translatable_id',
                    'referencedColumnName' => 'id',
                    'onDelete'             => 'CASCADE'
                ]],
                'targetEntity' => $classMetadata->getReflectionClass()->getMethod('getTranslatableEntityClass')->invoke(null),
            ]);`

**Solution 2 :** (yes, stil, messy but allow to avoid too many work if you have naming strategy).
In the above file (above code) `'referencedColumnName' => 'id',` at line 226 should be removed and the default naming strategy will be used. By default, doctrine use `id` too. But you then define your own custom naming strategy as described here : [](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/namingstrategy.html) .

**NB :**
For KnpLabs, as you just setted referencedColumnName id (same as the default naming strategy of doctrine). Why not just remove it and letting doctrine infer it from naming strategy? Anyway, anyone could set their custom association in their translatable entity.

**Comment by atim140** [comment]
**Solution 1 :**
You can map your own `translatable` association in your translatable entity. You could get inspiration from this default association in the `TranslatableSubscriber` class of knplabs.

`$classMetadata->mapManyToOne([
                'fieldName'    => 'translatable',
                'inversedBy'   => 'translations',
                'cascade'      => ['persist', 'merge'],
                'fetch'        => $this->translationFetchMode,
                'joinColumns'  => [[
                    'name'                 => 'translatable_id',
                    'referencedColumnName' => 'id',
                    'onDelete'             => 'CASCADE'
                ]],
                'targetEntity' => $classMetadata->getReflectionClass()->getMethod('getTranslatableEntityClass')->invoke(null),
            ]);`

**Solution 2 :** (yes, stil, messy but allow to avoid too many work if you have naming strategy).
In the above file (above code) `'referencedColumnName' => 'id',` at line 226 should be removed and the default naming strategy will be used. By default, doctrine use `id` too. But you then define your own custom naming strategy as described here : [](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/namingstrategy.html) .

**NB :**
For KnpLabs, as you just setted `referencedColumnName` to `id` (same as the default naming strategy of doctrine). Why not just remove it and letting doctrine infer it from naming strategy? Anyway, anyone could set their custom association in their translatable entity.
