### ISSUE TITLE
[Translatable] Too many database access

### ISSUE THREAD

**Issue by homersimpsons** [KnpLabs/DoctrineBehaviors#343]
Hello,
I'm using Translatable to get various language of created events.
I'm using the Twig template to get the translation `{{ event.translate(app.request.locale).name }}`
This works very well, but I see that each time this function is called, a new request is done.

I would like to be able to fetch all the translations when looking into the database to avoid guetting tons of access.

The idea is that, when I use `$nextEvents = $repository->findAll();` this have to return `$nextEvents` with the name translation (in current locale > fallback one > one that exist).
Then a Twig access could look like `{{ event.name }}` (just as before translations)

Is it possible ?
Or do you get a code to reduce database queries?

Hope I was clear, don't hesitate to reply for more informations.

**Comment by docteurklein** [comment]
that's more a doctrine problem: you'll need to "fetch join" the translations alongside the translatable entity.
see http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#joins for more details

**Comment by homersimpsons** [comment]
Couldn't this be done by KnpLabs/DoctrineBehaviors(Translatable) extension instead of doing this manually each time?

**Comment by docteurklein** [comment]
there is a parameter for changing the default loading strategy from "lazy" to "eager": https://github.com/KnpLabs/DoctrineBehaviors/blob/master/config/orm-services.yml#L9-L10

**Comment by homersimpsons** [comment]
Ok I think that this is what I needed, Thank you.
This need to be Documented somewhere.

**Comment by homersimpsons** [comment]
Hello, I come back to you, if I switch from LAZY to EAGER this doesn't change anything.
That mean, if I have 50 results after `$query->getResult();` It will generate 50 requests more.

Maybe, if possible, you could create a method `hydrateObjects($Objects)` (where `$Objects = $query->getResult()` objects) that would hydrate all object with one request.

**Comment by homersimpsons** [comment]
#285

**Comment by homersimpsons** [comment]
FTR I did create a method in my repository: `getQBWithTranslations` that `leftJoin` my translation table with the current language so it's a kind of eager loading

**Comment by TomasVotruba** [comment]
Could you send PR to correct this behavior?

Not sure if in scope of package though, might be Doctrine side.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
