### ISSUE TITLE
is it possible to disable the event driven ORM mapping ?

### ISSUE THREAD

**Issue by kermorgant** [KnpLabs/DoctrineBehaviors#346]
Hello,

Just wrote about an issue with CraueFormFlowBundle here : https://github.com/craue/CraueFormFlowBundle/issues/271

I suspect it's due to the way the mapping is made with a subscriber here, and which is not seen by the FlowBundle.

Would there be a simple way to write down the mapping (I'm using yaml) in my configuration, just to get CraueFormFlow working ?

Regards
Mikael

**Comment by docteurklein** [comment]
yes you can disable the subscriber (but globally, not just the metdata event listener).

But AFAIR, all the subscribers allow you to write the mapping by hand, and won't redefine a field (or assoc) of the same name.

**Comment by kermorgant** [comment]
Thanks.

Indeed, I was just doing the mistake of adding the $translations property besides doing the mapping by hand. Without this, I can have the subscriber and the handmade mapping.

Sadly, it did not solve my issue with my form flow but I can at least close this one.
