### ISSUE TITLE
[Translatable] default Locale issue - setLocales method of TranslatableSubscriber not hit

### ISSUE THREAD

**Issue by kermorgant** [KnpLabs/DoctrineBehaviors#347]
Hello,

I've setup the translatable behavior for a Project Entity. I've got it working (My project is using SF 2.8, knp doctrine behavior 1.4), but one issue remains with default locale. There are two locales (fr & en, the default and fallback locale being fr).

In my current setup, I always get "en" being the default locale for the entity, although I think I've made the ad hoc settings to get 'fr'.

I've setup a LocaleCallable class, and looking at the code, it should be called in TranslatableSubscriber in the setLocales method, but having run a debugger with a breakpoint on that method, nothing happens. 

`
parameters:
    knp.doctrine_behaviors.translatable_subscriber.default_locale_callable.class: AppBundle\Listener\LocaleCallable
`

I've manually activated the subscriber in config.yml (and also registered the bundle in AppKernel)

`

knp_doctrine_behaviors:
    translatable: true
    sluggable:      true
`

Any idea or suggestion to debug this further ?

**Comment by kermorgant** [comment]
Two comments 

* For now, I've added "getDefaultLocale" on the translatable entity, which lets me move further with my work.

* the page where the issue happened was an index (fetching projects from the repository, sending them o twig). But on another page, where I instanciated another project, I noticed the callable for the default language was called (I had forgotten a var_dump there).

I guess it has something to do with the way I fetch the projects, which does not trigger the postLoad event.

**Comment by ambrous** [comment]
I faced with the similar issue.

I found that **TranslatableSubscribe::setLocales** is called only within **postLoad** and **prePersist** events so if you do not set up a locale when you call **translate** method on an entity you will have default locale of **en**.

**Comment by ambrous** [comment]
Maybe it is possible to chane the **TranslatableSubscribe::setLocales** method to public and call it before sending to the **EventManager**?

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now. There have been many changes in recent days. Failing test case would be needed to reproduce.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
