### ISSUE TITLE
[Tree] Add alias as parameter of method addFlatTreeConditions

### ISSUE THREAD

**Issue by martinknor** [KnpLabs/DoctrineBehaviors#351]
It will be nice, if i know alias of main select in this method. Because for example:
I need order by priority: ->addOrderBy('t.priority', 'ASC')
I need join something (translations):  ->leftJoin($rootAlias.'.translations', 'tr')

etc...

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
