### ISSUE TITLE
[Loggable] loggable with user in doctrine logger

### ISSUE THREAD

**Issue by ljay79** [KnpLabs/DoctrineBehaviors#354]
Hi.
Im using the loggable bundle with a doctrine loggable callable.
I have tried every way i could figure and researched 3 days long in internet, however i cant find a way of having the user/username logged within the loggable callable.

Using Symfony 2.8 passing tokenstorage but getToken() will always return null, even when inside an authenticated backoffice area.

PS: Im a symfony noob, and maybe i simply miss a big fat lifecycle logic issue here.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
