### ISSUE TITLE
[Translatable] Child Relation Form Type

### ISSUE THREAD

**Issue by ScherlOMatic** [KnpLabs/DoctrineBehaviors#355]
Hello!

I've been looking around for my problem quite a while and maybe you guys have a solution for me ready.

My entities are this:
`
class Category {
  use ORMBehaviors\Translatable\Translatable;
}
`
`
class CategoryTranslation {

    use ORMBehaviors\Translatable\Translation;
    
     /**
     * One CategoryTranslation has One CategorySeo.
     * @ORM\OneToOne(targetEntity="CategorySeo", mappedBy="categoryTranslation")
     */
    private $categorySeo;
`
`
class CategorySeo {
    /**
     * One CategorySeo has One CategoryTranslation.
     * @ORM\OneToOne(targetEntity="CategoryTranslation", inversedBy="categorySeo")
     * @ORM\JoinColumn(name="category_translation_id", referencedColumnName="id")
     */
    protected $categoryTranslation;
`

As you can see Category is linked to CategoryRelation (OnetoMany) and CategoryRelation is linked to CategorySeo (OnetoOne).

Now I wanted to build a Admin User Interface with Sonata to edit Category Seo. I can edit all fields from Seo but I am not able to set the relation to CategoryTranslation.
`class CategorySeoAdmin extends AbstractAdmin {
   ->add('categoryTranslation', 'sonata_type_model', [
                    'property' => 'name'
                ])
`

What I get when accesing the designated page is simple nothing, no error, all other fields are rendered but the field category Translation only includes the label field.

After creating a CategoryTranslationAdmin class and a __toString() function my choices are getting rendered but saving generates following exception: Could not determine access type for property "categoryTranslation".

I know i could link CategorySeo to Category but I'd rather use the given setup.
Does anyone have a hint for me what could be wrong?

thx in advance stefan

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
