### ISSUE TITLE
[Tree] Multiple trees for the same table

### ISSUE THREAD

**Issue by doxt3r** [KnpLabs/DoctrineBehaviors#356]
Hi,
I'm trying to structure a table "topic", every topic can have childs and parents.
Does the Tree trait  table to have multiple root nodes ?

If yes could you give a little example ?

Thank you!

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
