### ISSUE TITLE
[Tree] Flat tree query issue

### ISSUE THREAD

**Issue by sokrev** [KnpLabs/DoctrineBehaviors#357]
The `getFlatTreeQB()` method is using only LIKE operator to compare paths and can return wrong results.

Lets asume we use IDs for path generation. When getting flat tree for entity with id === 1, the query is something like `WHERE materialized_path LIKE '/1%'`. That means if i have element assigned to parent with id 10, 11, 12 and so on, it will be returned either.

**Comment by Einenlum** [comment]
Hi @ksobol. Thanks for your feedback. It seems it's indeed possible that it returns wrong values.
I will try to take time to fix this.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
