### ISSUE TITLE
[Translatable] Empty value cause problem in v1.4.1

### ISSUE THREAD

**Issue by martinknor** [KnpLabs/DoctrineBehaviors#362]
I have entity:
```php
class ProductVariantTranslation
{
	use Translation;

	/**
	 * @ORM\Column(type="string", nullable=true)
	 * @var string
	 */
	protected $name;
}
```

The problem was caused, if i have empty name property and call this

```php
$variant->setName('');
$variant->mergeNewTranslations();
```

returns

```Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO product_variant_translation (name, locale, translatable_id) VALUES (?, ?, ?)' with params [\"\", \"cs\", 1]:\```

because this function evaluates this translation as empty in version 1.4.1

https://github.com/KnpLabs/DoctrineBehaviors/blob/6b99da7e6bb5570657bec6c3d7b55455b270fa19/src/Model/Translatable/TranslationMethods.php#L94

**Comment by Einenlum** [comment]
Hi @martinknor. Are you sure it's related to the `isEmpty()` method? Cause it seems that your error comes from a duplicate translation for the same locale. Are you sure it works with a non empty translation? Don't you have already a translation for the same translatable, with the locale `cs`?

**Comment by martinknor** [comment]
Hi @Einenlum. Yes, I'm sure. Problem is here:
I have entity:
```php
class ProductVariantTranslation
{
	use Translation;
        #'id', 'translatable', 'locale'
	/**
	 * @ORM\Column(type="string", nullable=true)
	 * @var string
	 */
	protected $name;
}
```
```php
 foreach (get_object_vars($this) as $var => $value) {
            if (in_array($var, ['id', 'translatable', 'locale'])) {
                continue;
            }
            if (!empty($value)) { # $name = '' is resolved as empty - new Translation is created. This is wrong, because i can have empty translation. I think $value === null will be better.
                return false;
            }
        }
        return true;
```

**Comment by StefanNiederkofler** [comment]
I have the same problem. But even a NULL value should be possible. I think the main problem is here:

https://github.com/KnpLabs/DoctrineBehaviors/blob/d27e25ff9bab8f6c0b88a2115e7fdd2d74b08fbb/src/Model/Translatable/TranslatableMethods.php#L102

`
protected function doTranslate($locale = null, $fallbackToDefault = true)
{

        if (null === $locale) {
            $locale = $this->getCurrentLocale();
        }

        $translation = $this->findTranslationByLocale($locale);
        if ($translation and !$translation->isEmpty()) {
            return $translation;
        }

        if ($fallbackToDefault) {
            if (($fallbackLocale = $this->computeFallbackLocale($locale))
                && ($translation = $this->findTranslationByLocale($fallbackLocale))) {
                return $translation;
            }

            if ($defaultTranslation = $this->findTranslationByLocale($this->getDefaultLocale(), false)) {
                return $defaultTranslation;
            }
        }

        $class       = static::getTranslationEntityClass();
        $translation = new $class();
        $translation->setLocale($locale);

        $this->getNewTranslations()->set((string)$translation->getLocale(), $translation);
        $translation->setTranslatable($this);

        return $translation;
    }
`

if the translation is "empty", it creates a new entity, but there could be already an empty existing one.

**Comment by grachevko** [comment]
We also have issue related to `isEmpty()` method.
Translation with only one property and value `"0"` return new translations instead of existing.

**Comment by maciek-kemnitz** [comment]
The issue is still not fixed. Can we do something about that? @StefanNiederkofler commit should fix the problem.

**Comment by mpoiriert** [comment]
Same issue here... took 2 hours to find !!!
Why this check is done anyway ?
I have a label only in my entity and the value can be '0' so it fail...

**Comment by gsinkovskiy** [comment]
I have the same issue
