### ISSUE TITLE
Symfony - Form - EntityType - Access translation property(choice_label, group_by)

### ISSUE THREAD

**Issue by kironet** [KnpLabs/DoctrineBehaviors#370]
Hello,

I have a problem with form.
Exactly in ` 'choice_label' => 'name',`
I tried to call ` translations.name` and 'translations[en].name'

Error for choice_label => 'name': 
> Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "App\Entity\Product\Category".

Error for choice_label => 'translations.name'
> Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "Doctrine\ORM\PersistentCollection".

Error for `choice_label => 'translations[en].name`
> Cannot read property "name" from an array. Maybe you intended to write the property path as "[name]" instead.

```
$builder->add('parent', EntityType::class, [
            'required' => false,
            'class' => Category::class,
            'choice_label' => 'name',
            'placeholder' => 'form.category.parent.placeholder',
            'label' => 'form.category.parent.label',
            "choice_translation_domain" => 'categories'

        ]);
```

**Comment by TheBrauxois** [comment]
I have the same issue, what did you do to fix it ?

**Comment by giovkanata** [comment]
@TheBrauxois [maybe this could help you](https://stackoverflow.com/questions/29232860/how-to-access-translated-property-using-knp-labs-translatable-doctrine-behaviors/29233740#29233740)

**Comment by kironet** [comment]
@TheBrauxois I think I've just removed the bundle :D 
But now it's working for me like this:

`'choice_label' => "translations[en].name"`
