### ISSUE TITLE
[filterable] Repository contains 2 abstract methods

### ISSUE THREAD

**Issue by megadruck** [KnpLabs/DoctrineBehaviors#372]
I am using the same Repository, which is descripted in the documentation

`class CategoryRepository extends EntityRepository
{
     use Filterable\FilterableRepository;

     public function getLikeFilterColumns()
     {
         return ['e:name', 'o:mandant'];
     }

     public function getEqualFilterColumns()
     {
         return [];
     }

     protected function createFilterQueryBuilder()
     {
         return $this
             ->createQueryBuilder('e')
             ->leftJoin('e.orders', 'o');
     }
}`

If I call the Repository with
$nodes = $em->getRepository('AppBundle:Category')->filterBy(['o:mandant' => $mandant]);

I got the error like in the title.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
