### ISSUE TITLE
fetching data in each locale

### ISSUE THREAD

**Issue by salimmejdoub** [KnpLabs/DoctrineBehaviors#373]
hello how can i fetch data for each locle in my front-end 
for exemple if i'm in Fr version the Fr data will be fetched

thanks a lot

**Comment by flug** [comment]
Can you give me more details?

**Comment by salimmejdoub** [comment]
for exemple in my entity 
i have title and description saved in database with those locales ( fr,en)
when in my url i have /fr/ it display the Fr version  of title and description 
if my url contains en/   it display the En version of title and description

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
