### ISSUE TITLE
getting data out of translation entity

### ISSUE THREAD

**Issue by megadruck** [KnpLabs/DoctrineBehaviors#374]
How to get the data out of translation Entity for a given locale after

$category = $em->getRepository('AppBundle:Category')->getTree();

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
