### ISSUE TITLE
Maintainers addition

### ISSUE THREAD

**Issue by Soullivaneuh** [KnpLabs/DoctrineBehaviors#379]
I saw you are looking for maintainers.

I don't have a lot of time, but I would like to be part of them to at least insure minimum maintenance (packages and PHP compatibility, critical bugfixes etc...)

If you don't want to maintain the package anymore, maybe add me as an admin? So I'll be able to add other maintainers later. :+1:

**Comment by NiR-** [comment]
We're definitely lacking maintainers on this project and we would really like to see it get the attention it deserves.

I added you as a maintainer. If you're missing something let me know. And if you know some other people willing to help us maintain this package, tell them we're eager to welcome new maintainers ;)

Welcome on board!

**Comment by Soullivaneuh** [comment]
Thanks! Anything important I should now about contributing rules here? :-)
