### ISSUE TITLE
Q: Translatable: Cache translations

### ISSUE THREAD

**Issue by kironet** [KnpLabs/DoctrineBehaviors#381]
Hi,

I'm using this bundle for multi languages categories. Because I have a lot of categories + translations, it has +- 100 queries. So I'd like to cache categories and fetch it from cache. 
I tried to use repository and instead of getResult I called getArrayResult but getting this error 

> Impossible to invoke a method ("translate") on an array

Because it's not in array. 

So I'd like to ask, how would you cache translations?

Thanks

**Comment by TomasVotruba** [comment]
Not sure if this is place to cache this. I'd go with Doctrine 2 level cache
