### ISSUE TITLE
 SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t     oo long; max key length is 767 bytes  

### ISSUE THREAD

**Issue by kironet** [KnpLabs/DoctrineBehaviors#384]
Hi,

I'm getting this error:

 

> SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
>   oo long; max key length is 767 bytes  

How can I change default lenght of locale columnt(it should be 190)?

**Comment by julien-maitan** [comment]
but is this really necessary ??? who uses language code up to 190 chars ? in most case you'll use 2 chars or maybe 5 for language code like en, en-gb, en-us. And according to https://stackoverflow.com/a/2608667/4552457 if you use IETF language tags the longest would be zh-hant (7 chars).

Also this is a mysql 5.6 and lower related problem. If you use 5.7 and above, the limit has been increased to 3072 bytes. And it is also related to the charset used for the table (utf8mb4). 

You can also, as a quick fix, set the column definition yourself, and it won't be overridden by the subscriber:

```php
class EntityTranslation
{
    use ORMBehaviors\Translatable\Translation;

    /**
     * @ORM\Column(type="string", length=7)
     */
    protected $locale;
}
```
Related to https://github.com/KnpLabs/DoctrineBehaviors/issues/388

**Comment by gnutix** [comment]
I had the same error because the project was configured by default with a `utf8mb4` charset and a MySQL 5.6 instance. Changed the charset to `utf8` and the error was gone.
