### ISSUE TITLE
{{ item.getName }} work but not {{ item.name }}

### ISSUE THREAD

**Issue by AxelBriche** [KnpLabs/DoctrineBehaviors#385]
Hello, I use the proxy and {{ item.getName }} work but not {{ item.name }}, it is possible to use .name directly with the proxy ? Thanks.

**Comment by AdelBachene** [comment]
@AxelBriche is your variable `$name` private?

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/KnpLabs/DoctrineBehaviors/pull/440
