### ISSUE TITLE
Sortable: getSortProperty

### ISSUE THREAD

**Issue by binhle410** [KnpLabs/DoctrineBehaviors#386]
we need something like getSortProperty to easily customise the default "sort" property to any other name, say: position as in http://bib.schema.org/position

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
