### ISSUE TITLE
[Translatable] Shrink locale column

### ISSUE THREAD

**Issue by NiR-** [KnpLabs/DoctrineBehaviors#388]
During a database migration from `utf8` charset to `utf8mb4`, I realized that `locale` columns coming from this library are `VARCHAR(255)`. This works, but it's not optimum. It would be better to shrink down these columns to 2 chars.

Unfortunately, this would be a BC break and thus it could be done only for the next major release.

**Comment by CoalaJoe** [comment]
What about en-us and en-gb? Maybe 2 is too small.

**Comment by NiR-** [comment]
@CoalaJoe Indeed, I checked Symfony routing to see what is allowed, and determined 2 would be ok for this library; But as it can be used without Symfony, so limiting to 5 seems more reasonable :)

**Comment by sylvaincombes** [comment]
imho we should have an upper limit and let the maxlength possible (190 if we want utf8mb4 compliance)

For example this is a valid locale with 3 components : zh_Hant_CN (Language code, Script code, Country code), but this one is a valid too de_DE_u_co_phonebk_cu_ddm

As seen on the CLDR site we can have :

```
unicode_language_subtag(2)_unicode_script_subtag(4)_unicode_region_subtag(2)_unicode_variant_subtag(8?)_[key_type, key_type, ...]
```
On real projects the longest I have used is zh_Hant_CN / zh_Hans_CN but I think it's a better strategy to give more room for developers choice and flexibility

References :

- https://www.unicode.org/reports/tr35/tr35-17.html#Locale
- https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/KnpLabs/DoctrineBehaviors/pull/389
