### ISSUE TITLE
HasLifecycleCallbacks conflict

### ISSUE THREAD

**Issue by DreLincolin** [KnpLabs/DoctrineBehaviors#393]
Not sure if this is a issue or a feature but if you want to have your own Life Cycle Callbacks in the Entity itself: You will have to choose between your callbacks or this behaviours;

just add @ORM\HasLifecycleCallbacks after @ORM\Entity

Didn't see any reference in the docs about this so i thought i would report this.

Cheers

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
