### ISSUE TITLE
KnpLabs/DoctrineBehaviors (translatable) with Vichuploadbundle

### ISSUE THREAD

**Issue by alex83130** [KnpLabs/DoctrineBehaviors#396]
I use the bundle KnpLabs/DoctrineBehaviors (translatable) for to manage my translation.

I use also the bundle vichuploadbundle to manage my img.

I have an entity that must have different images depending on languages, so I placed my img field in my entityTranslatable entity. But I have this error because my image field is in CreationTranslation entity. How mapping this ? :

![capture](https://user-images.githubusercontent.com/15250423/43637633-010369be-9716-11e8-87d3-ff3a43642e98.PNG)

This is my twig code : 

`{{  vich_uploader_asset(creation, 'imageCreation ') }}`

And this is my entity code : 
```
	/**
	 * @Vich\UploadableField(mapping="image_creation", fileNameProperty="image")
	 * @var File
	 */
	private $imageCreation;
```
Thank you in advance

**Comment by TomasVotruba** [comment]
Provide full translatable + translation entity, so we can debug

**Comment by garak** [comment]
Can't you extract CreationTranslation from creation? If so, you should pass it to `vich_uploader_asset` helper.
By the way, if `imageCreation` is the only mapped field in entity and you're using VichUploaderBundle 1.11+, you can omit (the bundle will get it automatically)

**Comment by TomasVotruba** [comment]
Closing as possibly fixed in newer Symfony, KnpLabs and VichUploaderBundler version. 
If not, provide test case in PR. Thank you
