### ISSUE TITLE
Package is not installable via composer: The archive may contain identical file names with different capitalization

### ISSUE THREAD

**Issue by diimpp** [KnpLabs/DoctrineBehaviors#398]
```bash
$ docker-compose exec php composer require knplabs/doctrine-behaviors:~1.5
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing knplabs/doctrine-behaviors (1.5.0): Loading from cache
    Failed to execute unzip -qq  '/srv/api/vendor/knplabs/doctrine-behaviors/3d9b6237588659f3873aa8a1081df68a' -d '/srv/api/vendor/composer/8a9bb8db'

unzip: short read

    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class
```

As result, I've empty `vendor/knplabs/doctrine-behaviors` directory.
Apparently my docker image runs on case insensitive FS and there are files with same names, but in different case in the repository.

There are same style bugs in other projects, so I decided to open it here as well.

I'm still debugging this issue, so I'll update it if I'll found a workaround or it will turn up to be invalid.

**Comment by opassion** [comment]
@diimpp did you figure out the solution for this?

**Comment by diimpp** [comment]
@opassion I don't quite remember, most likely I didn't use it in the end, but you always can fork the repository and rename conflicting files and use your repository as vcs source for the composer package.

**Comment by TomasVotruba** [comment]
Should by fixed now with PSR-4 used everywhere.

If not, please report exact file that is causing this
