### ISSUE TITLE
Apply to be a maintainer

### ISSUE THREAD

**Issue by binhle410** [KnpLabs/DoctrineBehaviors#399]
If you still look for a maintainer, let me know.
I would like to become a contributor.

**Comment by docteurklein** [comment]
@binhle410 that would be awesome and ok for me if other @knplabs are ok too (@PedroTroller @NiR- , ...)

**Comment by TomasVotruba** [comment]
Hi, I'm current new maintainer (= doing all the merges and issues).

Help woudl be great. Can I ask you to go through the issues and identify those most likely to close and ping me there? Old, unclear, probably solved etc.

Thank you

Next step would be finishing this: https://github.com/KnpLabs/DoctrineBehaviors/issues/241
