### ISSUE TITLE
DoctrineBehaviors translatable in Symfony 4 ?

### ISSUE THREAD

**Issue by Rmy5** [KnpLabs/DoctrineBehaviors#403]
I'm trying to use the translatable extension in Symfony 4.
Just setup a test following the documentation example:
translatable entity:

    <?php

         namespace App\Entity;

        use Doctrine\ORM\Mapping as ORM;
        use Knp\DoctrineBehaviors\Model as ORMBehaviors;

       /**
         * @ORM\Entity(repositoryClass="App\Repository\FAQRepository")
         */
        class FAQ
        {
            use ORMBehaviors\Translatable\Translatable;

            /**
             * @ORM\Id()
             * @ORM\GeneratedValue()
             * @ORM\Column(type="integer")
             */
            private $id;

            /.**
             * @ORM\Column(type="datetime", nullable=true)
             */
            private $updatedAt;

            public function getId(): ?int
            {
                return $this->id;
            }

            public function getUpdatedAt(): ?\DateTimeInterface
            {
                return $this->updatedAt;
            }

            public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
            {
                $this->updatedAt = $updatedAt;

                return $this;
            }
        }

translation entity:

        <?php
        
        namespace App\Entity;
        
        use Doctrine\ORM\Mapping as ORM;
        use Knp\DoctrineBehaviors\Model as ORMBehaviors;
        
        /**
         * @ORM\Entity
         */
        class FAQTranslation
        {
            use ORMBehaviors\Translatable\Translation;
        
            /**
             * @ORM\Column(type="text")
             */
            protected $question;
        
            /**
             * @ORM\Column(type="text")
             */
            protected $answer;
        
            /**
             * @ORM\Column(type="integer", nullable=true)
             */
            protected $category;
        
        
            public function getQuestion(): ?string
            {
                return $this->question;
            }
        
            public function setQuestion(string $question): self
            {
                $this->question = $question;
        
                return $this;
            }
        
            public function getAnswer(): ?string
            {
                return $this->answer;
            }
        
            public function setAnswer(string $answer): self
            {
                $this->answer = $answer;
        
                return $this;
            }
        
        
            public function getCategory(): ?int
            {
                return $this->category;
            }
        
            public function setCategory(?int $category): self
            {
                $this->category = $category;
        
                return $this;
            }
        }

Getting  **No identifier/primary key specified for Entity "App\Entity\FAQTranslation". Every Entity must have an identifier/primary key.** when running **doctrine:schema:update --force**.

All the documentations I found seem to refer to Symfony 3 or even Symfony 2, is it possible to use DoctrineBehaviors in Symfony 4 ?

**Comment by treatys** [comment]
What is your solution? I have the same problem and absolutely no idea how to get it work.

**Comment by bbkr66** [comment]
You have just to call the bundle in your bundles.php :
Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true],

**Comment by TheRatG** [comment]
> You have just to call the bundle in your bundles.php :
> Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true],

it doesn't help

**Comment by byhaskell** [comment]
Symfony 4.4. It helped to add the key to the translation file, as shown in this comment https://github.com/KnpLabs/DoctrineBehaviors/issues/404#issuecomment-506898805
