### ISSUE TITLE
Using DoctrineBehaviors translatable in Symfony 4 ?

### ISSUE THREAD

**Issue by Rmy5** [KnpLabs/DoctrineBehaviors#404]
I'm trying to use the translatable extension in Symfony 4.
Just setup a test following the documentation example:
translatable entity:

    <?php

         namespace App\Entity;

        use Doctrine\ORM\Mapping as ORM;
        use Knp\DoctrineBehaviors\Model as ORMBehaviors;

       /**
         * @ORM\Entity(repositoryClass="App\Repository\FAQRepository")
         */
        class FAQ
        {
            use ORMBehaviors\Translatable\Translatable;

            /**
             * @ORM\Id()
             * @ORM\GeneratedValue()
             * @ORM\Column(type="integer")
             */
            protected $id;

            /.**
             * @ORM\Column(type="datetime", nullable=true)
             */
            protected $updatedAt;

            public function getId(): ?int
            {
                return $this->id;
            }

            public function getUpdatedAt(): ?\DateTimeInterface
            {
                return $this->updatedAt;
            }

            public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
            {
                $this->updatedAt = $updatedAt;

                return $this;
            }
        }

translation entity:

        <?php
        
        namespace App\Entity;
        
        use Doctrine\ORM\Mapping as ORM;
        use Knp\DoctrineBehaviors\Model as ORMBehaviors;
        
        /**
         * @ORM\Entity
         */
        class FAQTranslation
        {
            use ORMBehaviors\Translatable\Translation;
        
            /**
             * @ORM\Column(type="text")
             */
            protected $question;
        
            /**
             * @ORM\Column(type="text")
             */
            protected $answer;
        
            /**
             * @ORM\Column(type="integer", nullable=true)
             */
            protected $category;
        
        
            public function getQuestion(): ?string
            {
                return $this->question;
            }
        
            public function setQuestion(string $question): self
            {
                $this->question = $question;
        
                return $this;
            }
        
            public function getAnswer(): ?string
            {
                return $this->answer;
            }
        
            public function setAnswer(string $answer): self
            {
                $this->answer = $answer;
        
                return $this;
            }
        
        
            public function getCategory(): ?int
            {
                return $this->category;
            }
        
            public function setCategory(?int $category): self
            {
                $this->category = $category;
        
                return $this;
            }
        }

Testing the translatable entity:

            /**
             * @Route("/test", name="test")
             */
            public function testfaq()
            {
                $em = $this->getDoctrine()->getManager();
        
                $faq = new FAQ();
                $faq->translate('fr')->setQuestion('Quelle est la couleur ?');
                $faq->translate('en')->setQuestion('What is the color ?');
                $em->persist($faq);
        
                $faq->mergeNewTranslations();
                $em->flush();
        
                return $this->render('app/test.html.twig', [
                ]);
            }

A new ID is added in the **faq** table.
But nothing is persisted in the **faqtranslation** table.

All the documentations I found seem to refer to Symfony 3 or even Symfony 2, is it possible to use DoctrineBehaviors translatable in Symfony 4 ?

**Comment by msphn** [comment]
@Rmy5 in case you didn't find a solution. `mergeNewTranslations ` needs to be called before persisting the entity.

**Comment by Rmy5** [comment]
@msphn Thanks ! I'll have a look at it.

**Comment by msphn** [comment]
@Rmy5 any news? I use it in several 3.5, 4.1 and 4.1 projects.

**Comment by Roman9961** [comment]
@Rmy5  tell please how you solve "No identifier/primary key specified " problem?

**Comment by Rmy5** [comment]
@Roman9961 Well I needed a quick solution so I ended up not using DoctrineBehaviors. But I will look into DoctrineBehaviors when I get around to it.

**Comment by quiquegarcia** [comment]
@Roman9961 the properties definition in the Translation and Translatable traits is not using the @ORM\column annotation, so you need to add it to your entities.

For example:

```php
/**
 * @var int
 *
 * @ORM\Column(name="id", type="integer", nullable=false, options={"unsigned"=true})
 * @ORM\Id
 * @ORM\GeneratedValue(strategy="IDENTITY")
 */
protected $id;
```
I will be checking this bundle because it needs to be updated to work with symfony4

**Comment by msphn** [comment]
It works with symfony4
