### ISSUE TITLE
[Translations] BC Break current locale

### ISSUE THREAD

**Issue by grachevko** [KnpLabs/DoctrineBehaviors#405]
We use trait in parent class, this pr https://github.com/KnpLabs/DoctrineBehaviors/pull/392 break setting current locale as [TranslatableSubscriber](https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/ORM/Translatable/TranslatableSubscriber.php#L288) call `getClassAnalyzer::hasTrait` in non recuresive mode. 
Maybe shoulde add recuresive to solve this? Or make it configurable.

**Comment by jaroslavlibal** [comment]
We are facing the same issue and we would also love to make this configurable.

**Comment by tristanbes** [comment]
We're also facing the same issue
