### ISSUE TITLE
Knp\DoctrineBehaviors\Bundle\DependencyInjection\Configuration: deprecation message with Symfony 4.2

### ISSUE THREAD

**Issue by SinErgy84** [KnpLabs/DoctrineBehaviors#408]
Getting deprecation message with Symfony 4.2 due to "A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0."

Solution: 

replace
`
$builder = new TreeBuilder(); 
$builder->root('knp_doctrine_behaviors')
`

with

`
$builder = new TreeBuilder('knp_doctrine_behaviors');
$builder->getRootNode()
`

For futher information see [Symfony 4.2 Upgrade Guide Part #config](https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md#config)

**Comment by msphn** [comment]
@SinErgy84 would you provide a pull request?

**Comment by deman714** [comment]
Merge it, please, somebody who can. I'm tired of that deprecated message in Symfony.

**Comment by trboltom** [comment]
I am afraid this whole repo is just dead

**Comment by TomasVotruba** [comment]
Resolved
