### ISSUE TITLE
I can help out

### ISSUE THREAD

**Issue by msphn** [KnpLabs/DoctrineBehaviors#409]
I'm using the DoctrineBehaviors in projects. As you requested for help, I'd would like to do so.

As everyone I don't have a lot time, I'm working full time as a backend developer, that keeps me busy.

I can certainly help fixing issues and assure quality of pull requests.

DoctrineBehaviors is just super important for me and many production critical application. 👍

**Comment by TomasVotruba** [comment]
Hi, I'm current new maintainer (= doing all the merges and issues).

Help woudl be great. Can I ask you to go through the issues and identify those most likely to close and ping me there? Old, unclear, probably solved etc.

Thank you

Next step would be finishing this: https://github.com/KnpLabs/DoctrineBehaviors/issues/241
