### ISSUE TITLE
PreUpdate is called with an empty ChangeSet after translatable onFlush

### ISSUE THREAD

**Issue by KunoWA** [KnpLabs/DoctrineBehaviors#410]
I am using Gedmo/Translatable with PersonalTranslation objects.

When only a translatable field of an entity is changed, the PreUpdate listener catches the event but the change set with the changed fields in the entity is empty. 

1. Problem: this is’nt following the specification: preUpdate should only be called with a changeset.
2. Problem: The issue is not that preUpdate is called without any change of a field in the entity; also when only a translatable field is changed I expect preUpdate is triggered.
3. Problem: Inside the doctrine package I could trace that on the update event the changeset is correctly detected and stored but then
  - on flush is triggered: inside this event the translatable listener is called which is ‘changing’ the entity object. This result in a different hash of the entity object 
 - then the pre update listeners are called like mine registered listener. But for this event no changeset is found anymore, because the hash of the object changed, but the changeset is stored in the doctrine package with the objects hash as key.

Maybe this just happens when using the Personal Translation alternative for the respective entity. Because then the translations are a component of the entity and therefore any change in the onFlush event does also change the objects hash. 

Suggestion for a solution: why not the id is used as the key inside the collection of change sets?

Thanks for any help and ideas!

**Comment by KunoWA** [comment]
Maybe after changing any fields or association (eg any Personal Translation objects) the onFlush listener of the translatable component should call unitOfWork->recomputeSingleEntityChangeSet?
see 
https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html#onflush:
Changing primitive fields or associations requires you to explicitly trigger a re-computation of the changeset of the affected entity. This can be done by calling $unitOfWork->recomputeSingleEntityChangeSet($classMetadata, $entity).

**Comment by msphn** [comment]
Dunno, but maybe you'd like to ask at https://github.com/Atlantic18/DoctrineExtensions?

**Comment by TomasVotruba** [comment]
This is not the gedmo package but knplabs, so we can't help with this
