### ISSUE TITLE
[Translatable] Custom translatable row id

### ISSUE THREAD

**Issue by benjhoo** [KnpLabs/DoctrineBehaviors#414]
Hi,
I'm trying to make an existing Symfony project translatable with your bundle.

The problem is that the previous developper gave custom name to the entities id (ex: id_tableName).

When I generate SQL schema with doctrine, I have the following error : 
```
An exception occurred while executing 
'ALTER TABLE post_translation ADD CONSTRAINT FK_945A30422C2AC5D3 
FOREIGN KEY (translatable_id) REFERENCES post (id) ON DELETE CASCADE':

  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```
Because Doctrine is trying to add fk to a non existing field ('post'.'id instead of 'post'.'id_post').
How can I tell your bundle the real SQL id name ?

Thanks

**Comment by TomasVotruba** [comment]
Currently in 2.0 even translatable use native entity id
