### ISSUE TITLE
Translation id property could be not an int

### ISSUE THREAD

**Issue by marcosh** [KnpLabs/DoctrineBehaviors#415]
I just started to work in a project where the ids are actually UUIDs, so they are not integers. This causes some confusion because the type does not align with the one declared here:https://github.com/KnpLabs/DoctrineBehaviors/blob/9bc5a6a6a6e6cb92ac7467410876882994732325/src/Model/Translatable/TranslationProperties.php#L22.

I guess it would be nice to have a more generic type annotation to allow the usage of ids which are not integers

**Comment by TomasVotruba** [comment]
Resolved by https://github.com/KnpLabs/DoctrineBehaviors/pull/421

merged in https://github.com/KnpLabs/DoctrineBehaviors/pull/442
