### ISSUE TITLE
Implement a TranslationNormalizer that could be cacheable

### ISSUE THREAD

**Issue by bastnic** [KnpLabs/DoctrineBehaviors#417]
Hi folks, 

I'm not sure if it's the right place to post this, but I wanted to create the discussion. 

As per https://github.com/api-platform/core/issues/2593, we see that non resource object can have a quite horrific impact on serializer performance. I do not need Translation to be ressource as it's pretty tied to its base object (not sure I represent the majority on this case) so every Translation serialized cost a lot.

To fix this issue I implemented a custom normalizer, and I wanted to share it. Is it supposed to be taken by apip, DoctrineBehaviors, project itself, no clue, but It can be a performance problem so here is the ping.

```php
class TranslationNormalizer implements NormalizerInterface, CacheableSupportsMethodInterface
{
    /** @var AbstractNormalizer */
    private $normalizer;

    public function __construct(AbstractNormalizer $normalizer)
    {
        $this->normalizer = $normalizer;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        return $this->normalizer->normalize($object, $format, $context);
    }

    public function supportsNormalization($data, $format = null)
    {
        return (\is_object($data) && in_array(\Knp\DoctrineBehaviors\Model\Translatable\Translation::class, array_keys(class_uses($data))));
    }

    public function hasCacheableSupportsMethod(): bool
    {
        return true;
    }
}
```

FYI, the `$normalizer` given is an `ObjectNormalizer`, as it's the default in Symfony.

**Comment by mdeboer** [comment]
This can be simplified to:

```php
<?php

use Knp\DoctrineBehaviors\Model\Translatable\Translation;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;

class TranslationNormalizer extends ObjectNormalizer implements CacheableSupportsMethodInterface
{ 
    public function supportsNormalization($data, $format = null)
    {
        return (\is_object($data) && in_array(Translation::class, array_keys(class_uses($data))));
    }

    public function hasCacheableSupportsMethod(): bool
    {
        return true;
    }
}
```

**Comment by TomasVotruba** [comment]
Hi, feel free to send PR for this feature :+1:
