### ISSUE TITLE
[Translatable] Problems with configuration

### ISSUE THREAD

**Issue by treatys** [KnpLabs/DoctrineBehaviors#426]
Hello,

I've just installed DoctrineBehaviors to Symfony Flex and I cannot go thru configuration. I am getting this error:

`  The service "knp.doctrine_behaviors.translatable_subscriber.default_locale_callable" has a dependency on a non-existent parameter "locale". Did you mean one of these: "kern  
  el.default_locale", "knp.doctrine_behaviors.translatable_subscriber.current_locale_callable.class", "knp.doctrine_behaviors.translatable_subscriber.default_locale_callable.  
  class"?    `

Do you have any idea how to fix this?

**Comment by TomasVotruba** [comment]
This will be resolved on services level in new version
