### ISSUE TITLE
[Translatable] SF4 : currentLocale always null

### ISSUE THREAD

**Issue by gponty** [KnpLabs/DoctrineBehaviors#427]
Hi, 

Dont understand why currentLocale is always null (then setLocale is defined) :

$this = {App\Entity\Referentiel\CodifTranslation} [4]
 libelleCodif = null
 id = null
 locale = "fr"
 translatable = {App\Entity\Referentiel\Codif} [11]
  id = {int} 20
  codeCodif = "ETOILE"
  etatCodif = {int} 5
  userAjout = {Proxies\__CG__\App\Entity\User} [28]
  userModif = {Proxies\__CG__\App\Entity\User} [28]
  translations = {Doctrine\Common\Collections\ArrayCollection} [1]
  newTranslations = {Doctrine\Common\Collections\ArrayCollection} [1]
  currentLocale = null
  defaultLocale = "en"
  createdAt = {DateTime} [3]
  updatedAt = {DateTime} [3]

thank you

**Comment by TomasVotruba** [comment]
Hi, we'd need more intput from your config on this.

The locale is resolved from `RequestStack` service
