### ISSUE TITLE
mergeNewTranslations() needs to be fixed

### ISSUE THREAD

**Issue by holema** [KnpLabs/DoctrineBehaviors#428]
```diff
/**
     * Merges newly created translations into persisted translations.
     */
    public function mergeNewTranslations()
    {
        foreach ($this->getNewTranslations() as $newTranslation) {
-            if (!$this->getTranslations()->contains($newTranslation) && !$newTranslation->isEmpty()) {
+            if (!$this->getTranslations()->contains($newTranslation) && !$this->getNewTranslations()->isEmpty()) {
                $this->addTranslation($newTranslation);
                $this->getNewTranslations()->removeElement($newTranslation);
            }
        }
    }
```

needs to become because the newTranslation ArrayAcoolection chould be checked. not the foreach element by itself.

**Comment by TomasVotruba** [comment]
Could you send PR?

**Comment by danilphd** [comment]
> ```diff
> /**
>      * Merges newly created translations into persisted translations.
>      */
>     public function mergeNewTranslations()
>     {
>         foreach ($this->getNewTranslations() as $newTranslation) {
> -            if (!$this->getTranslations()->contains($newTranslation) && !$newTranslation->isEmpty()) {
> +            if (!$this->getTranslations()->contains($newTranslation) && !$this->getNewTranslations()->isEmpty()) {
>                 $this->addTranslation($newTranslation);
>                 $this->getNewTranslations()->removeElement($newTranslation);
>             }
>         }
>     }
> ```
> 
> needs to become because the newTranslation ArrayAcoolection chould be checked. not the foreach element by itself.

What is it for? If the collection (`getNewTranslations`) is empty, `foreach` will not work. This is a meaningless change.

More importantly, if you try to add a new translation with a value of `0`, `false`, or `"`.
```
    public function isEmpty(): bool
    {
        foreach (get_object_vars($this) as $var => $value) {
            if (in_array($var, ['id', 'translatable', 'locale'], true)) {
                continue;
            }

            if (! empty($value)) {
                return false;
            }
        }

        return true;
    }
```
https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Model/Translatable/TranslationMethodsTrait.php#L51

The translation will not be saved.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
