### ISSUE TITLE
Translate method loads all translation

### ISSUE THREAD

**Issue by Yolo-plop** [KnpLabs/DoctrineBehaviors#429]
Hello,

I noticed that my application returned an awfull lot of rows on every page and found out that Knp Translatable loads every translations when translate method is called.

Why is that? Any way to fix it?

Thanks

**Comment by TomasVotruba** [comment]
Hi, we need replicable test case.

Take this method - https://github.com/KnpLabs/DoctrineBehaviors/blob/3af6cb011aea600196168e937ab03ba913e01c0b/tests/ORM/TranslatableTest.php#L30-L50, duplicate it and add your own issues

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
