### ISSUE TITLE
Suggest dependencies instead of require them

### ISSUE THREAD

**Issue by mmarton** [KnpLabs/DoctrineBehaviors#455]
Hi @TomasVotruba 

Thanks for the lots of work you put into this repo.
A lot of dependencies have been added lately to the project in the require section of composer.json.
Would you consider moving them to the suggest part? For example if I don't intend to use uuidable functionality I shouldn't have to install the ramsey/uuid package.

WDYT?

**Comment by TomasVotruba** [comment]
Hey, in most cases, this leads to optional dependencies issue, see: https://matthiasnoback.nl/2014/04/theres-no-such-thing-as-an-optional-dependency/

There were already few such bugs where optional dependency was `doctrine/orm` package, but it only work with the *right* version. Hard to find the right by trail end error.

Saying that, only real solution is to have many small packages. That's just too much maintence for now, when the package is on the edge of refresh.
