### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by nicolashachet** [KnpLabs/DoctrineBehaviors#466]
Hi,

is it planned to ensure compatibility with Symfony 5 ?

Here is the result when activating the bundle : 

`Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in \vendor\knplabs\doctrine-behaviors\src\Bundle\DependencyInjection\Configuration.php on line 12 and at least 1 expected`

Thanks for the feedback.

**Comment by TomasVotruba** [comment]
Hi,

could you try latest alpha version? 
It has lot of BC changes, but it should be compatible with Symfony 5.

**Comment by nicolashachet** [comment]
Thanks for your reply.

I tried this in composer.json : 
```
"behat/transliterator": "dev-master",
"knplabs/doctrine-behaviors": "v2.0.0-alpha2"
```

But the requirements can't be resolved :
```

...
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/security v4.4.1 requires symfony/http-kernel ^4.4 -> no matching package found.
    - symfony/security v4.4.0 requires symfony/http-kernel ^4.4 -> no matching package found.
    - knplabs/doctrine-behaviors v2.0.0-alpha2 requires symfony/security ^4.4|^5.0 -> satisfiable by symfony/security[v4.4.0, v4.4.1].
    - Installation request for knplabs/doctrine-behaviors v2.0.0-alpha2 -> satisfiable by knplabs/doctrine-behaviors[v2.0.0-alpha2].

```
Any idea ?

**Comment by TomasVotruba** [comment]
This should be  resolved with `v2.0.0-alpha3`. Could you try it?

**Comment by nicolashachet** [comment]
Thanks, composer update is OK with alpha3.

I'll try use the bundle tomorrow.

**Comment by TomasVotruba** [comment]
Great, thanks for confirmation :+1: 

Working on a an upgrade path now:
https://github.com/KnpLabs/DoctrineBehaviors#upgrade-1x-to-2

**Comment by laurentHCM** [comment]
Hello Tomas,

Thanks for your job. I will also test.
I tried the upgrade process and there is a side effect by using this command 

vendor/bin/rector process src --config vendor/knplabs/doctrine-behaviors/upgrade/rector/doctrine-behaviors-20.yaml

If we use a fullname as return signature for a function , the full name is changed ( in fact all full names are changed) but in many case like when using Stripe, you have a Customer entity and Stripe has also a customer entity so we have to fully qualify the name

    public function createIntent(Customer $customer, float $amount): \Stripe\PaymentIntent
+    public function createIntent(Customer $customer, float $amount): PaymentIntent

**Comment by TomasVotruba** [comment]
Hi,

the import issue should be solved by: https://github.com/rectorphp/rector/pull/2459

**Comment by laurentHCM** [comment]
Hi Tomas,

Thanks.
I will do it again to check.

For translatable, I modified my entities according to the new format.
And now when I try to apply bin/console make:migration I have an error message:

In RuntimeReflectionService.php line 63:

Property App\Entity\CategoryTranslation::$id does not exist

I hope it can help.
Thanks.


De : Tomáš Votruba [mailto:notifications@github.com]
Envoyé : vendredi 20 décembre 2019 13:45
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Comment
Objet : Re: [KnpLabs/DoctrineBehaviors] Symfony 5 compatibility (#466)


Hi,

the import issue should be solved by: rectorphp/rector#2459<https://github.com/rectorphp/rector/pull/2459>

**Comment by TomasVotruba** [comment]
Yea, we need to complete that migration rule to Rector.

How does your normal id property look like?

**Comment by laurentHCM** [comment]
Here is the header of my Entity.
It works well  with Symfony4 and knplabs/doctrine-behaviors 1.6.0


use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Model as ORMBehaviors;
use Symfony\Component\Validator\Constraints as Assert ;

/**
* @ORM\Table(name="category")
* @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
*/
class Category
{
    use ORMBehaviors\Translatable\Translatable;

    /**
    * @ORM\Id()
    * @ORM\GeneratedValue()
    * @ORM\Column(type="integer")
    */
    private $id;


De : Tomáš Votruba [mailto:notifications@github.com]
Envoyé : vendredi 20 décembre 2019 14:00
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Comment
Objet : Re: [KnpLabs/DoctrineBehaviors] Symfony 5 compatibility (#466)


Yea, we need to complete that migration rule to Rector.

How does your normal id property look like?

**Comment by TomasVotruba** [comment]
Could you show me `CategoryTranslation` as well?

**Comment by laurentHCM** [comment]
Sure , this is the new version.

<?php

declare(strict_types=1);

namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait;

/**
* @ORM\Entity
*/
class CategoryTranslation implements TranslationInterface
{
    use TranslationTrait;

    /**
    * @ORM\Column(name="ca_name",type="string",length=128)
    */
    private $name;

    /**
    * @return string
    */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
    * @param  string
    * @return null


De : Tomáš Votruba [mailto:notifications@github.com]
Envoyé : vendredi 20 décembre 2019 14:09
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Comment
Objet : Re: [KnpLabs/DoctrineBehaviors] Symfony 5 compatibility (#466)


Could you show me CategoryTranslation as well?

**Comment by TomasVotruba** [comment]
I see. That's all I need, I'll prepare the migration rule during today

**Comment by laurentHCM** [comment]
Great. Do not hesitate to contact me If I can do something.

De : Tomáš Votruba [mailto:notifications@github.com]
Envoyé : vendredi 20 décembre 2019 14:18
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Comment
Objet : Re: [KnpLabs/DoctrineBehaviors] Symfony 5 compatibility (#466)


I see. That's all I need, I'll prepare the migration rule during today

**Comment by nicolashachet** [comment]
Hi, 

I tried successfully following behaviours :
- Loggable
- Blameable
- Timestampable
- Soft-Deletable

Thanks for your work !

**Comment by TomasVotruba** [comment]
I've updated the upgrade set with @ORM\Id property completion to the entity.

Could you retry the run? `rector/rector` dev-master is needed

**Comment by laurentHCM** [comment]
Hi Tomas,

I’ve tried today and it’s perfect.
Thanks a lot.
Merry Christmas.

De : Tomáš Votruba [mailto:notifications@github.com]
Envoyé : mardi 24 décembre 2019 06:58
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Comment
Objet : Re: [KnpLabs/DoctrineBehaviors] Symfony 5 compatibility (#466)


I've updated the upgrade set with @Orm<https://github.com/Orm>\Id property completion to the entity.

Could you retry the run? rector/rector dev-master is needed

**Comment by TomasVotruba** [comment]
Wow, that's great to hear. 
Have a great xmass too!

**Comment by TomasVotruba** [comment]
Wow, that's great to hear. 
Have a great xmass too!

**Comment by TomasVotruba** [comment]
Wow, that's great to hear. 
Have a great xmass too!

**Comment by laurentHCM** [comment]
Hi Tomas,

Maybe there is a point that can be improve.
If I launch two times this process   vendor/bin/rector process src --config vendor/knplabs/doctrine-behaviors/upgrade/rector/doctrine-behaviors-20.yaml
Then the variable var $id is declared two times in the EntityTranslation.php .

    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

Laurent.


De : Tomáš Votruba [mailto:notifications@github.com]
Envoyé : mardi 24 décembre 2019 17:42
À : KnpLabs/DoctrineBehaviors
Cc : laurent BARBEAU; Comment
Objet : Re: [KnpLabs/DoctrineBehaviors] Symfony 5 compatibility (#466)


Wow, that's great to hear.
Have a great xmass too!

**Comment by TomasVotruba** [comment]
Hi Laurent,

good point. I was thinking about it, but didn't get to real work.
Will be handled here: https://github.com/rectorphp/rector/pull/2479

**Comment by TomasVotruba** [comment]
Closing as Symfony 5 is on. 
For any new issues, just create a new issue here.

Thank you :heart:
