### ISSUE TITLE
[Upgrade][Rector] Issue with autoloading when using rector

### ISSUE THREAD

**Issue by fsoedjede** [KnpLabs/DoctrineBehaviors#485]
Hello @TomasVotruba,

Thanks for the work you have done in to upgrade this lib.
When trying to use the rector command as written here (https://github.com/KnpLabs/DoctrineBehaviors#upgrade-1x-to-2), I had an issue.

![image](https://user-images.githubusercontent.com/8562588/71809487-7bd13500-3070-11ea-9cbe-fab92ea38e64.png)

I think it's because the class `Knp\DoctrineBehaviors\Model\Blameable\Blameable` does not exists anymore in 2.0

What I did to be able to use rector is:
- Before `composer require knplabs/doctrine-behaviors:^2.0`:
    - Run the command `composer require rector/rector --dev`
    - Download the file [doctrine-behaviors-20.yaml](https://github.com/KnpLabs/DoctrineBehaviors/blob/master/upgrade/rector/doctrine-behaviors-20.yaml) to the root dir of my project
    - Run the command `vendor/bin/rector process src --config doctrine-behaviors-20.yaml` and check the changes
- `composer require knplabs/doctrine-behaviors:^2.0` and test

### Features status in my context
- Timestampable: 👌 
- Translatable: 👌 
- Sluggable: 🆗  (There is an issue when using sluggable with translations. See #488)
- Blameable: :thumbsdown: issue created #486 

Thanks

**Comment by TomasVotruba** [comment]
Hi,

thanks for feedback. This is expected, since you upgrade after the class was removed.

> What I did to be able to use rector is:

:+1: 

Could you update the post, so it's clear for other? 

---

> Features status in my context

Thanks for feedback!

Please report Sluggable and Blameable at Rector repository. Better with minimal reproducible code or test case.

**Comment by fsoedjede** [comment]
Hi,

Thanks for the quick reply.

I've updated my post. I hope it's clearer now.

For Sluggable and Blameable the issues are not related to rector (Sorry for the misleading subject) but how the new version is working.
If there is a change to be done, it must be done here before making any change in rector repository.

The issue for Blameable is created. I will add the issue for Sluggable later today

Regards

**Comment by TomasVotruba** [comment]
> I've updated my post. I hope it's clearer now.

I meant to ugprade the tutorial to upgrade with first running upgrade set, so people won't have the same problem same you:
https://www.tomasvotruba.cz/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/#how-to-migrate-from-version-1-to-2

> For Sluggable and Blameable the issues are not related to rector (Sorry for the misleading subject) but how the new version is working.
If there is a change to be done, it must be done here before making any change in rector repository.

I see.

> The issue for Blameable is created. I will add the issue for Sluggable later today

Awesome :+1: 

Thank you for fast work

**Comment by fsoedjede** [comment]
> I meant to ugprade the tutorial to upgrade with first running upgrade set, so people won't have the same problem same you:
https://www.tomasvotruba.cz/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/#how-to-migrate-from-version-1-to-2

Sorry I misunderstood. So, I should make a PR to update this page https://github.com/TomasVotruba/tomasvotruba.cz/blob/master/source/_posts/2020/2019-12-30-doctrine-behaviors-2-0-reloaded.md. Am I right?

**Comment by fsoedjede** [comment]
@TomasVotruba I think this issue is not relevant anymore. Is it ok for you?
