### ISSUE TITLE
[Blameable] Issue with doctrine mapping

### ISSUE THREAD

**Issue by fsoedjede** [KnpLabs/DoctrineBehaviors#486]
After installing v2.0 on an existing project and running the command `php bin/console doctrine:migrations:diff` I had many changes:
```sql
ALTER TABLE simple_pages DROP FOREIGN KEY FK_92660F3F896DBBDE;
ALTER TABLE simple_pages DROP FOREIGN KEY FK_92660F3FB03A8386;
ALTER TABLE simple_pages DROP FOREIGN KEY FK_92660F3FC76F1F52;
DROP INDEX IDX_92660F3FC76F1F52 ON simple_pages;
DROP INDEX IDX_92660F3FB03A8386 ON simple_pages;
DROP INDEX IDX_92660F3F896DBBDE ON simple_pages;
ALTER TABLE simple_pages ADD created_by VARCHAR(255) DEFAULT NULL, ADD updated_by VARCHAR(255) DEFAULT NULL, ADD deleted_by VARCHAR(255) DEFAULT NULL, DROP created_by_id, DROP updated_by_id, DROP deleted_by_id;
ALTER TABLE simple_pages_translations DROP FOREIGN KEY FK_B34E1BEA896DBBDE;
ALTER TABLE simple_pages_translations DROP FOREIGN KEY FK_B34E1BEAB03A8386;
ALTER TABLE simple_pages_translations DROP FOREIGN KEY FK_B34E1BEAC76F1F52;
DROP INDEX IDX_B34E1BEA896DBBDE ON simple_pages_translations;
DROP INDEX IDX_B34E1BEAB03A8386 ON simple_pages_translations;
DROP INDEX IDX_B34E1BEAC76F1F52 ON simple_pages_translations;
ALTER TABLE simple_pages_translations ADD updated_by VARCHAR(255) DEFAULT NULL, ADD deleted_by VARCHAR(255) DEFAULT NULL, DROP created_by_id, DROP updated_by_id, DROP deleted_by_id, CHANGE locale locale VARCHAR(5) NOT NULL, CHANGE slug created_by VARCHAR(255) DEFAULT NULL;
```

I should only have :
```sql
ALTER TABLE simple_pages_translations CHANGE locale locale VARCHAR(5) NOT NULL;
```

It's because this line https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/EventSubscriber/BlameableSubscriber.php#L142 returns `null` in cli context and `App\Entity\User` in http context.

CLI context: function `mapStringUser` (https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/EventSubscriber/BlameableSubscriber.php#L161) is used
HTTP context: function `mapManyToOneUser` (https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/EventSubscriber/BlameableSubscriber.php#L149) is used

This means even if I run the SQL queries above, I will have an issue because of this difference in the processing.

### My proposal

As previously done for blameable, there should be a parameter: `doctrine_behaviors_blameable_user_entity` equivalent of previous parameter `knp.doctrine_behaviors.blameable_subscriber.user_entity` in which the user class should be added.
Instead of using the UserProvider to update the class metadata info the parameter should be used.

I could be interesting to use an interface; so only classes implementing that interface would be allowed by the user provider.

**Comment by TomasVotruba** [comment]
I wonder, why does the userProvider work only in non CLI?

**Comment by fsoedjede** [comment]
Because `Symfony\Component\Security\Core\Security` is used to get the User objects. In CLI it will not return any User as there is no authentication.

**Comment by TomasVotruba** [comment]
What's the expected return value in CLI?
How can we get it from Symfony?

**Comment by fsoedjede** [comment]
In CLI, the expected result is null for `$security->getToken()` and `$security->getUser()` where `$security` is `Symfony\Component\Security\Core\Security`

I don't know yet how the user class can be recovered from symfony. I'll add it later

**Comment by TomasVotruba** [comment]
I see.

If you manage to make CLI working with Symfony, please send PR so we have this covered.
Thank you!

**Comment by fsoedjede** [comment]
I've created the PR #491 
I don't find another way to have the user class in CLI
