### ISSUE TITLE
[Sluggable + Translatable] Unique slug generatiion

### ISSUE THREAD

**Issue by fsoedjede** [KnpLabs/DoctrineBehaviors#488]
Hi,

When using Sluggable with Translatable, there might be an issue if we want the slug to be unique.
Example:
`src/Entity/SimplePage.php`
```php
<?php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors as ORMBehaviors;

class SimplePage implements ORMBehaviors\Contract\Entity\TranslatableInterface
{
    use ORMBehaviors\Model\Translatable\TranslatableTrait;
    /**
     * @var int
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @return int
     */
    public function getId(): ?int
    {
        return $this->id;
    }
}
```

`src/Entity/SimplePageTranslation.php`
```php
<?php
namespace App\Entity;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors as ORMBehaviors;

class SimplePageTranslation implements
    ORMBehaviors\Contract\Entity\SluggableInterface,
    ORMBehaviors\Contract\Entity\TranslationInterface
{
    use ORMBehaviors\Model\Sluggable\SluggableTrait;
    use ORMBehaviors\Model\Translatable\TranslationTrait;

    /**
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    /**
     * @var string
     * @ORM\Column(length=255)
     */
    private $title;

//Getter and setter
...
    public function getSluggableFields(): array
    {
        return ['title'];
    }
    public function shouldGenerateUniqueSlugs(): bool
    {
        return true;
    }
}
```

I'm using a2lix/translation-form-bundle so I have something like this:

![image](https://user-images.githubusercontent.com/8562588/71820116-77b41000-308e-11ea-95c4-71dcd092a155.png)

I can save both french and english translations at the same time but if for exemple I enter for the title field `test` in both french and english, it will be save:
- fr => test
- en => test
instead of 
- fr => test
- en => test-1
because the insert is in the same transaction and the check for the uniqueness is done early: 
![image](https://user-images.githubusercontent.com/8562588/71820638-06755c80-3090-11ea-849a-3e79e3eed48d.png)

Standalone Sluggable does not have any problem
It's specific to Sluggable + Translatable usage

I can't currently see how this could be fixed. Does anyone have an idea?

**Comment by TomasVotruba** [comment]
What happens when you change the order of subscribers?
