### ISSUE TITLE
[Blameable] Maximum function nesting level of '256' reached

### ISSUE THREAD

**Issue by toooni** [KnpLabs/DoctrineBehaviors#492]
I don't exactly know why but `BlameableSubscriber` creates an error "Maximum function nesting level of '256' reached" (segfault when xdebug is disabled). It seems like the issue can be solved for me by not using `$entityManager->getUnitOfWork()` directly in the constructor and calling `$this->entityManager->getUnitOfWork()` in the methods inside the subscriber.
I will be creating a PR as soon as https://github.com/KnpLabs/DoctrineBehaviors/pull/491 is merged.

**Comment by TomasVotruba** [comment]
It's infinite loop.
Could you share minimal entity code to replicate?

**Comment by TomasVotruba** [comment]
The referenced PR will need more time/work, so I would not wait for it

**Comment by toooni** [comment]
There's no code to replicate. The issue happens for me without having a single `BlameableInterface`. I only use the `Translation`/`Translatable` stuff and successfully migrated from v1 to v2.
I think it will be better anyway if the `getUnitOfWork` call doesn't happen in the constructor. If you agree I will make a PR tomorrow morning.

**Comment by TomasVotruba** [comment]
> I think it will be better anyway if the getUnitOfWork call doesn't happen in the constructor. If you agree I will make a PR tomorrow morning.

I see, yes :+1:

**Comment by toooni** [comment]
Since you were so fast I was able to create the PR right now ;)
