### ISSUE TITLE
Fields not generated

### ISSUE THREAD

**Issue by seb-jean** [KnpLabs/DoctrineBehaviors#497]
Hi,
I used TimestampableTrait and TimestampableInterface for my entity but the fields created_at and updated_at are not generated when I do the launch the command `php bin/console make:migration`
It's normal ?
Thanks :)

```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TimestampableInterface;
use Knp\DoctrineBehaviors\Model\Timestampable\TimestampableTrait;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post implements TimestampableInterface
{
    use TimestampableTrait;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }
}
```

**Comment by TomasVotruba** [comment]
Hi, I don't use `make:migration` so I'm not sure.

- What package version do you use?
- What Symfony version do you use?


What about these commands?

1) `bin/console  doctrine:schema:update --dump-sql`?

2) `bin/console doctrine:migrations:migrate`?

**Comment by gpgautier** [comment]
@seb-jean Did you add the bundle to your `bundles.php`?

If not, add:

`Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true],`

After that the fields should be added when you create a new migration.

**Comment by napestershine** [comment]
@TomasVotruba is it possible to add a SF 5 recipe ?

TIA

**Comment by TomasVotruba** [comment]
@napestershine What exactly should I imagine under it?

**Comment by seb-jean** [comment]
Thanks @gpgautier . It's works :)
I forgot to register the bundle.

**Comment by rogamoore** [comment]
Same happened to me - I think a recipe (https://flex.symfony.com/) would be helpful - I don't remember the last time I had to add a bundle manually to bundle.php :)

**Comment by TomasVotruba** [comment]
How could you make that recipe happen?

**Comment by rogamoore** [comment]
Actually according to the documentation here https://github.com/symfony/recipes#creating-recipes it should not be necessary to create a recipe (because no config files are needed) and Symfony Flex should automagically register the bundle. But somehow it doesn't recognize https://github.com/KnpLabs/DoctrineBehaviors as a Symfony bundle.

**Comment by rogamoore** [comment]
The reason according to https://github.com/symfony/flex/issues/278 is that https://github.com/KnpLabs/DoctrineBehaviors doesn't have the type `symfony-bundle` on packagist. You can see it if you compare these to entries:
- https://packagist.org/packages/knplabs/doctrine-behaviors
- https://packagist.org/packages/knplabs/knp-menu-bundle

So maybe someone can change this on packagist and all problems would be solved.

**Comment by rogamoore** [comment]
I created a PR https://github.com/KnpLabs/DoctrineBehaviors/pull/521
