### ISSUE TITLE
Fallback and collection issue

### ISSUE THREAD

**Issue by parhs** [KnpLabs/DoctrineBehaviors#5]
Hello. This bundle is simple and effective.However i cant use it as server supports php 5.3
First i was wondering whether there is a way to support fallback if desired locale doesnt exist.Maybe you could use default locale if specified fails.

    protected function findTranslationByLocale($locale)
    {
        $translations = $this->getTranslations()->filter(function($translation) use ($locale) {
            return $locale === $translation->getLocale();
        });

        return $translations->first();
    }

Also here why you dont use indexBy at metadata ?it would be simpler to use ->get($locale) 

As for fallback i see no easy solution.. Eager or lazy loading and doing fallback at findTranslationByLocale code .In sql as i know there isnt an easy way to get the desired locale from the translations table and default if it doesnt exist apart coalesce which requires extra effort .Is there any real solution for this ?

**Comment by akovalyov** [comment]
Closed by https://github.com/KnpLabs/DoctrineBehaviors/commit/f3bb1c32de251d22c26056ffaf1353121abcabca
