### ISSUE TITLE
[Tree] Add support to nested sets and closure tree strategies

### ISSUE THREAD

**Issue by damour** [KnpLabs/DoctrineBehaviors#50]
Now tree behavior support only materialized path.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
