### ISSUE TITLE
Attempted to call an undefined method named "getDefaultLocale"

### ISSUE THREAD

**Issue by labudzinski** [KnpLabs/DoctrineBehaviors#500]
https://github.com/KnpLabs/DoctrineBehaviors/commit/7514ad1c27350c3aaf62a89bb4dd09070cec453b#r36768859

**Comment by TomasVotruba** [comment]
What about $currentRequest->getDefaultLocale()?

**Comment by labudzinski** [comment]
@TomasVotruba instead of $currentRequest->getDefaultLocale() is $this->getDefaultLocale();

**Comment by TomasVotruba** [comment]
I see that. I'm asking what happens, when you put: `$currentRequest->getDefaultLocale()` there.

**Comment by labudzinski** [comment]
@TomasVotruba Works properly

**Comment by TomasVotruba** [comment]
PR then?

**Comment by labudzinski** [comment]
Yes, I prepared the task so that I would not forget.

**Comment by TomasVotruba** [comment]
Actually with Github online edit feature, it's faster to create such PR instead of making an issue.
