### ISSUE TITLE
Tag v1.6.1

### ISSUE THREAD

**Issue by mmarton** [KnpLabs/DoctrineBehaviors#503]
Hi @TomasVotruba 

Could you please tag version 1.6.1 at commit https://github.com/KnpLabs/DoctrineBehaviors/commit/072078422bcada395906ec96b192c6b30a93bebb ?

This is the point where the symfony 5 compatibility were added but the new dependencies are not yet.

thx

**Comment by TomasVotruba** [comment]
Hi, how exactly? 

Copy paste git would help

**Comment by simivar** [comment]
According to [Git book](https://git-scm.com/book/en/v2/Git-Basics-Tagging) snippet below should do the trick. Please notice it will create tag with current date.
```git
git tag -a 1.6.1 0720784
git push origin 1.6.1
```


If you want to backdate the tag to date of commit you should use:

for Windows:
```git
git checkout 0720784
set GIT_COMMITTER_DATE="Mon, 9 Dec 2019 15:23:03 +0100"
git tag -a 1.6.1
git push origin 1.6.1
set GIT_COMMITTER_DATE=
git checkout master
```

for Linux-based OS:
```git
git checkout 0720784
GIT_COMMITTER_DATE="Mon, 9 Dec 2019 15:23:03 +0100" git tag -a 1.6.1
git push origin 1.6.1
git checkout master
```

**Comment by TomasVotruba** [comment]
I'm getting to this now

**Comment by TomasVotruba** [comment]
It needed a message on Linux:

```diff
 git checkout 0720784
-GIT_COMMITTER_DATE="Mon, 9 Dec 2019 15:23:03 +0100" git tag -a 1.6.1
+GIT_COMMITTER_DATE="Mon, 9 Dec 2019 15:23:03 +0100" git tag -a 1.6.1 -m "legacy release"
 git push origin 1.6.1
 git checkout master
```

@simivar Thank you for making this!

**Comment by TomasVotruba** [comment]
1.6.1 is out - https://github.com/KnpLabs/DoctrineBehaviors/releases/tag/1.6.1
