### ISSUE TITLE
[Timestampable] Property subset update (field update)

### ISSUE THREAD

**Issue by stephanvierkant** [KnpLabs/DoctrineBehaviors#506]
I'm trying to migrate from Gedmo, but there is no alternative to this behavior:

    /**
     * @var \DateTime $contentChanged
     *
     * @ORM\Column(name="content_changed", type="datetime", nullable=true)
     * @Gedmo\Timestampable(on="change", field={"title", "body"})
     */
    private $contentChanged;

**Comment by TomasVotruba** [comment]
How it should work?

**Comment by AlexeyKosov** [comment]
@TomasVotruba it should update the `updatedAt` field only if a field from the list is changed, rather than any field. In other words, it would be great to have the ability to track only selected fields specified in an annotation.

**Comment by TomasVotruba** [comment]
Could you add such feature?

**Comment by TomasVotruba** [comment]
Closing as answered.
