### ISSUE TITLE
[Timestampable] Use createdAt OR updatedAt

### ISSUE THREAD

**Issue by stephanvierkant** [KnpLabs/DoctrineBehaviors#507]
I'm trying to migrate from Gedmo. I've got a couple of entities that can't be updated, so a `updatedAt` field doesn't make any sense. It would be great if one can use `createdAt` without using `updatedAt` (or maybe the other way around).

**Comment by TomasVotruba** [comment]
Could you provide a docs, how it would look like if implemented?

**Comment by TomasVotruba** [comment]
Closing as stale
