### ISSUE TITLE
TreeTrait::buildTree is broken

### ISSUE THREAD

**Issue by Zausenec** [KnpLabs/DoctrineBehaviors#511]
```Knp\DoctrineBehaviors\ORM\Tree\TreeTrait::buildTree``` is broken and violates phpdoc contract

**Comment by TomasVotruba** [comment]
Test case is needed

**Comment by gregquat** [comment]
The documentation about including the TreeTrait in the EntityRepository is also missing.

**Comment by TomasVotruba** [comment]
@gregquat PR?

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
