### ISSUE TITLE
Duplicate definition of column 'created_at' on entity 'App\Entity\User' in a field or discriminator column mapping.

### ISSUE THREAD

**Issue by MatthewBooth** [KnpLabs/DoctrineBehaviors#512]
```php
/**
 * Trait TimestampableEntityTrait
 *
 * @package App\Traits
 */
trait TimestampableEntityTrait
{
    /**
     * @var DateTimeInterface $createdAt
     * @ORM\Column(type="datetime", nullable=true)
     * @Serializer\Groups({"timestamp"})
     */
    protected $createdAt;

    /**
     * @var DateTimeInterface $updatedAt
     * @ORM\Column(type="datetime", nullable=true)
     * @Serializer\Groups({"timestamp"})
     */
    protected $updatedAt;
}
```

I'm unable to set any column data on a custom Trait without running into this error when running `make:migration`

`Duplicate definition of column 'created_at' on entity 'App\Entity\User' in  a field or discriminator column mapping.`

I need to be able to set nullable due to some weird SQLITE problem in Jenkins (works fine on my machine, Jenkins version complains about createdAt being `NULL`)

**Comment by MatthewBooth** [comment]
Nevermind. I was being dumb

**Comment by TomasVotruba** [comment]
No worries, my daily job :smile:  
What exactly happened?
