### ISSUE TITLE
Configuration of null vs not null

### ISSUE THREAD

**Issue by loevgaard** [KnpLabs/DoctrineBehaviors#513]
In your subscribers you set the nullability to true in most cases. But for a property like `createdAt` a lot of people would probably like that to be `nullable = false`.

I can provide a PR to fix this if you think this sounds fair :)

Thank you for taking up this great work!

**Comment by loevgaard** [comment]
@TomasVotruba: Did you see this? Wdyt? Do you want me to make a PR?

**Comment by TomasVotruba** [comment]
PR with test case would help.

**Comment by TomasVotruba** [comment]
Closing as stale
