### ISSUE TITLE
[Blameable] Query error when use blameable

### ISSUE THREAD

**Issue by ad3n** [KnpLabs/DoctrineBehaviors#519]
Query produced add extra `_id` in column

```Feb  9 20:57:43 |CRITI| REQUES Uncaught PHP Exception Doctrine\DBAL\Exception\InvalidFieldNameException: "An exception occurred while executing 'SELECT k0_.id AS id_0, k0_.kode AS kode_1, k0_.nama AS nama_2, k0_.created_by AS created_by_3, k0_.updated_by AS updated_by_4, k0_.deleted_by AS deleted_by_5, k0_.created_at AS created_at_6, k0_.updated_at AS updated_at_7, p1_.id AS id_8, p1_.kode AS kode_9, p1_.nama AS nama_10, k0_.propinsi_id AS propinsi_id_11, p1_.created_by_id AS created_by_id_12, p1_.updated_by_id AS updated_by_id_13, p1_.deleted_by_id AS deleted_by_id_14 FROM kabupaten k0_ LEFT JOIN propinsi p1_ ON k0_.propinsi_id = p1_.id ORDER BY k0_.id ASC LIMIT 30':  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'p1_.created_by_id' in 'field list'"```

**Comment by TomasVotruba** [comment]
This is hardly useful.
Failing test case is needed.

**Comment by ad3n** [comment]
@TomasVotruba : i dont know how to solve this problem, even after read the event subscriber

Just add minimal config like doc and you will get error like that

**Comment by TomasVotruba** [comment]
Copy this test, 
https://github.com/KnpLabs/DoctrineBehaviors/blob/master/tests/ORM/BlameableTest.php

modify it so the query is incorrect,

get query and compare it to desired one

**Comment by szymon-todes** [comment]
I have the same problem

Symfony 5.04 with EasyAdmin. Migration went through OK, but when I'm trying to list. edit or add items in EasyAdmin it comes up with an error:

`An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT u0_.id AS id_0, u0_.name AS name_1, u0_.deleted_at AS deleted_at_2, u0_.created_by_id AS created_by_id_3, u0_.updated_by_id AS updated_by_id_4, u0_.deleted_by_id AS deleted_by_id_5 FROM unit_type u0_ WHERE u0_.id IN (?, ?, ?) ORDER BY u0_.id DESC' with params [3, 2, 1]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'u0_.created_by_id' in 'field list'"`

**Comment by TomasVotruba** [comment]
Failing test case in PR is needed

**Comment by tlorens** [comment]
For some reason Blameable is attempting to fetch 'created_by_id', which isn't created when the schema is updated.  It really shouldn't be appending `_id` onto the end of the column name.  I'm having this issue as well Symfony 5.0.5, doctrine-behaviors 2.0

**Comment by szymon-todes** [comment]
Correct, but it seems to work fine for some entities in my project. I have implemented my own UserBundle with Blameable and it saves the details fine in database, but not for the entities in App (both entities has been setup in the same way). Could the location be an issue?

**Comment by szymon-todes** [comment]
In BlameableSubscriber there is a function mapEntity with if condition and `if` the first requirement is met the mapping to the table column is set to the created_by_id, but for `else` the column is created_by
```
if ($this->userProvider->provideUserEntity()) {    
    $this->mapManyToOneUser($classMetadataInfo);    
 } else {
    $this->mapStringUser($classMetadataInfo);
}
```
then in function mapManyToOneWithTargetEntity we have the below:
```
$classMetadataInfo->mapManyToOne([
    'fieldName' => $fieldName,
    'targetEntity' => $userEntity,
    'joinColumns' => [
         [
             'onDelete' => 'SET NULL',
        ],
    ],
]);
```
Maybe the array passed to Doctrine\ORM\Mapping\ClassMetadataInfo `mapManyToOne()` needs setting the column name?

**Comment by tlorens** [comment]
I was just tinkering with this today with a filter I was writing.  There's a few condition checks in the ClassMetadataInfo class that determines it's 'association'/'relationship'.  Which is where it appends `_id` to the $columnName.   I think the BlameableSubscriber may need more/less logic to determine the user's relationship to the object.  I some how got it trying to query created_by_id_id at one point.  I've since gave up and reverted to Gedmo.  Meh

**Comment by Tersoal** [comment]
It seems that was fixed and merged #491 but there is no new version with this fixes. Do you know when new release will be made?

**Comment by luca-nardelli** [comment]
I confirm that switching to dev-master instead of 2.0.1 solved the issue for me

**Comment by TomasVotruba** [comment]
Closing as resolved
