### ISSUE TITLE
Method mergeNewTranslations not work for me (Symfony 5.0.5, PHP 7.4.1)

### ISSUE THREAD

**Issue by uginroot** [KnpLabs/DoctrineBehaviors#525]
Old project code (not work for new projects):
```php
    public function create(array $names):Country
    {
        $entityManager = $this->getEntityManager();
        $country = new Country();

        foreach ($names as $locale => $name){
            $translation = $country->translate($locale)->setName($name);
        }

        $country->mergeNewTranslations();
        $entityManager->persist($country);
        $entityManager->flush();

        return $country;
    }
```

Now (working way):
```php
    public function create(array $names):Country
    {
        $entityManager = $this->getEntityManager();
        $country = new Country();

        foreach ($names as $locale => $name){
            $translation = $country->translate($locale);
            $translation->setName($name);
            $entityManager->persist($translation);
        }

        $entityManager->persist($country);
        $entityManager->flush();

        return $country;
    }
```

**Comment by t0F** [comment]
Hi uginroot, thanks for your workaround. 
I wanted to use that trait for a personnal symfony 5 project tonight, I will let you know if I face the same problem with mergeNewTranslations. 

Regards, 
t0FF

**Comment by jkabat** [comment]
@uginroot may it be a problem with missing persist:cascade definition of your translation relation?

It is a wild guess as I still did not upgrade to v2. Hopefully Ill find a time to do it soon.

**Comment by uginroot** [comment]
> @uginroot could it be a problem with missing persist:cascade definition of your translation relation?

Maybe, but the cascade = {"persist"} setting is not specified in ```TranslationPropertiesTrait->translatable``` and ```TranslatablePropertiesTrait->translations``` property. And before, these settings were not indicated. I think this is due to the transition to Symfony 5. But I did not find out the reason. The solution above works for me.
