### ISSUE TITLE
vendor/bin/rector process src --config vendor/knplabs/doctrine-behaviors/upgrade/rector/doctrine-behaviors-20.yaml

### ISSUE THREAD

**Issue by kakhavk** [KnpLabs/DoctrineBehaviors#528]
vendor/bin/rector process src --config vendor/knplabs/doctrine-behaviors/upgrade/rector/doctrine-behaviors-20.yaml

                                                                                                                        
 [ERROR] Class "Rector\Rector\Class_\AddInterfaceByTraitRector" was not found while loading                             
         "vendor/knplabs/doctrine-behaviors/upgrade/rector/doctrine-behaviors-20.yaml" file. Are you sure it is         
         correctly spelled?

**Comment by TomasVotruba** [comment]
I don't it's spelled correctly https://github.com/rectorphp/rector/blob/c6fa32590e754f0876e7c39c4a01e902cd96ba86/src/Rector/Class_/AddInterfaceByTraitRector.php#L18

**Comment by kakhavk** [comment]
Maybe but it shows this error. after I downgraded rector to v0.6.14 this error disappeared.
thanks!

**Comment by TomasVotruba** [comment]
Should be fixed instead.

**Comment by TomasVotruba** [comment]
I'll move it to Rector, so it's covered

**Comment by TomasVotruba** [comment]
It's fixed in the master btw.
Fixed by https://github.com/KnpLabs/DoctrineBehaviors/commit/a187e4f37117f1db44cddda657eaed8fbd5f82ba
