### ISSUE TITLE
Support for multiple Entity Managers?

### ISSUE THREAD

**Issue by benr77** [KnpLabs/DoctrineBehaviors#533]
My app has multiple entity managers configured. As soon as I enable this bundle, the app segfaults.

Are multiple entity managers supported?

Is there any additional configuration needed?

Thank you!

**Comment by TomasVotruba** [comment]
Hi, look at https://github.com/KnpLabs/DoctrineBehaviors/pull/509
It's half-done. Test are missing though.

The PR is stale, so you can take over and complete with tests.

**Comment by mduplouy** [comment]
Hi guys,
Sory but i looked to modify the tests and i didn't manage to handle it.

@benr77 imho the segfaults you get are not related to the fact that multiple em are not supported yet

**Comment by benr77** [comment]
Yes, I haven't found the cause of the segfaults yet. They do only occur when this bundle is enabled though.

**Comment by TomasVotruba** [comment]
That's probably circular refrence of some kind. I suspect something around EntityManager in constructors.

**Comment by TomasVotruba** [comment]
Closing as stale
