### ISSUE TITLE
[SoftDeletable/Timestampable] Change field names

### ISSUE THREAD

**Issue by AndreasA** [KnpLabs/DoctrineBehaviors#535]
Hi,

for various reasons on some of my entities I have to use different field names than the default ones. It would be nice if one could easily configure them. Especially in the event listeners. The traits themselves i could already change easily but that doesn't help that the listener would want to create the default fields.

**Comment by TomasVotruba** [comment]
Hi, how would you implement it?

**Comment by AndreasA** [comment]
Hi, I have been thinking about this as I don't want to make it overblown like with the Gedmo extensions.

Not sure if this is the best solution but it should work:

- Interface for the entity that has a `public static getFieldForUpdatedAt` etc. Maybe event separate interfaces so `createdAt` and `updatedAt` can be used without the other.
- Event listener checks for those field names instead of the hard coded ones (that is why `static` so it works without an instance).
- In updateTimestamps call the `'set' . ucase(static::getFieldForUpdatedAt())`.
- Then only the field defintion trait has to be custom made and everything else could be used from the bundle.

I think that wouldn't be that complicated to implement and don't require a lot of additional configuration / configuration parsing etc.

**Comment by TomasVotruba** [comment]
Could you maybe send PR with tests with your proposal? 
That would be much better to talk over

**Comment by AndreasA** [comment]
Sure. However, it might take me some time until I can do so.

**Comment by AndreasA** [comment]
@TomasVotruba Sorry for the delay. I completely forgot about it.
I will try to create the PR sometime this week as I should have time.

**Comment by TomasVotruba** [comment]
Great! I look forward to your PR!

**Comment by AndreasA** [comment]
@TomasVotruba Sorry. I did not forget this time but I admit I didn't want to take time to code anything during my short vacation.
So I actually did not create a PR yet. Maybe I will be able to do so tomorrow morning, if not I still want to create it as soon as possible but I can't promise a date.
As I currently did have an active project that needs that feature and uses DoctrineBehaviors it takes me a bit longer to create it...

**Comment by AndreasA** [comment]
@TomasVotruba 
Here is the PR:
https://github.com/KnpLabs/DoctrineBehaviors/pull/554/files

I think this would also add support for https://github.com/KnpLabs/DoctrineBehaviors/issues/507

One issue might be that if one did not use `TimestampableTrait` directly but the sub-traits, it would be a breaking change as new methods etc. are required.

**Comment by AndreasA** [comment]
For now I only did it for timestampable. If this is fine I should be able to add a similar structure to softdeletable.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
