### ISSUE TITLE
field createdAt/updatedAt not created by orm

### ISSUE THREAD

**Issue by sanchobouillant** [KnpLabs/DoctrineBehaviors#536]
I want to use Timestampable with my entities

I have the code:
```
class User implements TimestampableInterface
{
    use TimestampableTrait;

.......
}
```

Fields createdAt and updatedAt aren't mapped automatically? 

doctrine:schema:update doesn't create them. I try to add $createdAt and $updatedAt myself but the fields aren't updated.

Did I miss something?

**Comment by TomasVotruba** [comment]
Random idea: have your registered bundle?

**Comment by patrickmatsumura** [comment]
Try adding `Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle::class => ['all' => true]` to `bundles.php`

**Comment by cdesign** [comment]
I think you need to add a paragraph to the 'Usage' section of the README.md noting this bundle needs to be registered. In this new Symfony5/flex world we are all getting used to recipes doing that for us. I pulled my hair out for two hours over this and almost reverted to the antishov/StofDoctrineExtensionsBundle -- until I found this post.

Aside from that, thank you! for all of your time in updating and maintaining this bundle. It's absolutely indispensable. In fact, I keep wondering why this functionality isn't built directly into Doctrine itself, especially the 'Timestampable' and 'Blameable' traits.

**Comment by TomasVotruba** [comment]
> I think you need to add a paragraph to the 'Usage' section of the README.md noting this bundle needs to be registered. In this new Symfony5/flex world we are all getting used to recipes doing that for us. 

Could you send PR?

**Comment by uginroot** [comment]
#534 I made sure that the bundle registered automatically (symfony/flex) and removed this part from the documentation, there was simply no new release of KnpLabs/DoctrineBehaviors

**Comment by TomasVotruba** [comment]
Closing as resolved then.
