### ISSUE TITLE
 DoctrineBehaviors/docs/translatable.md

### ISSUE THREAD

**Issue by lxregistry** [KnpLabs/DoctrineBehaviors#540]
tried to day to install in symfony 5.0.6
I receive this error
 No identifier/primary key specified for Entity "App\Entity\Category". Every Entity must have an identifier/primary key.

what is wrong

**Comment by TomasVotruba** [comment]
ID is missing

**Comment by uginroot** [comment]
> ID is missing

Help is out of date. At first I also did not understand that I needed to add the id field myself. This was not required before.

**Comment by TomasVotruba** [comment]
> I could add this to the readme, but English is not my native language.

Neither mine. Better some English than outdated docs. Go for it!

**Comment by TomasVotruba** [comment]
This might also help with version 2: https://www.tomasvotruba.com/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/
