### ISSUE TITLE
Release 2.0.2 BC breaks due to bundle namespace change

### ISSUE THREAD

**Issue by virtualize** [KnpLabs/DoctrineBehaviors#542]
Bundle namespace changed from   
`Knp\DoctrineBehaviors\Bundle\DoctrineBehaviorsBundle` to   `Knp\DoctrineBehaviors\DoctrineBehaviorsBundle`  
So we need to update our `config/bundles.php`

Change comes from this PR https://github.com/KnpLabs/DoctrineBehaviors/pull/534 
Maybe reverting it and release a 2.0.3? 

I guess a lot of people will update their vendors soon, due to todays symfony security release 4.4.7 / 5.0.7.

**Comment by TomasVotruba** [comment]
See https://github.com/KnpLabs/DoctrineBehaviors/pull/534#issuecomment-60608940
