### ISSUE TITLE
[Sluggable] shouldRegenerateSlugOnUpdate should be public

### ISSUE THREAD

**Issue by prof-web-coding** [KnpLabs/DoctrineBehaviors#548]
https://github.com/KnpLabs/DoctrineBehaviors/blob/97bd87ef835c09307bd1477949035aabe544f3be/src/Model/Sluggable/SluggableMethodsTrait.php#L54

Should this not be `public function shouldRegenerateSlugOnUpdate(): bool `?

**Comment by TomasVotruba** [comment]
Why do you need it to be public?

**Comment by prof-web-coding** [comment]
Well, imagine a scenario where you want a user to select if the slug should be automatically generated or not... You could achieve it by overriding this method. I mean what is the point in having a private method returning always true or false?

**Comment by TomasVotruba** [comment]
Could you provide some code snippet that demonstrates that?

**Comment by prof-web-coding** [comment]
Yes, okay, it is actually not needed. Sorry. Thanks.
