### ISSUE TITLE
[Translatable] How to override default locale?

### ISSUE THREAD

**Issue by I-Valchev** [KnpLabs/DoctrineBehaviors#549]
The default locale is hardcoded as 'en' in `TranslatablePropertiesTrait`, however sometimes the default is something else, e.g. `en-GB`, or `nl`, etc.

What is the best way to override this (for example, from `services.yaml` or some other config, **not code**), so that in whatever way translatable entities are created/fetched, they will have that default locale?

Changing the defaultLocale after instantiation does not work, as earlier the default is used to set the currentLocale.

**Comment by Kocal** [comment]
The `defaultLocale` is configured by the `TranslatableSubscriber`, here:
https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/EventSubscriber/TranslatableSubscriber.php#L177-L180

And if you take a look at [`LocaleProvider#provideFallbackLocal()]`(https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Provider/LocaleProvider.php#L61-L77), it will use locale from: 
- current request, if it exists
- from parameter `locale`, if it exists
- from parameter `kernel.default_locale`, if it exists

**Comment by I-Valchev** [comment]
Right thanks!

Also not sure if this is very relevant, but I only now discovered that the translate fallback is about falling back from `en_GB` to `en` for example, not falling back to the default locale.  🤷‍♂️ I guess that makes sense, it's just my mental model was different.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
