### ISSUE TITLE
Problem when using make:migration

### ISSUE THREAD

**Issue by glanes** [KnpLabs/DoctrineBehaviors#551]
Hi all,

Not sure if the problem is with  this bundle but every time that  I run migration or diff I end up having duplicated sql queries to change the fields related to TranslatableTrait / TimestampableTrait.
Does not matter how many times I execute the migration, next time is going to generate all the code below again. 
I am using symfony 5 and 10.4.11-MariaDB
`        

$this->addSql('ALTER TABLE general_setting_time_management CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');

        $this->addSql('ALTER TABLE task_type CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');

        $this->addSql('ALTER TABLE task_type_translation CHANGE translatable_id translatable_id INT DEFAULT NULL, CHANGE task_type_t_description task_type_t_description VARCHAR(255) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');

        $this->addSql('ALTER TABLE module_translation CHANGE translatable_id translatable_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE module_t_description module_t_description VARCHAR(255) DEFAULT NULL');

        $this->addSql('ALTER TABLE module CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');

        $this->addSql('ALTER TABLE general_setting_time_management_translation CHANGE translatable_id translatable_id INT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
`
Any ideas what should I try to fix this?
Cheers

**Comment by glanes** [comment]
Sorry my mistake,

The setting was missing on the .env file
?serverVersion=10.4.11-MariaDB

**Comment by TomasVotruba** [comment]
Interesting. How could we detect such error for the user, so they know what to do?

It might be annoying
