### ISSUE TITLE
Please help with Tree

### ISSUE THREAD

**Issue by akorz** [KnpLabs/DoctrineBehaviors#552]
Hello,

For example I have tree like that

```
 root - child1 - child2
    |
    - child3
``` 

I have entity child2 and I want to build something like breadcrumbs: root > child1 > child2. How it can be done? I'm really puzzled.

**Comment by Kocal** [comment]
Hi, 

You can use `$node->getParentNode()` and a loop or recursivity. Something like this:
```php
$node = $child2;
$reversedTree = [];

while(null !== $node) {
  $reversedTree [] = $node;
  $node = $node->getParentNode();
}

var_dump($reversedTree );
```

**Comment by akorz** [comment]
@Kocal thank you for code :)

Here my code

```
        /** @var CategoryRepository $repository */
        $repository = $this->getRepository();

        /** @var Category $entity */
        foreach ($entities as $entity) {

            /** @var Category $node */
            $node = $entity;
            $breadcrumbs = [];

            while(null !== $node) {
                $breadcrumbs[] = $node->getName();
                $node = $node->getParentNode();
            }

            $entity->setBreadcrumbs($breadcrumbs);
        }
```

When I itterate my entities I always have parentNode is null:

```
  ["childNodes":"App\Domain\Category\Entity\Category":private]=>
  NULL
  ["parentNode":"App\Domain\Category\Entity\Category":private]=>
  NULL
  ["materializedPath":protected]=>
  string(74) "/6d317041-5b42-4948-8871-02c210961c31/620fb53d-9535-42c5-9979-7c253e836bdf"
```

Here my records from DB
SELECT BIN_TO_UUID(id), name, materialized_path from categories;

```
25fab3b7-82ba-4fe2-b7b3-09a375cb1a9a,Child12,/6d317041-5b42-4948-8871-02c210961c31/620fb53d-9535-42c5-9979-7c253e836bdf
620fb53d-9535-42c5-9979-7c253e836bdf,Child1,/6d317041-5b42-4948-8871-02c210961c31
6d317041-5b42-4948-8871-02c210961c31,<ROOT>,""
cbeca4d6-8066-4233-a73f-33f04d128050,Child2,/6d317041-5b42-4948-8871-02c210961c31
```

Where is my mistake?

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
