### ISSUE TITLE
[Timestampable] Unnecessary database access

### ISSUE THREAD

**Issue by pmontoya** [KnpLabs/DoctrineBehaviors#553]
Hi,

In [TimestampableSubscriber](https://github.com/KnpLabs/DoctrineBehaviors/blob/a076c4a4794d05aeaac81ec9ae18009d1696a939/src/EventSubscriber/TimestampableSubscriber.php#L63) a call to database connection is done to choose between `datetimetz` and `datetime` metadata format to add.
It throws an exception if you install your vendors before starting the database (or if you don't need a started database in the CI for example). Maybe it would be better to set the format in the configuration with a defaut value?

If it's ok for you, I will create the corresponding PR.

**Comment by TomasVotruba** [comment]
Hi,

PR might be helpful. Thanks :+1:
