### ISSUE TITLE
[Improvement] Configuration tree parse

### ISSUE THREAD

**Issue by pmontoya** [KnpLabs/DoctrineBehaviors#556]
Hi,

Do you think it would be better to have a specific configuration file (parsed thanks to a ConfigurationInterface) to set parameters than overriding parameters defined in services.yaml?

The symfony documentation : https://symfony.com/doc/current/bundles/configuration.html

We should then create configuration for composer flex plugin.

I would be happy to create the PR if it's ok for you but it will create a BC break.

**Comment by TomasVotruba** [comment]
Hi, from hindsight, we can give it a go :+1:

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
