### ISSUE TITLE
Using Timestampable throws an error when creating a new entity

### ISSUE THREAD

**Issue by parijke** [KnpLabs/DoctrineBehaviors#558]
I changed the entity like described in @TomasVotruba  blog https://www.tomasvotruba.com/blog/2020/01/06/migrate-gedmo-to-knplabs/ thinking it was very easy.

I can change an existing record and it captures the updatedAt time. But when creating a new record, an error is shown.

Can anyone help me with this?

```
TypeError:
Return value of App\Entity\Product::getCreatedAt() must implement interface DateTimeInterface, null returned

  at vendor/knplabs/doctrine-behaviors/src/Model/Timestampable/TimestampableMethodsTrait.php:16
  at App\Entity\Product->getCreatedAt()
     (vendor/symfony/property-access/PropertyAccessor.php:384)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty()
     (vendor/symfony/property-access/PropertyAccessor.php:93)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue()
     (vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms()
     (vendor/symfony/form/Form.php:377)
  at Symfony\Component\Form\Form->setData()
     (vendor/symfony/form/Form.php:481)
  at Symfony\Component\Form\Form->initialize()
     (vendor/symfony/form/FormBuilder.php:206)
  at Symfony\Component\Form\FormBuilder->getForm()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:842)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->createEntityForm()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:778)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->createNewForm()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:908)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->executeDynamicMethod()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:301)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->newAction()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:908)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->executeDynamicMethod()
     (vendor/easycorp/easyadmin-bundle/src/Controller/AdminControllerTrait.php:86)
  at EasyCorp\Bundle\EasyAdminBundle\Controller\EasyAdminController->indexAction()
     (vendor/symfony/http-kernel/HttpKernel.php:157)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:191)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (public/index.php:25)
  at require('/home/paul/www/test-knplabs/public/index.php')
     (/home/paul/.symfony/php/1f578ba6ccbb1add18b380021c9ebe0f3fd87e3c-router.php:29)   
```

**Comment by TomasVotruba** [comment]
Its seems the interface needs to be updated to nullable or your data completed first to database.

**Comment by parijke** [comment]
Sorry I do not understand what you mean. 
The getCreatedAt comes from the TimestampableTrait right? So how do I alter it to comply?

I just changed the entities according your blog. 

Does is has something to do with easyadmin? I use EA to manage the entities.

**Comment by TomasVotruba** [comment]
1. `TimestampableTrait` here might need an update itself. It might be wrong.

> Does is has something to do with easyadmin? I use EA to manage the entities.

I don't think so. I use it with EA too and don't have such problem. But I use it from the very start.

By "your data completed first to database" I ask about your database. If it had data before and you just added 2 columns, they're probably `null` now.

**Comment by parijke** [comment]
Ah yes, it has data in the database, and I ran a migration without problems
the funny thing is the entity UPDATES fine, I only get the error creating NEW entities.

The TimestampabaleTrait is from this bundle
`in vendor/knplabs/doctrine-behaviors/src/Model/Timestampable/TimestampableMethodsTrait.php (line 16)`

**Comment by parijke** [comment]
Just to be sure I deleted the fields from the database and created a mirgration. Running it gave the following:

`ALTER TABLE booking ADD created_by VARCHAR(255) DEFAULT NULL, ADD updated_by VARCHAR(255) DEFAULT NULL, ADD deleted_by VARCHAR(255) DEFAULT NULL, ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL
`
As far as I can reason these fields come from the bundle.

**Comment by parijke** [comment]
@TomasVotruba 

I created a clean environment, created one entity and added the doctrine-behaviours to the entity (just Timestampable). Then I created a clean database with schema.

It throws the exact same error. You can mimic this by cloning my test
https://github.com/parijke/test-dcotrine-behaviours

So I think there must be some kinfd of error / bug?

**Comment by parijke** [comment]
Any ideas?

**Comment by TomasVotruba** [comment]
I don't have time to run external repositories, but failing test case in pull-request would help.

**Comment by parijke** [comment]
I am happy to do that if you  can tell me what to do? I am sorry but as a relative newbie to symfony I do not exactly understand what you mean by a failing test case in pull-request.

**Comment by TomasVotruba** [comment]
You can inspire in recently merged pull-requests, e.g.
https://github.com/KnpLabs/DoctrineBehaviors/pull/546/files

**Comment by parijke** [comment]
As far as I can see a pul request id for software changes? I have no idea how to solve this error, I have just created a repo to replicate the error.

**Comment by TomasVotruba** [comment]
If you click on the id, there is code with sample test case. 
The test case needs to replicate your behavior and fail. Then we can focus on solving it.

**Comment by parijke** [comment]
Sorry I have no clue what to do with it. I am going to switch back to gedmo for now, as that worked sofar. I'll keep an eye on the repo and rerun my local test setup once in a while to see if it has been solved.

Thanks sofar,

**Comment by parijke** [comment]
I did a test with a little help of Javier (the developer behinf easyadmin). The symfony forms use nulls. So when I changed the `DateTimeInterface t`o `?DateTimeInterface` it worked.

**Comment by TomasVotruba** [comment]
That's what I suggested in 1st comment: https://github.com/KnpLabs/DoctrineBehaviors/issues/558#issuecomment-622394257

There would have to be a new trait for EasyAdmin to prevent people from using weak contract if they don't have it.

**Comment by nkl-kst** [comment]
@parijke I faced the same behaviour. Fixed it by not displaying the `createdAt` and `updatedAt` fields in the EasyAdmin backend. For me it's a resonable solution, because these fields are internal only and not intended to be manually edited.

**Comment by parijke** [comment]
Great tip!

**Comment by mpoiriert** [comment]
This is a simple a if we create a new Entity and call getCreated()/getUpdated() it should not failed.

The method signature in the trait should simple allow to return null value.

**Comment by grizzlylab** [comment]
Hi @TomasVotruba, I think you can close this issue :)

**Comment by TomasVotruba** [comment]
@grizzlylab Thanks for the ping :+1: :slightly_smiling_face:
