### ISSUE TITLE
[Sluggable] Unable to provide locale for the slugger service

### ISSUE THREAD

**Issue by snikolow** [KnpLabs/DoctrineBehaviors#559]
### Problem

I am playing around with the Sluggable behavior and it came to my attention that I am unable to provide a locale /even the fallback is not an option/ whenever I generate an entity slug.

Take a look at the following line - https://github.com/KnpLabs/DoctrineBehaviors/blob/v2.0.3/src/Model/Sluggable/SluggableMethodsTrait.php#L76 for the exact implementation and you can see that an option to provide locale is never considered. Even more, the method itself is marked as `private`, so not only we have to override the `generateSlug` method, but we also need the logic from `generateSlugValue`.

I've also took a look at the test cases and I believe they should be extended with some more complex localized strings for most languages. I am currently using the behaviour with cyrillic.

### Proposal

Move the class initialization to a new, `protected` method, something like `createSlugger` with nullable argument for `$locale` and then replace it by calling the new method in `generateSlugValue` so that we can override it in our entities and provide the locale on our own.

I am open to suggestions or further discussion, if a PR is necessary.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
