### ISSUE TITLE
Add behavior Sortable

### ISSUE THREAD

**Issue by seb-jean** [KnpLabs/DoctrineBehaviors#560]
Hi,
Is it possible to add the Sortable behavior?
Thank you :)

**Comment by TomasVotruba** [comment]
Hi, it was here before, but the business requirements for it very unique for each user.
In the end it lead to pile of useless code. So I've decided to remove it and let every user implement it in his or her own domain.

**Comment by vasilvestre** [comment]
Do you have any recommandation to do a clean code or a nice approach to this problem @TomasVotruba  ?
