### ISSUE TITLE
Locale Fallback behaviour

### ISSUE THREAD

**Issue by gion-andri** [KnpLabs/DoctrineBehaviors#562]
In d9dde9789f4cbdfceb261c0d2c348f1b66fa0d08 the fallback behaviour was changed: 

**It was**
- locale (e.g. de-DE)
- fallback locale (e.g. de)
- default locale (e.g. en)

**Now it is**
For "complex locales" like "de-DE"
- locale (e.g. de-DE)
- fallback locale (e.g. de)

For "simple locales" like "de"
- locale (e.g. de)
- default locale (e.g. en)

This seems a little weird, because the default locale is now ignored in some cases. Why was this change made? 

Many browsers send Accept-Language headers with language and region like de-DE, for those users the new behaviour now only works if a page is available in de-DE or de. A different default locale is never provided. 

Do you have any recommendations, how the "old" behaviour could be restored?

Thank you very much :)

**Comment by ossinkine** [comment]
I think it was a mistake. According to the commit message, it should be just changing bool to null type hinting.

@gion-andri could you please create a PR with the fix?

**Comment by ossinkine** [comment]
@gion-andri Don't worry I've created the fix
