### ISSUE TITLE
[Translatable] Issue with TranslatableSubscriber::setLocales

### ISSUE THREAD

**Issue by EVDW** [KnpLabs/DoctrineBehaviors#563]
I was in v1.4.0 and try to update to 1.6.1, and I have an issue with the method `setLocales` in **TranslatableSubscriber** class because of the change line 319 of the condition:
 `!$this->getClassAnalyzer()->hasMethod($classMetadata->reflClass, 'setCurrentLocale')` 
to 
`!$this->isTranslatable($classMetadata)`.

My problem is that I have a entity which extends another one, and when the method `setLocales` checks if the class `isTranslatable`, so verify if the class have translation trait, my class hasn't, while the class which is extended, yes. So the current locale is never set.

=> I just look better the `isTranslatable` method which calls `getClassAnalyzer()->hasTrait` and take a look on `hasTrait` method, I see a third argument which fix my problem! This argument is `isRecursive` and checks into parent class!

**Comment by mnowaczyk** [comment]
Thanks for the bug report, I would have wasted all day looking for it.

**Comment by raziel057** [comment]
I also got the this issue while upgrading to 1.6.1. I'm currently not able to migrate on 2.x because of more complex situations. As it's a regression compared to previous version, would it be possible to create a 1.6.2 with this simple fix?

Just add ``true`` value to ``isRecursive`` In TranslatableSubscriber:
```
private function isTranslatable(ClassMetadata $classMetadata)
{
        return $this->getClassAnalyzer()->hasTrait($classMetadata->reflClass, $this->translatableTrait, true);
}
```

Currently I have to duplicate the TranslatableSubscriber.

Thanks

**Comment by TomasVotruba** [comment]
I'm sorry to hear this. We only support version 2 and onward.

Migration to v2 can be done with Rector: https://tomasvotruba.com/blog/2019/12/30/doctrine-behaviors-2-0-reloaded/

**Comment by raziel057** [comment]
I'm currently not able to make a PR as the branch 1.6.x doesn't exists here.

I understand that you support only v2 but it's a very small change and could avoid others to loose time analyzing this. I can see you have done a v 1.6.1 to fix a BC break also, so it could be the same here.

It's not always possible to migrate easily even using Rector if you have specific implementations for some Behaviors. In my case for example I had to provide a different implementation for Loggable to be able to collect changes in related entities / related collections.

**Comment by TomasVotruba** [comment]
In that case I'd go for local patches: https://tomasvotruba.com/blog/2020/07/02/how-to-patch-package-in-vendor-yet-allow-its-updates/

It will also help you with other bugs in other packages.

**Comment by raziel057** [comment]
Thanks for the link. I will use my fork until I can switch to v2.

https://github.com/raziel057/DoctrineBehaviors/tree/1.6.2
