### ISSUE TITLE
Symfony 5.1 and private services

### ISSUE THREAD

**Issue by davividal** [KnpLabs/DoctrineBehaviors#564]
I'm starting a new project using Symfony 5.1.

When I try to install DoctrineBehaviors, it fails due to:

      Cannot autowire service "Knp\DoctrineBehaviors\Provider\UserProvider": argument "$security" of method "__construc
  t()" references class "Symfony\Component\Security\Core\Security" but no such service exists.

I have symfony security packages installed as described in https://pehapkari.cz/blog/2019/12/23/how-we-upgraded-pehapkari-cz-from-symfony-4-to-5-in-25-days , but it was not enough.

Then I remembered https://symfony.com/blog/new-in-symfony-5-1-deprecate-public-services-into-private-services and edited my services.yaml:

    diff --git a/config/services.yaml b/config/services.yaml
    index 5c4b417..4893c85 100644
    --- a/config/services.yaml
    +++ b/config/services.yaml
    @@ -11,6 +11,9 @@ services:
         autowire: true      # Automatically injects dependencies in your services.
         autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    +    Symfony\Component\Security\Core\Security:
    +        public: true
    +

And everything worked just fine.

Is it worth a PR or am I missing something here?

**Comment by TomasVotruba** [comment]
> Is it worth a PR or am I missing something here? 

Not sure what changed in Symfony, but this fix is needed to make bundle work. 

So go ahead, send PR please  :+1:

**Comment by TomasVotruba** [comment]
Closing as answered.
