### ISSUE TITLE
Update doctrine packages?

### ISSUE THREAD

**Issue by crabnky** [KnpLabs/DoctrineBehaviors#565]
Hi,

Can we add latest doctrine packages to composer?

        "doctrine/common": "^2.7 || ^3.0",
        "doctrine/persistence": "^1.3.4 || ^2.0", 

And one more:

        "symplify/package-builder": "^7.2 || ^8.0",

**Comment by TomasVotruba** [comment]
Hi, sure, send PR :+1:

**Comment by TomasVotruba** [comment]
Clsoing as answered.

**Comment by sixpeteunder** [comment]
@TomasVotruba was this ever worked on?

**Comment by TomasVotruba** [comment]
Check the `composer.json`
