### ISSUE TITLE
[Wish] Make a dockerfile to speed up integration.

### ISSUE THREAD

**Issue by ONiAd** [KnpLabs/DoctrineBehaviors#571]
In order to contribute properly to this project, there's quite a bunch of dependencies to be satisfied, like phpstan and ecs. Would be nice to provide with a docker image to setup development process.

**Comment by Kocal** [comment]
> like phpstan and ecs

Won't a `composer install` not sufficient?

**Comment by TomasVotruba** [comment]
PR with Docker is welcomed

**Comment by ONiAd** [comment]
Arguably, I tend to work all the code on docker machines (keeping the host computer as clean as possible).
 The setup of the project I'm working on is not the same as this project, and trying to replicate checker dev dependencies to satisfy the pull request has failed due composer requirements, so, cannot speed up the development (nor this one nor mine).

**Comment by TomasVotruba** [comment]
I'd me happy to merge it when you find a time
