### ISSUE TITLE
[Translatable] Override default translatable_id column field

### ISSUE THREAD

**Issue by akira28** [KnpLabs/DoctrineBehaviors#574]
I'm trying to use a preexisting table with the Translatable behaviour. My problem is that the column name for the translatable id is not `translatable_id`. Is there a way to override or fake somehow the name of the column without copying and replacing the whole TranslatableSubscriber class?

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
