### ISSUE TITLE
2.0.5 fails to install because of roukmoute/hashids-bundle recipe

### ISSUE THREAD

**Issue by mmarton** [KnpLabs/DoctrineBehaviors#578]
Hi @TomasVotruba 

You added a new dependency in the lastest (2.0.5) PATCH release (roukmoute/hashids-bundle) which has a symfony recipie that fails to install with the exception of:

```
In Hashids.php line 418:
!!                                       
!!    Missing BC Math or GMP extension.
```
So this is literally a breaking change, not a patch.

In https://github.com/KnpLabs/DoctrineBehaviors/issues/455
I already tried to ask you to move these dependencies to suggestions. The majority of us don't use uuid-s, and if sometime I would use, I would prefer the symfony version of it.

So again: Please move these packages to suggestions and please fix this release

**Comment by TomasVotruba** [comment]
Hi, I didn't expect so much troubles for such a small addition. I'm sorry for caused troubles.

I'll revert it and recommend to implement it as standalone package who needs it.

**Comment by mmarton** [comment]
Thanks for the fast reaction

**Comment by TomasVotruba** [comment]
Thank you for sensitive and clear feedback
