### ISSUE TITLE
Using Blameable with bulk Insert and Updates -- Error undefined index from UnitOfWork (checking for User)

### ISSUE THREAD

**Issue by ahmadzai** [KnpLabs/DoctrineBehaviors#581]
Hi every one, 
Thanks for the nice bundle, I am using blameable and timestampable in my project, the issue is that when I am creating a record through a form, everything is fine, but when I am using batch insert/update process (that I created using vhichuploader/phpspreadsheet, etc.). I tried to manually set the createdBy and updatedBy, it works with new record insertions, but in my case I have to check before insertion if a record is already exist, then I am putting those records in an array, once the new records insertion process finish (after flushing and clearing the entity manager) then I am updating those records that were already existed, fetching them one by one from database and changing some of the values, but calling flush after modifying the entity gives me an error "Undefined Index: xxxxxxxxxxx", tracing that goes to UnitOfWork -> getEntityIdentifier() passing it the User object that is just created (to set the properties of updatedBy/createdBy). If I am trying to manually set those properties, it gives me another sort of errors (new entities found that are not persisted, try to set cascading persist in the annotation). 
By the way, I am not sure if this issue is relevant here or not, but if I try without (blameable) it works.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
