### ISSUE TITLE
Incommpatible with symfony 5.2-rc

### ISSUE THREAD

**Issue by mmarton** [KnpLabs/DoctrineBehaviors#608]
Hi!

if the bundle is installed symfony's boot process got into an infinite loop and dies with memory out.

UPDATE:
works with 5.2.0-RC2. I'll wait the final release and close it after.

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting. Having Symfony 5.2 in CI would help to keep eyes on it.

Any ideas where that gets stuck?

**Comment by mmarton** [comment]
I'm not an expert of the DI container build process, but seemd like the getdoctrineentitymanager and get***subscriber called each other. I'll check out tomorrow

**Comment by TomasVotruba** [comment]
I see. That might a be a good lead.

Thank you for looking into it

**Comment by mmarton** [comment]
It seems like the problem it with the Blameable and SluggableSubscribers that take EntityManager az a constructor argument 
You can get the entitiymanager from the events.

```php
public function prePersist(LifecycleEventArgs $lifecycleEventArgs): void
{
    $em = $lifecycleEventArgs->getEntityManager();
...
}
```

**Comment by TomasVotruba** [comment]
Thanks for finding the spot.

How could we fix this place to avoid circular loops?

**Comment by mmarton** [comment]
https://github.com/symfony/symfony/issues/39015

This looks similar, so maybe nothing, maybe what I suggested in the earlier comment

**Comment by diabelb** [comment]
You can test this pull request:
https://github.com/KnpLabs/DoctrineBehaviors/pull/609
composer require diabelb/doctrine-behaviors

**Comment by Hetarnam** [comment]
> You can test this pull request:
> #609
> composer require diabelb/doctrine-behaviors

Works perfectly for me in 5.2 with your patch, had infinite loop before on cache:clear

**Comment by mmarton** [comment]
Tested with 5.2.0-RC2 and the problen mo longer exists. (still not nice to inject entitymanager to a subscriber, but thats another story)

**Comment by mmarton** [comment]
Works with the 5.2.0 release

**Comment by TomasVotruba** [comment]
Thank you
