### ISSUE TITLE
[Geocodeable] Make locateable supported in mysql

### ISSUE THREAD

**Issue by AlmogBaku** [KnpLabs/DoctrineBehaviors#61]
right now its throw me an error:
 `Cannot get geometry object from data you send to the GEOMETRY field`

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
