### ISSUE TITLE
Symfony 5.2 + Uuidable + oracle  problem 

### ISSUE THREAD

**Issue by celsoandrade** [KnpLabs/DoctrineBehaviors#614]
I'm getting this error when I try to use Uuidable

> Warning: oci_bind_by_name(): Invalid variable used for bind

The problem is related to ramsey/uuid but I couldn't fix it

![image](https://user-images.githubusercontent.com/144451/109199247-f762d980-777d-11eb-9e7d-568efc40c49c.png)

Thank you

**Comment by TomasVotruba** [comment]
Hi, we need a test case to replicate
