### ISSUE TITLE
Improve descriptions for collaboration with translation memories

### ISSUE THREAD

**Issue by elfring** [KnpLabs/DoctrineBehaviors#619]
[A programming interface for translations is described](https://github.com/KnpLabs/DoctrineBehaviors/blob/8068b089ed71ea141183deb84f41f9e651b7f59c/docs/translatable.md#translatable "Update candidate") to some degree.
* :thinking: How do you think about to [improve collaboration with translation memories](https://en.wikipedia.org/wiki/Translation_memory "Description for the usage of translation memories")?
* :crystal_ball: Would you like to work with [any additional information systems for this application domain](https://en.wikipedia.org/wiki/Translation_management_system "Description for the usage of translation management systems")?

**Comment by TomasVotruba** [comment]
Hi, I'm not sure what you mean. Could you show us some Doctrine code example that demonstrates your issue?

**Comment by elfring** [comment]
[Example for provided information](https://github.com/KnpLabs/DoctrineBehaviors/blob/8068b089ed71ea141183deb84f41f9e651b7f59c/docs/translatable.md#entity "Documentation"):
```php
/** @var \Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface $category */
$category = new Category();
$category->translate('fr')->setName('Chaussures');
$category->translate('en')->setName('Shoes');
```

* I imagine that [desired translations should be stored in other data formats](https://symfony.com/doc/current/translation.html#translation-resource-file-names-and-locations "Translation Resource/File Names and Locations") (than PHP source code) for some use cases.
* Would you like to add any advices for [the automatic generation of forms](https://symfony.com/doc/current/forms.html#form-types "Description for the usage of form types") together with translated fields?

**Comment by TomasVotruba** [comment]
So you're trying to update the documentation or extends features?

**Comment by elfring** [comment]
:thinking: I guess that my clarification request will touch both information areas.

**Comment by TomasVotruba** [comment]
Feel free to send PRs then 👍

**Comment by elfring** [comment]
:crystal_ball: How will it become clearer to import translation data from other information sources for a selected object-relational mapping?

**Comment by TomasVotruba** [comment]
I don't use translations, so I can't help here

**Comment by elfring** [comment]
Can any other contributors get into the mood to add more helpful information?

**Comment by TomasVotruba** [comment]
Closing for lack of traction here. Feel free to send PR with extending documentation. It would be very helpful :+1:
