### ISSUE TITLE
[Feature Request] Sluggable transliterate, and improve getSluggableFields

### ISSUE THREAD

**Issue by denys281** [KnpLabs/DoctrineBehaviors#63]
Hi! Would be great if Sluggable, will can make automatic transliteration from Cyrillic, like in gedmo ext. Now from the box it works only with Latin. 

And it will be great if I can pass to generateSlug() not only field name, but also  fox example getters name.

**Comment by MAXakaWIZARD** [comment]
@denys281 Everything is implemented and merged, you can close this issue now.

**Comment by denys281** [comment]
@MAXakaWIZARD  I haven't permission to do this ;-)

**Comment by docteurklein** [comment]
thanks \o
