### ISSUE TITLE
Symfony Uuid vs Ramsey Uuid

### ISSUE THREAD

**Issue by mkalisz77** [KnpLabs/DoctrineBehaviors#633]
Hi,

As now Symfony has his own Uuid/Ulid component
( https://symfony.com/blog/new-in-symfony-5-2-doctrine-types-for-uuid-and-ulid) maybe  ramsey /
uuid should be replaced by standard Symfony library?

Regards,
Michal Kalisz

**Comment by TomasVotruba** [comment]
Hi,

that might break some stuff and force people to switch. 
How can we allow both?

**Comment by mkalisz77** [comment]
I'm not Symfony master, one possibility is to have it in another new Trait.

**Comment by TomasVotruba** [comment]
We'll need tests to make sure it works. Would you like to add it?

**Comment by mkalisz77** [comment]
Hi,
I've prepared PR for using ULID from Symfony.

**Comment by TomasVotruba** [comment]
Hi, I'm going through old opended issues and PRs to cleanup too-long-opened items and close them. Thank you for your contribution and time.

We needs a feature with test and passing CI to be able to merge it without letting a bug in.
If this is still relevant for you, please add code with test and make CI pass first. Then we'll able to merge your feature without further waiting :+1: 

Thank for understanding.
