### ISSUE TITLE
Tree no parentNode and childNodes saved to database 

### ISSUE THREAD

**Issue by wucherpfennig** [KnpLabs/DoctrineBehaviors#638]
Hi, I am trying to use the tree behavior. I am including the behavior as follows:

```php
/**
 * @ORM\Entity(repositoryClass=ExtendedPimCategoryRepository::class)
 */
class ExtendedPimCategory implements TranslatableInterface, TreeNodeInterface, TimestampableInterface
{

    use TreeNodeTrait;
    use TranslatableTrait;
    use TimestampableTrait
```

By doing so the property materialized path will be stored to the database. But the `parentNode` and `childNodes` properties from `TreeNodePropertiesTrait` are always `null`.

Am I missing something? How else can I quickly find the `parentNode`?

BR wucherpfennig

**Comment by wucherpfennig** [comment]
'solved' ... you just have to load the elements with the `getTree` function...

**Comment by abdellahrk** [comment]
Hi @wucherpfennig, can you please elaborate? I have spent hours looking for the solution to this. Loading from the repository does not work as the doc says - `$categoryRepositon->getTree()` 
Where should `getTree()` be placed?

**Comment by wucherpfennig** [comment]
@abdellahrk sorry for the late reply!

In your repository add the `TreeTrait`

```php

...
use Knp\DoctrineBehaviors\ORM\Tree\TreeTrait;
...

class MyEntityWithTreeTraitRepository extends ServiceEntityRepository
{

    use TreeTrait;

   ....
```

In your Service etc. use the repository as follows:

```php
....
/** @var MyEntityWithTreeTrait $tree */
$tree = $this->repository->getTree(path: $anyMyEntityWithTreeTrait->getRealMaterializedPath());

// eg. return !empty($tree) ? $tree : NULL;
// eg. $tree->getChildNodes()
....
```

---
Update
In my case I also had to make sure that I set the a "good default" (especially eg for root nodes):

```php
private function saveMyEntityWithTreeTraitIfNotExists(....): MyEntityWithTreeTrait {
	...
	$anyMyEntityWithTreeTrait = $this->findBySomething();
	if (empty($anyMyEntityWithTreeTrait)) {
		$anyMyEntityWithTreeTrait = new MyEntityWithTreeTrait();
		$anyMyEntityWithTreeTrait->setMaterializedPath(MyEntityWithTreeTrait::getMaterializedPathSeparator()); // set good default
	}
	...
```

---

I hope this explains how it works.

BR wucherpfennig

**Comment by abdellahrk** [comment]
Hi @wucherpfennig, thank you very much. This is so helpful I cannot thank you enough.
