### ISSUE TITLE
Improve GitHub repo's description to help finding this bundle in GitHub search

### ISSUE THREAD

**Issue by bocharsky-bw** [KnpLabs/DoctrineBehaviors#644]
Change repo's description to:

> Doctrine2 behavior traits that help handling Blameable, Loggable, Sluggable, SoftDeletable, Uuidable, Timestampable, Translatable, Tree behavior

It would help to find this bundle in GitHub search by e.g. "Translatable" keyword, it's not there currently: https://github.com/search?o=desc&q=doctrine+Translatable&s=stars&type=Repositories

Because repo's description for now is just:

> Doctrine2 behavior traits

<img width="540" alt="Screenshot 2021-08-03 at 19 07 52" src="https://user-images.githubusercontent.com/3317635/128049107-03b8121a-d7b5-4326-aea0-e15479a0f718.png">

**Comment by TomasVotruba** [comment]
Hi, thasnk for suggestions.

Untfortunately I don't have that high access and original maintainers only "rent" me the repository for maintenance.

**Comment by TomasVotruba** [comment]
Closing as we're locked out of this level repository maintenance.

**Comment by bocharsky-bw** [comment]
Can't we ping someone who has access to it? /cc @docteurklein @PedroTroller ?

**Comment by TomasVotruba** [comment]
@bocharsky-bw I'll leave this to you then :+1:

**Comment by PedroTroller** [comment]
@bocharsky-bw @TomasVotruba done !

**Comment by bocharsky-bw** [comment]
@PedroTroller awesome, thank you!
