### ISSUE TITLE
Upgrade not working with Rector

### ISSUE THREAD

**Issue by vnenrico20** [KnpLabs/DoctrineBehaviors#645]
Hi,

I'm trying to upgrade bundle to latest version. I followed the README instruction to install Rector. 

But I couldn't find this file:  vendor/rector/rector/config/set/doctrine-behaviors-20.yaml
(https://github.com/rectorphp/rector/tree/main/config/set)

Did I do anything wrong?

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

The old config path is deprecated. I've updated README with new Rector API. Check it out and let me know :+1:

**Comment by vnenrico20** [comment]
Thanks a lot for your quick response & action. It works perfectly now.

Much appreciated!!!

**Comment by TomasVotruba** [comment]
Glad to hear that! You're welcome
