### ISSUE TITLE
composer issue (not really a bug)

### ISSUE THREAD

**Issue by eddeh** [KnpLabs/DoctrineBehaviors#669]
Just to let you guys know, on symfony 5.3.10 and PHP 8.0.12 
`composer require knplabs/doctrine-behaviors`  
gives errors:
`Problem 1
    - knplabs/doctrine-behaviors 2.3.0 requires doctrine/dbal ^2.9 -> found doctrine/dbal[v2.9.0, ..., 2.13.4] but the package is fixed to 3.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - knplabs/doctrine-behaviors[2.3.1, ..., 2.3.3] require doctrine/dbal ^2.13 -> found doctrine/dbal[2.13.0, ..., 2.13.4] but the package is fixed to 3.1.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires knplabs/doctrine-behaviors ^2.3 -> satisfiable by knplabs/doctrine-behaviors[2.3.0, 2.3.1, 2.3.2, 2.3.3].`

Only way the package can be installed is to downgrade Doctrine DBAL from 3 to 2
(with `composer require knplabs/doctrine-behaviors -W`   )
For me, this is not an issue as I dont use DBAL and DBAL ^2.12 supports PHP 8 anyway.

**Comment by TomasVotruba** [comment]
Hi, it looks like we should bump deps to `doctrine\dbal` and `^3.1`. 
Could you send PR?

**Comment by eddeh** [comment]
@TomasVotruba will do asap

**Comment by eddeh** [comment]
@TomasVotruba done
