### ISSUE TITLE
Translatable - How to access a property of the joined Translation entity in Symfony2 Form Type Entity with query_builder?

### ISSUE THREAD

**Issue by krafas** [KnpLabs/DoctrineBehaviors#67]
I have Category and CategoryTranslation entities and I want to load category.id and category_translation.title to form field, but I can't access title, because category has no method getTitle() (it is in the CategoryTranslation). 

``` php
$builder
    ->add(
        'category',
        'entity',
        array(
            'class' => 'AcmeDemoBundle:Category',
            'property' => 'title',
            'query_builder' => function (CategoryRepository $repository) {
                return $repository->getAllCategoriesByLocaleQueryBuilder('en');
            },
        )
    )
);
```

The CategoryRepository method:

``` php
public function getAllCategoriesByLocaleQueryBuilder($locale)
{
    $queryBuilder = $this->getEntityManager()->createQueryBuilder();

    $queryBuilder
        ->select('c, c.id, ct.title')
        ->from('AcmeDemoBundle:Category', 'c')
        ->join('c.translations', 'ct')
        ->where('ct.locale = :locale')
        ->setParameter('locale', $locale);

    return $queryBuilder;
}
```

If I'm trying to select from CategoryTranslation when I can't set correct identifier for form field, because it is set from CategoryTranslation (CategoryTranslation.id but in this case I need CategoryTranslation.translatable_id)

I'm not sure if in this case I can use Symfony2 form field type entity or should I use other field type. Any suggestions?

**Comment by Mondane** [comment]
@krafas does this solution still work for you ? I get this error:

> Cannot read property "name" from an array. Maybe you intended to write the property path as "[name]" instead.

When using this code:

```
                $form
                    ->add('nourishmentType, 'entity', array(
                            'required' => true,
                            'label' => 'Nourishment type',
                            'class' => "VaartiesDwehBundle:NourishmentType",
                            'property' => "translations['{$this->request->getLocale()}'].name",
                        )
                    );
```

**Comment by Mondane** [comment]
I have found out a bit more that makes me use the following syntax:

```
                $form
                    ->add('nourishmentType, 'entity', array(
                            'required' => true,
                            'label' => 'Nourishment type',
                            'class' => "VaartiesDwehBundle:NourishmentType",
                            'property' => 'name',
                        )
                    );
```

In my entity, I have this _call function which normally makes $entity->getName() work, even if that property is translated:

```
   /**
     * This function makes it possible to call translated properties without
     * having to know if the enitity is translated.
     *
     * @param string $method
     * @param array $arguments
     * @return type
     */
    public function __call($method, $args)
    {
        if (!method_exists(self::getTranslationEntityClass(), $method)) {
            $method = 'get'.ucfirst($method);
        }

        return $this->proxyCurrentLocaleTranslation($method, $args);
    }
```

But the entity form element doesn't use that __call function. After adding a getName() to my entity, the entity form element behaves as expected:

```
    public function getName() {
        return $this->__call('name', array());
    }
```

With this clue, I'm gonna search in symfony where it checks for the existence of a property.

**Comment by akovalyov** [comment]
Random guess from the guys passing by - can it be `__call` method of PropertyAccessot disabled by default? (http://symfony.com/doc/current/components/property_access/introduction.html#magic-call-method).

**Comment by Mondane** [comment]
@akovalyov , I was just typing this up on the same subject:

Well, it turns out, the choice form type is used to render the list. This type creates a PropertyAccessorBuilder but without 'magic' enabled. This means that the __call function is totally ignored. After fiddling around in vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccess.php* in function *createPropertyAccessorBuilder* :

change

```
    public static function createPropertyAccessorBuilder()
    {
        return new PropertyAccessorBuilder();
    }
```

to

```
    public static function createPropertyAccessorBuilder()
    {
        $p = new PropertyAccessorBuilder();
        $p->enableMagicCall();
        return $p;
    }
```

it works. Now, this isn't a nice solution. For now, I'll settle with adding that getName() function to my entity and asking symfony why the choise type works like this.

**Comment by Mondane** [comment]
This guy: http://stackoverflow.com/a/30331620 talks about creating your own entity form type. I tried that, but failed 

> Neither the property "name" nor one of the methods "getName()", "name()", "isName()", "hasName()", "__get()" exist and have public access in class "Proxies\__CG__\Vaarties\DwehBundle\Entity\NourishmentType".

For testing, I added a __construct to the existing entity type:

```
    public function __construct(\Doctrine\Common\Persistence\ManagerRegistry $registry, \Symfony\Component\PropertyAccess\PropertyAccessorInterface $propertyAccessor = null, \Symfony\Component\Form\ChoiceList\Factory\ChoiceListFactoryInterface $choiceListFactory = null)
    {
        $propertyAccessor = new \Symfony\Component\PropertyAccess\PropertyAccessor(true);
        parent::__construct($registry, $propertyAccessor, $choiceListFactory);
    }
```

in which I created the accessor with magic but it doesn't work. Somehow, symfony doesn't pick it up. 

If someone is willing to go on further with this, be my guest. I also made a start with a new form type:

```
<?php
namespace Vaarties\DwehBundle\Form\Type;

use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\ChoiceList\Factory\ChoiceListFactoryInterface;
use Symfony\Component\PropertyAccess\PropertyAccessor;
use Symfony\Component\PropertyAccess\PropertyAccessorBuilder;
use Symfony\Component\PropertyAccess\PropertyAccessorInterface;

class MagicEntityType extends EntityType
{
    public function __construct(ManagerRegistry $registry, PropertyAccessorInterface $propertyAccessor = null, ChoiceListFactoryInterface $choiceListFactory = null)
    {
        $propertyAccessor = new PropertyAccessor(true);
        parent::__construct($registry, $propertyAccessor, $choiceListFactory);
    }

    public function getName()
    {
        return 'magic_entity';
    }
}
```

I'll use the workaround mentioned earlier (adding getters to my main entity).

**Comment by akovalyov** [comment]
What about configuration of `property_accessor` service in your compiler pass? Generally it should work (never tried it though)

**Comment by Mondane** [comment]
I've read about that yesterday, see https://groups.google.com/forum/#!topic/symfony2/YgH5oUMsuYk . Since that will make it a global change, I'll stick with my workaround. Maybe in the future, I'll fiddle more with a new form type. Thanks for the pointer though.
