### ISSUE TITLE
generateSlugValue method has wrong return type

### ISSUE THREAD

**Issue by garak** [KnpLabs/DoctrineBehaviors#672]
[This return type](https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Model/Sluggable/SluggableMethodsTrait.php#L55) is wrong, it's probably left after a previous refactoring of the method.
The current code can't return anything but a string. The phpdoc should be removed and `: string` should be added instead.

**Comment by TomasVotruba** [comment]
Hi, it might be the case. Could you send PR?

**Comment by garak** [comment]
PR sent. Do you think it's possible, if PR approved, to backport such fix to versions 2.3 and 2.2? I've got a project that is still on Symfony 4/PHP 7.4

**Comment by TomasVotruba** [comment]
See https://github.com/KnpLabs/DoctrineBehaviors/issues/668#issuecomment-953069622

There are more packages that already dropped PHP 7.*, so this would not help.
Instesad, I recommend to upgrade never PHP/Symfony with Rector. It's ~2-4 days work.
