### ISSUE TITLE
Constraints applied to the properties of traits

### ISSUE THREAD

**Issue by pdias** [KnpLabs/DoctrineBehaviors#684]
I don't know if it's an error or if there's some configuration I'm missing.

I'm using the translations and importing the traits, but when submitting my entity's form an error occurs in the **_currentLocale_** (**_This value should not be null._**) property (**defined in TranslatableTrait/TranslatablePropertiesTrait**) .

If I run the command:

**debug:validator --show-all "src/Entity"**

I check that contraints are being applied to all properties in the trait, for example:

**currentLocale** have  **Symfony\Component\Validator\Constraints\Type** and **Symfony\Component\Validator\Constraints\NotNull** .

Is there any way I can resolve this situation?!!

I'm using PHP 8, Symfony 5,4.2 

Thanks for your attention and sorry for bothering you.

**Comment by TomasVotruba** [comment]
Hi, thanks for the report. Could you add a PR with failing test case of this behavior? We can try to find solution to it then.

**Comment by pdias** [comment]
I found the problem (**configuration in validator.yaml**), 

If we uncommented this **App\Entity** line, **_every entity would get auto-mapped_** validation without needing the extra annotation.

`auto_mapping:
           App\Entity\: []`

**And this was uncommented...** commenting was everything as intended.

@TomasVotruba thanks for your willingness to help.

Thanks.

**Comment by TomasVotruba** [comment]
Thanks  for sharing your solution :clap: I'm glad it works!

**Comment by pdias** [comment]
> Thanks  for sharing your solution :clap: I'm glad it works!

@TomasVotruba maybe it's a good idea to use @Assert\disableautomapping in some trait properties as we avoid disabling auto_mapping in validation.yaml

Just an idea.
