### ISSUE TITLE
Timestampable entity - updated_at column contains timestam after creating.

### ISSUE THREAD

**Issue by skocdopolet** [KnpLabs/DoctrineBehaviors#693]
Hello,

I am using a timestampable entity. When I create a new entity and save it, the "created_at" field correctly contains the current datetime, but the "updated_at" field also contains the current date too.

As I expect, the field "updated_at" should be null. It should be contain the datetime value only after updating this entity.

Cheers
Tomas

**Comment by TomasVotruba** [comment]
Hi, this is expected value.
The difference is that updated at is always changed.
