### ISSUE TITLE
For some reason, blameable and timestampable doesn't work on one entity

### ISSUE THREAD

**Issue by parijke** [KnpLabs/DoctrineBehaviors#702]
I cannot seem to find out why the fields stay empty on this certain entity (which worked before)

All other entities still work with these behaviours. I drives me crazy trying to find the issue. Any suggestions, pointers where to look?

**Comment by TomasVotruba** [comment]
Hi Paul,

thanks for reporting. That might be some race-condition in DI.
Could you send a PR with failing test case? It would be easier to reproduce and then fix.

**Comment by parijke** [comment]
I understand that it would help to locate the problem. Going to try it, but I "think" it would be hard to mimic in a minimalistic setup. Is there a way I can identify the race condition in any way?

**Comment by TomasVotruba** [comment]
I'd use debugging techniques you're used to.
We'll need the test case in any way, as a proposed fix could be changed in the future and regression introduced.

**Comment by parijke** [comment]
OK. I've determined a way to reproduce it locally anyway. As soon as I inject 
private ProjectRepository $projectRepository in my own subscriber (without even using it further on) it starts to fail.

As soon as I remove the repo from the constructor, it works again.

**Comment by parijke** [comment]
Probably my ignorance for injecting a repository in a prePersist even subscriber?

**Comment by parijke** [comment]
@TomasVotruba, forgive me if I am talking nonsense, I am way less experienced as you are.

I think, after investigating code, it happens because the "dynamic fields" line createdAt do not exists (yet) at some point, because they are added dynamically to the entities by using and Event Subcriber itself? Because somewhere early in the stack I get:
`Class App\Entity\Todo has no field or association named createdAt`

I get the same response if I try to query for that property using doctrine:query:dql

So it is definetly something in the order of race conditions I think.

**Comment by parijke** [comment]
I've solved it for now by removing the injection of the repository by an injection of the entitymanager and make a call to the getRepository method. So my "problem" is solved now, or at least I have a work around.

**Comment by TomasVotruba** [comment]
> Probably my ignorance for injecting a repository in a prePersist even subscriber?

I don't use much Doctrine last couple years, but that might be the case. AFAIK subscribers should be as thin as possible, and repository could conflict there.
