### ISSUE TITLE
[Translatable] currentLocale = null

### ISSUE THREAD

**Issue by sitobcn82** [KnpLabs/DoctrineBehaviors#71]
Using the trait \Knp\DoctrineBehaviors\Model\Translatable\Translation inside an Entity, I see that the property currentLocale is never setted , so we always obtain the default locale ('en') in all the calls to $this->translate().

In my symfony2 controller I've setted correctly the locale and all the requests goes with the correct locale.

If I change this getDefaultLocale, all the trasnlations are made correctly, so I think that is no problem with the fallback.

**Comment by gregumo** [comment]
I have the same issue with a2lix/translation-form-bundle. It seems that when an entity use Translatable Trait you can't use a form without a2lix TranslationsType to manage all your locales. The only way I found to have a Form for a specific local, is to set the currentLocale manually before creating your form.

```php
// GIven I have a PageTranslation for an entity Page
$page = new Page();
$page->setCurrentLocale($request->getLocale());
$form = $this->createForm(SingleLocalePageType::class, $page);
...
```

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
