### ISSUE TITLE
service alias is deprecated, use "Symfony\Bundle\SecurityBundle\Security" instead

### ISSUE THREAD

**Issue by PhilETaylor** [KnpLabs/DoctrineBehaviors#731]
`Since symfony/security-bundle 6.2: The "Symfony\Component\Security\Core\Security" service alias is deprecated, use "Symfony\Bundle\SecurityBundle\Security" instead. It is being referenced by the "Knp\DoctrineBehaviors\Provider\UserProvider" service.`

**Comment by Kocal** [comment]
A PR #727 is already opened

**Comment by PhilETaylor** [comment]
Awesome - thanks. Sorry I did not see that one
