### ISSUE TITLE
[Tree] Tree\Node fails on setParentNode(null)

### ISSUE THREAD

**Issue by EquisTango** [KnpLabs/DoctrineBehaviors#74]
setChildNodeOf() must check parent node for null, to allow parent-less (root) nodes.

**Comment by CharlyPoppins** [comment]
Temporary I use this
´´´
if (null === $this->getCategorieParente()) {
	$this->setMaterializedPath('/');
} else {
	$this->setChildNodeOf($this->getCategorieParente());
}
´´´
