### ISSUE TITLE
Search or filter results by translatable fields in Knplabs doctrine behaviors bundle (Symfony2)

### ISSUE THREAD

**Issue by kvaje** [KnpLabs/DoctrineBehaviors#84]
Hello,
I have seen some questions about this topic but without good answers.

I have entity Site with fields:
ID, host, enabled
and translatable entity SiteTranslations with fields name, description, keywords. (I use Knplabs translatable strategy)

I would like to filter results in list table by name, host and enabled values. For host and enabled field it is working ok, because those fields are in Site repository. But I can't find a solution how to filter by "name" which is in SiteTranslatable repository and in table sitetranslation.

Here is my form validation in controler:

<pre>
….
if ($form->isValid()) { // a check to see if the form is valid 
     // filter records
      if($form->get('filter')->isClicked{
           if ($filter->getHost() !== null) $criteria['host'] = $filter->gethost();
           if ($filter->getEnabled() !== null) $criteria['enabled'] = $filter->getEnabled(); 
      }
}
…
$sites = $em->getRepository('PnetConlocoBundle:Site')->getList($criteria);
</pre>

And getList function in repository:

<pre>
public function getList($criteria = null)
{
             $qb = $this->createQueryBuilder('s')
                   ->select('s')
                   ->orderBy('s.root', 'ASC')
                   ->addOrderBy('s.lft', 'ASC'); 
         
            if($criteria !== null):
                foreach ($criteria as $field => $value):
                    if (!$this->getClassMetadata()->hasField($field)):
                        continue; // Make sure we only use existing fields (avoid any injection)
                    endif;  
                   
                    if ($this->getClassMetadata()->getTypeOfField($field) === 'string'
                        || $this->getClassMetadata()->getTypeOfField($field) === 'text'):
                        $qb ->andWhere($qb->expr()->like('s.'.$field, ':s_'.$field))
                            ->setParameter('s_'.$field, '%'.$value.'%');    // search LIKE %value%
                    else:    
                        $qb ->andWhere($qb->expr()->eq('s.'.$field, ':s_'.$field))
                            ->setParameter('s_'.$field, $value);
                    endif;
                endforeach;
            endif;        
        return $qb->getQuery()->getResult();
    }
</pre>

Does anybody know how update this code that it will work also for translatable fields?

Thanks in advance.

**Comment by Einenlum** [comment]
Seems there is now a PR for filtering even with empty values: https://github.com/KnpLabs/DoctrineBehaviors/pull/349

Seems this issue is old and the topic is far from the first question so I'm closing it for now.
