### ISSUE TITLE
ODM support?

### ISSUE THREAD

**Issue by Szpadel** [KnpLabs/DoctrineBehaviors#91]
Hi, I like this project, but I don't see any ODM support in master branch.
it shouldn't be hard to implement this.
If there are any plans for support MongoDB?

**Comment by docteurklein** [comment]
there was a tentative: https://github.com/KnpLabs/DoctrineBehaviors/pull/15
 but nothing yet. I don't plan to add it anytime soon, but if someone is willing to give it atry, don't hesitate! :)

**Comment by TomasVotruba** [comment]
Closing as scope for another package

**Comment by alterphp** [comment]
> Closing as scope for another package

Hi @TomasVotruba and thank you for taking on maintaining this package !

Do you know any existing intention for another package ? Do you have any idea on such implementation ? I guess Tree and Translatable are irrelevant for Mongo ODM as it relies on relations.

I'm pretty sure that only subscribers are specific, models may be the same. I'm gonna work on it anyway. Any hint from you is welcome !

**Comment by TomasVotruba** [comment]
Hi, I have no better knowledge about this package than you can see from the code. 
I just use it and it works :) and make sure it works in the future
