### ISSUE TITLE
[Geocodable] 'DISTANCE' returns miles, not km.

### ISSUE THREAD

**Issue by kimlai** [KnpLabs/DoctrineBehaviors#97]
Hello,

After getting inconsistent results when computing distances using the `DISTANCE` function provided by this bundle, we discovered that the `<@>` operator actually returns miles, not kms (see [here](http://www.postgresql.org/docs/9.3/static/earthdistance.html#EARTHDISTANCE-POINT-OPERATORS)).

Looking at your [tests](https://github.com/KnpLabs/DoctrineBehaviors/blob/fabd11672901d7d80d36e5ea73a23971f3b99aa4/tests/Knp/DoctrineBehaviors/ORM/GeocodableTest.php#L78) and [documentation](https://github.com/KnpLabs/DoctrineBehaviors/blob/1812ec01566bea7b1cc4e9332d75e4b037f75ecd/README.md#geocodable), it would seem that you're unaware of this.

We've seen that postgresql also provides a function `earth_distance` which returns the distance in meters (and can also output other units be tweaking the `earth` function). This could help solve the problem.

I'd be happy to try to implement this solution if you think it's a good idea.

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
