### ISSUE TITLE
[Geocodable] the DISTANCE function is broken.

### ISSUE THREAD

**Issue by kimlai** [KnpLabs/DoctrineBehaviors#99]
Hi again,

As a follow up for [this issue](https://github.com/KnpLabs/DoctrineBehaviors/issues/97), I found another bug in the Geocodable trait, but this one is critical.

The signature of the constructor of your Point class looks like this : 

``` php
public function __construct($latitude, $longitude);
```

But according to the [documentation](http://www.postgresql.org/docs/9.3/static/earthdistance.html#EARTHDISTANCE-POINT-OPERATORS) : 

> The module relies on representing Earth locations as values of type point, in which **the first component is taken to represent longitude in degrees, and the second component is taken to represent latitude in degrees**. Points are taken as (longitude, latitude) and not vice versa because longitude is closer to the intuitive idea of x-axis and latitude to y-axis.

Which is completely stupid because it's not compatible wtih the `ll_to_earth` function, which takes the latitude first.

Anyway, all your distance computations are off, which you can clearly see in the info I added [here](https://github.com/KnpLabs/DoctrineBehaviors/pull/98/files#diff-936ba6edcc4a9b6c1b6d343505ca07dbR100), since the first of your tests should fail.

But simply invert lat and long in the Point constructor would not be compatible with my new `DISTANCE_IN_METERS` function, not without some ugly hack (I think).

**Comment by TomasVotruba** [comment]
I'm going through the old issues/PRs and closing most of them so we can focus on now.
This one is missing any feedback or reasoning so I cannot deduce anything from it.

Thanks for you though, but closing for reasons above.

If the bug still remains, please send failing test case to verify it. Only with test we'll be albe to help.
